"""Artículos del blog: medición de AEO, checklist de AEO y schema para AEO (EN y ES)."""

POSTS = [
    # -----------------------------------------------------------------------
    # Cómo medir el AEO
    # -----------------------------------------------------------------------
    {
        'key': 'aeo-measure',
        'publish_gmt': '2026-10-27 13:00:00',
        'cat': 'aeo',
        'image': 'post-aeo-measure',
        'en': {
            'slug': 'how-to-measure-aeo',
            'title': 'How to Measure AEO: AI Citations, Brand Mentions and AI Referral Traffic',
            'seo': ['How to Measure AEO: Citations, Mentions and AI Traffic',
                    'How to measure AEO: track AI citations and brand mentions in ChatGPT, Gemini and Perplexity, AI referral traffic in GA4 and your Search Console signals.',
                    'measure aeo'],
            'tldr': 'Rank tracking alone cannot tell you whether AI assistants use your content. To measure AEO, combine a fixed list of questions checked across ChatGPT, Gemini, Perplexity and AI Overviews, AI referral traffic in GA4, Search Console data, brand search and what your leads tell you. No single metric is perfect, so read the trend.',
            'intro': 'To measure AEO (Answer Engine Optimization) is to track whether AI assistants mention, cite and link your brand when people ask the questions that matter to your business. There is no single report for it, so you combine a fixed list of questions checked across AI tools, AI referral traffic in GA4, Search Console data and lead feedback.',
            'body': [
                ['h2', 'Why rank tracking is not enough for AEO'],
                ['p', 'Classic SEO reports show positions and clicks for keywords. AI answers work differently: the same question can produce a different answer each time, the answer may mention your brand without linking to you, and many users never click. A page can rank well and still be missing from the answer the buyer actually reads.'],
                ['p', 'That does not make rankings useless. Assistants and AI Overviews draw on web content, so organic visibility is still a useful leading signal. It just needs to be complemented with metrics that look at the answers themselves and at the business they generate.'],
                ['h2', 'To measure AEO, track a fixed list of key questions'],
                ['p', 'The core of AEO tracking is a list of the questions your buyers really ask, taken from sales calls, support tickets, search data and your own FAQs. You check the same list on a regular schedule and log what the AI tools answer.'],
                ['ul', [
                    'Mix question types: category questions ("best ... for ..."), comparisons, problems your service solves and questions about your brand by name.',
                    'Check them in ChatGPT, Gemini, Perplexity and Google AI Overviews, ideally from a clean session without your personal history.',
                    'Record for each answer whether your brand is mentioned, whether your site is cited or linked, how you are described and which competitors appear.',
                    'Repeat on the same schedule and keep the wording identical, so the comparison between months is fair.',
                ]],
                ['p', 'From that log you can calculate a simple share of answers: the portion of questions where your brand appears, and the portion where your site is cited as a source. Track both separately, because being mentioned and being linked are different wins.'],
                ['p', 'Manual sampling is slow but transparent. Tools that automate these checks can help at scale; treat their numbers as samples too, since they query the same variable systems you do.'],
                ['h2', 'Measure AI referral traffic in GA4'],
                ['p', 'When an assistant links to your site and the user clicks, the visit often arrives as a referral. In GA4, open the Traffic acquisition report by session source and look for domains such as chatgpt.com, perplexity.ai, gemini.google.com, copilot.microsoft.com and claude.ai.'],
                ['p', 'To see it every month without filtering by hand, create a custom channel group with an "AI assistants" channel that matches those sources with a regular expression, and place it above the default Referral channel. Then compare engagement and conversions for that channel with organic search.'],
                ['p', 'Keep in mind that not every AI visit is labeled: some apps do not pass a referrer, so part of this traffic lands in Direct. AI referral numbers are a floor, not the full picture. If you need help with the setup, our <a href="{service:analytics}">analytics service</a> covers it.'],
                ['h2', 'Use Search Console and brand search signals'],
                ['ul', [
                    'Search Console counts clicks and impressions from AI features such as AI Overviews inside the standard Web performance report. Watch the pages that gain impressions for question-style queries.',
                    'Longer, conversational queries showing up in Search Console suggest your pages match the way people ask AI tools.',
                    'Brand search trends in Search Console and Google Trends show whether more people look for you by name, which can reflect being recommended in AI answers.',
                ]],
                ['h2', 'Ask your leads'],
                ['p', 'Add an option such as "AI assistant (ChatGPT, Gemini, Perplexity)" to the "How did you hear about us?" field in your forms, and ask the same question in sales calls. Self-reported attribution is imperfect, but it captures influence that analytics cannot see, like a buyer who read an answer and then typed your URL.'],
                ['h2', 'Build a simple dashboard to measure AEO'],
                ['ol', [
                    'Share of answers: mentions and citations across your question list.',
                    'AI referral sessions and conversions from the custom channel group.',
                    'Search Console impressions and clicks for question-style queries.',
                    'Brand search trend over time.',
                    'Leads that mention AI assistants as a source.',
                ]],
                ['p', 'Review it monthly and read the trend, not individual answers. AI tools change models and sources often, so a single check can mislead. If you are still setting up the basics, start with our <a href="{post:aeo-checklist}">AEO checklist</a>. If you want a team to run the whole process, see our <a href="{seo-aeo}">AEO and SEO services</a>.'],
            ],
            'faq_title': 'Frequently asked questions on how to measure AEO',
            'ref': ['Google Analytics Help: introducing GA4', 'https://support.google.com/analytics/answer/10089681'],
            'faq': [
                ['Can you measure AEO precisely?', 'Not with the precision of classic rankings. AI answers vary by user, location, wording and model version, and some visits arrive without a referrer. What you can do is sample the same questions on a fixed schedule, combine them with analytics and lead data, and focus on the direction of the trend over several months.'],
                ['Which tools help you measure AEO?', 'GA4 and Search Console cover traffic and search signals at no cost. For the answers themselves, a spreadsheet with your question list and monthly manual checks is a solid start. Several SEO platforms and dedicated AI visibility tools now automate prompt tracking; they save time, but their results are samples too and should be read as trends.'],
                ['How often should I check AI answers?', 'Monthly works for most brands, because it smooths out day-to-day variation without losing track of real changes. Check more often after launching important pages or during a campaign. Keep the same questions, tools and wording each time, and note the date and model when possible, so comparisons between months stay meaningful.'],
            ],
            'takeaways': [
                'Rank tracking alone does not show whether AI assistants use your content.',
                'A fixed list of questions, checked on a schedule, is the core of any effort to measure AEO.',
                'A custom channel group in GA4 makes AI referral traffic visible.',
                'Every way to measure AEO is imperfect: combine sources and read the trend.',
            ],
        },
        'es': {
            'slug': 'como-medir-el-aeo',
            'title': 'Cómo medir el AEO: citas en la IA, menciones de marca y tráfico de IA',
            'seo': ['Cómo medir el AEO: citas, menciones y tráfico de IA',
                    'Cómo medir el AEO: seguimiento de citas y menciones en ChatGPT, Gemini y Perplexity, tráfico de referencia de IA en GA4 y señales de Search Console.',
                    'medir el AEO'],
            'tldr': 'Las posiciones por sí solas no te dicen si los asistentes de IA usan tu contenido. Para medir el AEO, combina una lista fija de preguntas revisadas en ChatGPT, Gemini, Perplexity y los AI Overviews, el tráfico de referencia de IA en GA4, los datos de Search Console, las búsquedas de marca y lo que te cuentan tus leads. Ninguna métrica es perfecta: mira la tendencia.',
            'intro': 'Medir el AEO (Answer Engine Optimization) es comprobar si los asistentes de IA mencionan, citan y enlazan tu marca cuando alguien hace las preguntas que importan para tu negocio. No existe un informe único para esto, así que combinas una lista fija de preguntas revisadas en varias herramientas, el tráfico de IA en GA4, Search Console y tus leads.',
            'body': [
                ['h2', 'Por qué seguir posiciones no alcanza para el AEO'],
                ['p', 'Los informes clásicos de SEO muestran posiciones y clics por palabra clave. Las respuestas de la IA funcionan distinto: la misma pregunta puede dar una respuesta diferente cada vez, la respuesta puede mencionar tu marca sin enlazarte y muchos usuarios nunca hacen clic. Una página puede posicionar bien y aun así faltar en la respuesta que lee el comprador.'],
                ['p', 'Eso no vuelve inútiles a las posiciones. Los asistentes y los AI Overviews se apoyan en contenido web, así que la visibilidad orgánica sigue siendo una buena señal anticipada. Solo hay que complementarla con métricas que miren las respuestas en sí y el negocio que generan.'],
                ['h2', 'Para medir el AEO, sigue una lista fija de preguntas clave'],
                ['p', 'La base de la medición del AEO es una lista con las preguntas que tus compradores hacen de verdad, tomadas de llamadas de venta, tickets de soporte, datos de búsqueda y tus propias preguntas frecuentes. Revisas la misma lista con una frecuencia fija y anotas lo que responden las herramientas de IA.'],
                ['ul', [
                    'Combina tipos de preguntas: de categoría ("mejor ... para ..."), comparaciones, problemas que resuelve tu servicio y preguntas sobre tu marca por su nombre.',
                    'Revísalas en ChatGPT, Gemini, Perplexity y los AI Overviews de Google, idealmente desde una sesión limpia, sin tu historial personal.',
                    'Anota en cada respuesta si mencionan tu marca, si citan o enlazan tu sitio, cómo te describen y qué competidores aparecen.',
                    'Repite con la misma frecuencia y con las mismas palabras, para que la comparación entre meses sea justa.',
                ]],
                ['p', 'Con ese registro puedes calcular una participación en respuestas simple: la proporción de preguntas en las que aparece tu marca y la proporción en las que tu sitio se cita como fuente. Mide ambas por separado, porque ser mencionado y ser enlazado son logros distintos.'],
                ['p', 'El muestreo manual es lento pero transparente. Las herramientas que automatizan estas revisiones ayudan cuando la lista crece; toma sus números también como muestras, porque consultan los mismos sistemas variables que tú.'],
                ['h2', 'Mide el tráfico de referencia de IA en GA4'],
                ['p', 'Cuando un asistente enlaza tu sitio y el usuario hace clic, la visita suele llegar como referencia. En GA4, abre el informe de adquisición de tráfico por fuente de la sesión y busca dominios como chatgpt.com, perplexity.ai, gemini.google.com, copilot.microsoft.com y claude.ai.'],
                ['p', 'Para verlo cada mes sin filtrar a mano, crea un grupo de canales personalizado con un canal "Asistentes de IA" que agrupe esas fuentes con una expresión regular, y ubícalo por encima del canal de referencia predeterminado. Luego compara la interacción y las conversiones de ese canal con las de la búsqueda orgánica.'],
                ['p', 'Ten en cuenta que no todas las visitas desde la IA quedan identificadas: algunas aplicaciones no envían la referencia, así que parte de ese tráfico cae en Directo. Las cifras de referencia de IA son un piso, no el panorama completo. Si necesitas ayuda con la configuración, nuestro <a href="{service:analytics}">servicio de analítica</a> lo cubre.'],
                ['h2', 'Usa Search Console y las búsquedas de marca'],
                ['ul', [
                    'Search Console cuenta los clics e impresiones de funciones de IA como los AI Overviews dentro del informe de rendimiento web. Revisa qué páginas ganan impresiones en consultas con forma de pregunta.',
                    'Las consultas más largas y conversacionales que aparecen en Search Console indican que tus páginas coinciden con la forma en que la gente le pregunta a la IA.',
                    'La tendencia de búsquedas de tu marca en Search Console y Google Trends muestra si más personas te buscan por tu nombre, algo que puede reflejar recomendaciones en respuestas de la IA.',
                ]],
                ['h2', 'Pregúntales a tus leads'],
                ['p', 'Suma una opción como "Asistente de IA (ChatGPT, Gemini, Perplexity)" al campo "¿Cómo nos conociste?" de tus formularios y haz la misma pregunta en las llamadas de venta. La atribución declarada no es perfecta, pero capta una influencia que la analítica no ve, como la de un comprador que leyó una respuesta y luego escribió tu URL.'],
                ['h2', 'Arma un tablero simple para medir el AEO'],
                ['ol', [
                    'Participación en respuestas: menciones y citas en tu lista de preguntas.',
                    'Sesiones y conversiones del canal de asistentes de IA.',
                    'Impresiones y clics de Search Console en consultas con forma de pregunta.',
                    'Tendencia de búsquedas de marca en el tiempo.',
                    'Leads que mencionan a un asistente de IA como origen.',
                ]],
                ['p', 'Revísalo cada mes y lee la tendencia, no las respuestas sueltas. Las herramientas de IA cambian de modelos y fuentes con frecuencia, así que una sola revisión puede confundir. Si todavía estás armando lo básico, empieza por nuestro <a href="{post:aeo-checklist}">checklist de AEO</a>. Si quieres que un equipo lleve todo el proceso, mira nuestros <a href="{seo-aeo}">servicios de AEO y SEO</a>.'],
            ],
            'faq_title': 'Preguntas frecuentes sobre cómo medir el AEO',
            'ref': ['Ayuda de Google Analytics: presentación de GA4', 'https://support.google.com/analytics/answer/10089681'],
            'faq': [
                ['¿Se puede medir el AEO con precisión?', 'No con la precisión de las posiciones clásicas. Las respuestas de la IA cambian según el usuario, la ubicación, la redacción y la versión del modelo, y algunas visitas llegan sin referencia. Lo que sí puedes hacer es revisar las mismas preguntas con una frecuencia fija, cruzarlas con analítica y datos de leads, y mirar la tendencia durante varios meses.'],
                ['¿Qué herramientas sirven para medir el AEO?', 'GA4 y Search Console cubren el tráfico y las señales de búsqueda sin costo. Para las respuestas, una hoja de cálculo con tu lista de preguntas y revisiones manuales mensuales es un buen comienzo. Varias plataformas de SEO y herramientas de visibilidad en IA ya automatizan el seguimiento de prompts; ahorran tiempo, pero sus resultados también son muestras.'],
                ['¿Cada cuánto debo revisar las respuestas de la IA?', 'Una vez al mes funciona para la mayoría de las marcas, porque suaviza la variación diaria sin perder de vista los cambios reales. Revisa con más frecuencia después de lanzar páginas importantes o durante una campaña. Usa siempre las mismas preguntas, herramientas y palabras, y anota la fecha y el modelo cuando puedas.'],
            ],
            'takeaways': [
                'Las posiciones por sí solas no muestran si los asistentes de IA usan tu contenido.',
                'Una lista fija de preguntas, revisada con regularidad, es la base para medir el AEO.',
                'Un grupo de canales personalizado en GA4 hace visible el tráfico que llega desde la IA.',
                'Medir el AEO siempre es imperfecto: combina fuentes y lee la tendencia.',
            ],
        },
    },

    # -----------------------------------------------------------------------
    # Checklist de AEO
    # -----------------------------------------------------------------------
    {
        'key': 'aeo-checklist',
        'publish_gmt': '2026-11-10 14:00:00',
        'cat': 'aeo',
        'image': 'post-aeo-checklist',
        'en': {
            'slug': 'aeo-checklist',
            'title': 'AEO Checklist: Steps to Get Cited by ChatGPT, Perplexity and Gemini',
            'seo': ['AEO Checklist: How to Get Cited by ChatGPT and Gemini',
                    'An AEO checklist to get cited by ChatGPT, Perplexity and Gemini: technical access for AI crawlers, answer-first content, structured data and measurement.',
                    'aeo checklist'],
            'tldr': 'Getting cited by AI assistants starts with basics you can check: AI crawlers can reach your pages, each page answers a question in its first lines, structured data describes who you are, your brand is consistent across the web and you measure the results every month. No AEO checklist guarantees a citation, but skipping these steps makes one unlikely.',
            'intro': 'An AEO checklist is a step-by-step list of what a website needs so AI assistants such as ChatGPT, Perplexity and Gemini can find, understand and cite it. It covers technical access for AI crawlers, content written as direct answers, structured data, brand signals across the web and a simple way to measure results.',
            'body': [
                ['h2', '1. Technical access: let AI tools reach your content'],
                ['ol', [
                    'Make sure your key pages are indexable: no accidental noindex tags, correct canonical URLs and an XML sitemap submitted to Google Search Console and Bing Webmaster Tools.',
                    'Review robots.txt. Allow the search crawlers of the assistants where you want to appear, such as OAI-SearchBot (ChatGPT search), PerplexityBot, Googlebot and Bingbot, since the Bing index powers Microsoft Copilot.',
                    'Decide on training crawlers separately. GPTBot collects data for OpenAI models, and Google-Extended controls whether your content is used for Gemini models. Blocking Google-Extended does not remove you from Google Search or AI Overviews, which rely on Googlebot.',
                    'Put important information in HTML text. Content that only appears after heavy JavaScript, or lives inside images and PDFs, is harder for some AI crawlers to read.',
                    'Keep pages fast and free of barriers such as forced logins or bot protection that blocks legitimate crawlers.',
                    'Optionally, publish an llms.txt file that points to your most useful pages. It is a proposed convention, not a standard, and support varies, so treat it as a low-cost extra.',
                ]],
                ['h2', '2. Content: write answers, not just pages'],
                ['ol', [
                    'Answer the main question of each page in the first two or three sentences, then add the detail.',
                    'Use the real questions your customers ask as H2 and H3 headings.',
                    'Add a short FAQ with the follow-up questions buyers ask before deciding.',
                    'Show a visible "last updated" date and keep facts current.',
                    'Show who wrote the content and why they are qualified, with a short author bio.',
                    'Use lists, steps and tables where they help, and state specific facts: services, locations, integrations, timelines and how pricing works.',
                    'Cover one main topic per page and link related pages to each other.',
                ]],
                ['p', 'If you would rather have a team write and restructure this content, our <a href="{service:aeo-content}">AEO content service</a> does exactly that.'],
                ['h2', '3. Structured data: describe your business for machines'],
                ['ol', [
                    'Add Organization and WebSite schema with your name, logo, URL and official profiles.',
                    'Mark up services, articles, FAQs and breadcrumbs with the matching schema types.',
                    'Keep every fact in the markup consistent with the visible content.',
                    'Validate with Google Rich Results Test and the Schema Markup Validator.',
                ]],
                ['p', 'For the structured data step of this AEO checklist, we explain which types matter and why in our guide to <a href="{post:aeo-schema}">schema for AEO</a>.'],
                ['h2', '4. Brand signals beyond your site'],
                ['ol', [
                    'Keep your company name, description, address and phone consistent across Google Business Profile, directories and social profiles.',
                    'Collect genuine reviews on the platforms that matter in your industry.',
                    'Earn mentions in industry media, partner sites, roundups and communities where your buyers spend time.',
                    'Describe what you do with the same words everywhere, so assistants get a single, clear picture of your brand.',
                ]],
                ['h2', '5. Measurement: know whether it is working'],
                ['ol', [
                    'Write a fixed list of the questions your buyers ask and check them every month in ChatGPT, Perplexity, Gemini and AI Overviews.',
                    'Track AI referral traffic in GA4 with a custom channel group.',
                    'Add an "AI assistant" option to your "How did you hear about us?" field.',
                ]],
                ['p', 'The details are in our guide on <a href="{post:aeo-measure}">how to measure AEO</a>.'],
                ['h2', 'What an AEO checklist cannot do'],
                ['p', 'No checklist guarantees a citation. AI tools decide what to show, and their answers change with models, sources and wording. What an AEO checklist does is remove the obstacles that keep good content out of those answers. If you want a team to work through it with you, see our <a href="{seo-aeo}">AEO and SEO services</a>.'],
            ],
            'faq_title': 'Frequently asked questions about the AEO checklist',
            'ref': ['OpenAI: overview of OpenAI crawlers', 'https://platform.openai.com/docs/bots'],
            'faq': [
                ['How do I get cited by ChatGPT?', 'Allow OAI-SearchBot in your robots.txt, make sure your pages are indexed and readable as HTML text, and answer specific questions directly in the first lines. Add structured data and keep your brand information consistent across the web. No one can guarantee a citation, but these steps make your content eligible and easy to quote.'],
                ['Do I need an llms.txt file for AEO?', 'It is optional. llms.txt is a proposed convention for pointing AI tools to your most useful content, and support across assistants is limited and uneven. It is quick to create, so it can be a reasonable extra, but it does not replace crawlable pages, clear answers, structured data and a well organized site.'],
                ['Should I block GPTBot or Google-Extended?', 'That is a business decision about how your content is used to build AI models, not about visibility in answers. Search crawlers such as OAI-SearchBot and Googlebot control whether you can appear in ChatGPT search and Google results. Many brands allow search crawlers and review training crawlers with their legal team.'],
            ],
            'takeaways': [
                'Technical access comes first in any AEO checklist: AI crawlers must be able to reach and read your pages.',
                'Answer each question in the first lines, with clear headings and a short FAQ.',
                'Structured data and consistent brand signals remove doubt about who you are.',
                'Measure every month, because no AEO checklist guarantees a citation.',
            ],
        },
        'es': {
            'slug': 'checklist-de-aeo',
            'title': 'Checklist de AEO: pasos para que ChatGPT, Perplexity y Gemini te citen',
            'seo': ['Checklist de AEO: cómo lograr que ChatGPT y Gemini te citen',
                    'Checklist de AEO para que ChatGPT, Perplexity y Gemini te citen: acceso para rastreadores de IA, contenido con respuestas directas, schema y medición.',
                    'checklist de AEO'],
            'tldr': 'Que los asistentes de IA te citen empieza con aspectos básicos que puedes revisar: que los rastreadores de IA lleguen a tus páginas, que cada página responda una pregunta en sus primeras líneas, que los datos estructurados describan quién eres, que tu marca sea coherente en la web y que midas los resultados cada mes. Ningún checklist de AEO garantiza una cita, pero saltarte estos pasos la vuelve poco probable.',
            'intro': 'Un checklist de AEO es una lista paso a paso de lo que necesita un sitio web para que asistentes de IA como ChatGPT, Perplexity y Gemini puedan encontrarlo, entenderlo y citarlo. Cubre el acceso técnico para los rastreadores de IA, contenido escrito como respuestas directas, datos estructurados, señales de marca en la web y una forma simple de medir.',
            'body': [
                ['h2', '1. Acceso técnico: deja que la IA llegue a tu contenido'],
                ['ol', [
                    'Asegúrate de que tus páginas clave sean indexables: sin etiquetas noindex por error, con URL canónicas correctas y un sitemap XML enviado a Google Search Console y Bing Webmaster Tools.',
                    'Revisa el robots.txt. Permite los rastreadores de búsqueda de los asistentes en los que quieres aparecer, como OAI-SearchBot (búsqueda de ChatGPT), PerplexityBot, Googlebot y Bingbot, ya que el índice de Bing alimenta a Microsoft Copilot.',
                    'Decide por separado sobre los rastreadores de entrenamiento. GPTBot recopila datos para los modelos de OpenAI y Google-Extended controla si tu contenido se usa para los modelos de Gemini. Bloquear Google-Extended no te saca de la Búsqueda de Google ni de los AI Overviews, que dependen de Googlebot.',
                    'Pon la información importante en texto HTML. El contenido que solo aparece después de mucho JavaScript, o que vive dentro de imágenes y PDF, es más difícil de leer para algunos rastreadores de IA.',
                    'Mantén las páginas rápidas y sin barreras, como inicios de sesión obligatorios o protecciones contra bots que bloquean a los rastreadores legítimos.',
                    'Si quieres, publica un archivo llms.txt que apunte a tus páginas más útiles. Es una convención propuesta, no un estándar, y el soporte varía, así que tómalo como un extra de bajo costo.',
                ]],
                ['h2', '2. Contenido: escribe respuestas, no solo páginas'],
                ['ol', [
                    'Responde la pregunta principal de cada página en las primeras dos o tres oraciones y luego suma el detalle.',
                    'Usa las preguntas reales de tus clientes como títulos H2 y H3.',
                    'Agrega una sección breve de preguntas frecuentes con lo que los compradores preguntan antes de decidir.',
                    'Muestra una fecha visible de "última actualización" y mantén los datos al día.',
                    'Muestra quién escribió el contenido y por qué está calificado, con una breve biografía del autor.',
                    'Usa listas, pasos y tablas cuando ayuden, y da datos concretos: servicios, ubicaciones, integraciones, plazos y cómo funcionan los precios.',
                    'Trata un tema principal por página y enlaza las páginas relacionadas entre sí.',
                ]],
                ['p', 'Si prefieres que un equipo escriba y reestructure este contenido, nuestro <a href="{service:aeo-content}">servicio de contenido para AEO</a> hace justamente eso.'],
                ['h2', '3. Datos estructurados: describe tu negocio para las máquinas'],
                ['ol', [
                    'Agrega schema Organization y WebSite con tu nombre, logo, URL y perfiles oficiales.',
                    'Marca servicios, artículos, preguntas frecuentes y migas de pan con los tipos de schema que corresponden.',
                    'Mantén cada dato del marcado coherente con el contenido visible.',
                    'Valida con la prueba de resultados enriquecidos de Google y con el Schema Markup Validator.',
                ]],
                ['p', 'Para el paso de datos estructurados de este checklist de AEO, explicamos qué tipos importan y por qué en nuestra guía de <a href="{post:aeo-schema}">schema para AEO</a>.'],
                ['h2', '4. Señales de marca fuera de tu sitio'],
                ['ol', [
                    'Mantén el mismo nombre, descripción, dirección y teléfono de tu empresa en tu Perfil de Empresa de Google, directorios y redes sociales.',
                    'Junta reseñas reales en las plataformas que importan en tu industria.',
                    'Consigue menciones en medios del sector, sitios de socios, rankings y comunidades donde están tus compradores.',
                    'Describe lo que haces con las mismas palabras en todos lados, para que los asistentes tengan una imagen única y clara de tu marca.',
                ]],
                ['h2', '5. Medición: comprueba si está funcionando'],
                ['ol', [
                    'Escribe una lista fija de las preguntas que hacen tus compradores y revísalas cada mes en ChatGPT, Perplexity, Gemini y los AI Overviews.',
                    'Mide el tráfico de referencia de IA en GA4 con un grupo de canales personalizado.',
                    'Suma la opción "Asistente de IA" al campo "¿Cómo nos conociste?".',
                ]],
                ['p', 'Los detalles están en nuestra guía sobre <a href="{post:aeo-measure}">cómo medir el AEO</a>.'],
                ['h2', 'Lo que un checklist de AEO no puede hacer'],
                ['p', 'Ningún checklist garantiza una cita. Las herramientas de IA deciden qué mostrar, y sus respuestas cambian según el modelo, las fuentes y la forma de preguntar. Lo que sí hace un checklist de AEO es quitar los obstáculos que dejan al buen contenido fuera de esas respuestas. Si quieres que un equipo lo trabaje contigo, mira nuestros <a href="{seo-aeo}">servicios de AEO y SEO</a>.'],
            ],
            'faq_title': 'Preguntas frecuentes sobre el checklist de AEO',
            'ref': ['OpenAI: rastreadores de OpenAI', 'https://platform.openai.com/docs/bots'],
            'faq': [
                ['¿Cómo logro que ChatGPT me cite?', 'Permite OAI-SearchBot en tu robots.txt, asegúrate de que tus páginas estén indexadas y se puedan leer como texto HTML, y responde preguntas concretas en las primeras líneas. Suma datos estructurados y mantén la información de tu marca coherente en la web. Nadie puede garantizar una cita, pero estos pasos hacen que tu contenido califique y sea fácil de citar.'],
                ['¿Necesito un archivo llms.txt para el AEO?', 'Es opcional. El llms.txt es una convención propuesta para señalar a las herramientas de IA tu contenido más útil, y el soporte entre asistentes es limitado y desigual. Se crea rápido, así que puede ser un extra razonable, pero no reemplaza páginas rastreables, respuestas claras, datos estructurados y un sitio bien organizado.'],
                ['¿Debería bloquear GPTBot o Google-Extended?', 'Es una decisión de negocio sobre cómo se usa tu contenido para entrenar modelos de IA, no sobre tu visibilidad en las respuestas. Los rastreadores de búsqueda como OAI-SearchBot y Googlebot definen si puedes aparecer en la búsqueda de ChatGPT y en Google. Muchas marcas permiten los de búsqueda y revisan los de entrenamiento con su área legal.'],
            ],
            'takeaways': [
                'En todo checklist de AEO, el acceso técnico va primero: los rastreadores de IA deben poder llegar a tus páginas y leerlas.',
                'Responde cada pregunta en las primeras líneas, con títulos claros y preguntas frecuentes.',
                'Los datos estructurados y las señales de marca coherentes eliminan dudas sobre quién eres.',
                'Mide cada mes, porque ningún checklist de AEO garantiza una cita.',
            ],
        },
    },

    # -----------------------------------------------------------------------
    # Schema para AEO
    # -----------------------------------------------------------------------
    {
        'key': 'aeo-schema',
        'publish_gmt': '2026-11-24 14:00:00',
        'cat': 'aeo',
        'image': 'post-aeo-schema',
        'en': {
            'slug': 'schema-for-aeo',
            'title': 'Schema for AEO: The Structured Data AI Engines Read',
            'seo': ['Schema for AEO: The Structured Data AI Engines Read',
                    'Schema for AEO: which structured data types AI engines read, how to implement them in JSON-LD, keep them consistent with your content and validate them.',
                    'schema for aeo'],
            'tldr': 'Schema markup tells search engines and AI tools, in a format they read without guessing, who you are, what you offer and who wrote your content. In schema for AEO, the key types are Organization, WebSite, Service, LocalBusiness, BlogPosting, Person, FAQPage, BreadcrumbList and, for stores, Product. Schema adds clarity, not guarantees.',
            'intro': 'Schema for AEO is the structured data, usually written in JSON-LD, that describes your organization, services, articles, authors and FAQs in a format machines can read without guessing. It helps search engines and AI assistants understand what each page is about and who is behind it, which supports being cited, although it never guarantees it.',
            'body': [
                ['h2', 'What schema does for AEO, and what it does not'],
                ['p', 'Schema.org is a shared vocabulary that the major search engines created to describe entities: a company, a service, an article, a person, a product. When you add it to a page, you state those facts explicitly instead of leaving them to be inferred from the text.'],
                ['p', 'That clarity helps search engines build a reliable picture of your brand, and AI features that draw on search indexes benefit from it. What schema does not do is force an assistant to cite you. It is one signal among many, and it only works when the page itself is useful and the markup matches what users see.'],
                ['h2', 'Why JSON-LD is the format to use'],
                ['p', 'Google supports JSON-LD, Microdata and RDFa, and recommends JSON-LD because it lives in a single script block, separate from the visible HTML, which makes it easier to write and maintain. Most SEO plugins, including Rank Math and Yoast on WordPress, output JSON-LD by default.'],
                ['h2', 'Schema for AEO: the types that matter'],
                ['h3', 'Organization and WebSite'],
                ['p', 'Organization describes your company: name, logo, URL, contact details and sameAs links to your official profiles. WebSite describes the site itself. Together they connect your site with the same entity mentioned in directories, social networks and articles.'],
                ['h3', 'Service and LocalBusiness'],
                ['p', 'Service describes what you offer, who provides it and the area served. If you have an office or serve a specific area, LocalBusiness (or a more specific subtype) adds address, opening hours and location data, which should match your Google Business Profile.'],
                ['h3', 'BlogPosting, Article and Person'],
                ['p', 'BlogPosting or Article marks up the headline, publication and update dates and the author. Link the author to a Person entity with name, job title and profiles, and show the same information in a visible author bio. This supports the experience and trust signals that matter when engines pick sources.'],
                ['h3', 'FAQPage'],
                ['p', 'FAQPage marks up questions and answers that are visible on the page. Since 2023 Google shows FAQ rich results only for a limited set of well-known government and health sites, so most sites will not see the expanded snippet. The markup still describes question and answer pairs clearly, which is why many teams keep it.'],
                ['h3', 'BreadcrumbList'],
                ['p', 'BreadcrumbList shows where a page sits in your site structure, which helps engines understand how services, categories and articles relate to each other.'],
                ['h3', 'Product and Review for e-commerce'],
                ['p', 'Product markup with offers (price, currency and availability) and genuine ratings helps engines read product data accurately. Only mark up reviews that are visible on the page and come from real customers. Google does not show review stars for reviews a business publishes about itself.'],
                ['h2', 'Keep schema for AEO consistent with visible content'],
                ['ul', [
                    'Every fact in your markup should appear on the page: the same prices, the same questions, the same author.',
                    'Use the same company name, logo and URLs in every schema block and on your external profiles.',
                    'Avoid duplicate or conflicting markup, a common issue when a theme and an SEO plugin both output schema.',
                    'Update the markup when content changes, especially dates, prices and availability.',
                ]],
                ['h2', 'How to validate your structured data'],
                ['ol', [
                    'Test your key templates with the Google Rich Results Test to check eligibility for rich results.',
                    'Use the Schema Markup Validator (validator.schema.org) to check the syntax of every type, including the ones Google does not display.',
                    'Review the enhancement reports in Search Console to catch errors across the whole site.',
                    'Test again after theme, plugin or template changes.',
                ]],
                ['p', 'Schema for AEO is one layer of a broader plan that also covers content, technical access and brand signals; see the full <a href="{post:aeo-checklist}">AEO checklist</a>. If you want a team to audit and implement it, see our <a href="{seo-aeo}">AEO and SEO services</a> or our <a href="{service:website}">website development service</a>.'],
            ],
            'faq_title': 'Frequently asked questions about schema for AEO',
            'ref': ['Google Search Central: introduction to structured data', 'https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data'],
            'faq': [
                ['Does schema for AEO help you get cited by AI?', 'It can help, but it does not guarantee citations. Schema makes facts about your brand, content and authors explicit, which helps search engines and the AI features built on them understand your pages. Whether an assistant cites you still depends on the quality of the content, its relevance and your authority on the topic.'],
                ['Is FAQ schema still worth using?', 'In most cases, yes. Since 2023 Google limits FAQ rich results to a small group of authoritative sites, so the expanded snippet rarely appears. The markup still describes your questions and answers in a clear, machine readable way. Use it only for FAQs that are visible on the page and written for real users.'],
                ['Which schema types should a service business start with?', 'Start with Organization and WebSite on the home page, Service on each service page and LocalBusiness if you serve a specific area or have an office. Add BreadcrumbList across the site and BlogPosting with a Person author on articles. FAQPage fits pages with a visible FAQ. Validate everything before and after publishing.'],
            ],
            'takeaways': [
                'Schema states facts explicitly, which helps machines understand your pages.',
                'JSON-LD is the recommended format and the easiest to maintain.',
                'Markup must match the visible content, or it loses its value.',
                'Schema for AEO adds clarity, but it does not guarantee citations.',
            ],
        },
        'es': {
            'slug': 'schema-para-aeo',
            'title': 'Schema para AEO: los datos estructurados que leen los motores de IA',
            'seo': ['Schema para AEO: los datos estructurados que lee la IA',
                    'Schema para AEO: qué datos estructurados leen los motores de IA, cómo implementarlos en JSON-LD, mantenerlos coherentes con tu contenido y validarlos.',
                    'schema para AEO'],
            'tldr': 'El marcado schema le dice a los buscadores y a las herramientas de IA, en un formato que leen sin adivinar, quién eres, qué ofreces y quién escribió tu contenido. En el schema para AEO, los tipos clave son Organization, WebSite, Service, LocalBusiness, BlogPosting, Person, FAQPage, BreadcrumbList y, en tiendas, Product. El schema suma claridad, no garantías.',
            'intro': 'El schema para AEO son los datos estructurados, casi siempre en JSON-LD, que describen tu organización, servicios, artículos, autores y preguntas frecuentes en un formato que las máquinas leen sin adivinar. Ayuda a que los buscadores y los asistentes de IA entiendan de qué trata cada página y quién está detrás, lo que favorece las citas sin garantizarlas.',
            'body': [
                ['h2', 'Qué hace el schema por el AEO, y qué no hace'],
                ['p', 'Schema.org es un vocabulario común que crearon los principales buscadores para describir entidades: una empresa, un servicio, un artículo, una persona, un producto. Cuando lo agregas a una página, declaras esos datos de forma explícita en lugar de dejar que se deduzcan del texto.'],
                ['p', 'Esa claridad ayuda a los buscadores a formar una imagen confiable de tu marca, y las funciones de IA que se apoyan en esos índices se benefician. Lo que el schema no hace es obligar a un asistente a citarte. Es una señal entre muchas y solo funciona cuando la página es útil y el marcado coincide con lo que ve el usuario.'],
                ['h2', 'Por qué usar JSON-LD'],
                ['p', 'Google admite JSON-LD, Microdata y RDFa, y recomienda JSON-LD porque va en un solo bloque de script, separado del HTML visible, lo que lo hace más fácil de escribir y mantener. La mayoría de los plugins de SEO, como Rank Math y Yoast en WordPress, generan JSON-LD por defecto.'],
                ['h2', 'Schema para AEO: los tipos que importan'],
                ['h3', 'Organization y WebSite'],
                ['p', 'Organization describe tu empresa: nombre, logo, URL, datos de contacto y enlaces sameAs a tus perfiles oficiales. WebSite describe el sitio en sí. Juntos conectan tu sitio con la misma entidad que aparece en directorios, redes sociales y artículos.'],
                ['h3', 'Service y LocalBusiness'],
                ['p', 'Service describe lo que ofreces, quién lo presta y la zona que atiendes. Si tienes una oficina o atiendes un área concreta, LocalBusiness (o un subtipo más específico) suma dirección, horarios y ubicación, que deben coincidir con tu Perfil de Empresa de Google.'],
                ['h3', 'BlogPosting, Article y Person'],
                ['p', 'BlogPosting o Article marcan el título, las fechas de publicación y actualización y el autor. Vincula al autor con una entidad Person con nombre, cargo y perfiles, y muestra la misma información en una biografía visible. Esto refuerza las señales de experiencia y confianza que pesan cuando los motores eligen fuentes.'],
                ['h3', 'FAQPage'],
                ['p', 'FAQPage marca las preguntas y respuestas visibles en la página. Desde 2023, Google muestra los resultados enriquecidos de preguntas frecuentes solo para un grupo limitado de sitios gubernamentales y de salud reconocidos, así que la mayoría de los sitios no verá el fragmento ampliado. Aun así, el marcado describe con claridad cada par de pregunta y respuesta, y por eso muchos equipos lo mantienen.'],
                ['h3', 'BreadcrumbList'],
                ['p', 'BreadcrumbList indica en qué lugar de la estructura del sitio está cada página, lo que ayuda a los motores a entender cómo se relacionan servicios, categorías y artículos.'],
                ['h3', 'Product y Review para e-commerce'],
                ['p', 'El marcado Product con ofertas (precio, moneda y disponibilidad) y calificaciones reales ayuda a los motores a leer bien los datos del producto. Marca solo reseñas visibles en la página y escritas por clientes reales. Google no muestra estrellas para las reseñas que una empresa publica sobre sí misma.'],
                ['h2', 'Mantén el schema para AEO coherente con el contenido visible'],
                ['ul', [
                    'Cada dato del marcado debe aparecer en la página: los mismos precios, las mismas preguntas, el mismo autor.',
                    'Usa el mismo nombre de empresa, logo y URL en todos los bloques de schema y en tus perfiles externos.',
                    'Evita marcado duplicado o contradictorio, un problema común cuando el theme y un plugin de SEO generan schema a la vez.',
                    'Actualiza el marcado cuando cambie el contenido, sobre todo fechas, precios y disponibilidad.',
                ]],
                ['h2', 'Cómo validar tus datos estructurados'],
                ['ol', [
                    'Prueba tus plantillas clave con la prueba de resultados enriquecidos de Google para revisar si califican.',
                    'Usa el Schema Markup Validator (validator.schema.org) para revisar la sintaxis de todos los tipos, incluidos los que Google no muestra.',
                    'Revisa los informes de mejoras en Search Console para detectar errores en todo el sitio.',
                    'Vuelve a probar después de cambiar el theme, un plugin o una plantilla.',
                ]],
                ['p', 'El schema para AEO es una capa de un plan más amplio que también cubre contenido, acceso técnico y señales de marca; revisa el <a href="{post:aeo-checklist}">checklist de AEO</a> completo. Si quieres que un equipo lo audite e implemente, mira nuestros <a href="{seo-aeo}">servicios de AEO y SEO</a> o nuestro <a href="{service:website}">servicio de desarrollo web</a>.'],
            ],
            'faq_title': 'Preguntas frecuentes sobre schema para AEO',
            'ref': ['Google Search Central: introducción a los datos estructurados', 'https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data'],
            'faq': [
                ['¿El schema para AEO ayuda a que la IA te cite?', 'Puede ayudar, pero no garantiza citas. El schema hace explícitos los datos de tu marca, tu contenido y tus autores, lo que ayuda a los buscadores y a las funciones de IA construidas sobre ellos a entender tus páginas. Que un asistente te cite sigue dependiendo de la calidad del contenido, su relevancia y tu autoridad en el tema.'],
                ['¿Todavía vale la pena usar el schema de preguntas frecuentes?', 'En la mayoría de los casos, sí. Desde 2023 Google limita los resultados enriquecidos de preguntas frecuentes a un grupo pequeño de sitios con autoridad, así que el fragmento ampliado casi no aparece. El marcado sigue describiendo tus preguntas y respuestas de forma clara para las máquinas. Úsalo solo con preguntas visibles y escritas para usuarios reales.'],
                ['¿Con qué tipos de schema debería empezar una empresa de servicios?', 'Empieza con Organization y WebSite en la página de inicio, Service en cada página de servicio y LocalBusiness si atiendes un área concreta o tienes oficina. Suma BreadcrumbList en todo el sitio y BlogPosting con un autor Person en los artículos. FAQPage va en páginas con preguntas frecuentes visibles. Valida todo antes y después de publicar.'],
            ],
            'takeaways': [
                'El schema declara datos de forma explícita, lo que ayuda a las máquinas a entender tus páginas.',
                'JSON-LD es el formato recomendado y el más fácil de mantener.',
                'El marcado debe coincidir con el contenido visible o pierde su valor.',
                'El schema para AEO suma claridad, pero no garantiza citas.',
            ],
        },
    },
]
