POSTS = [
    # -----------------------------------------------------------------------
    # AEO para e-commerce y Shopify
    # -----------------------------------------------------------------------
    {
        'key': 'aeo-ecommerce',
        'publish_gmt': '2026-12-01 13:00:00',
        'cat': 'aeo',
        'image': 'post-aeo-ecommerce',
        'en': {
            'slug': 'aeo-for-ecommerce',
            'title': 'AEO for Ecommerce: How to Get Your Products Recommended by AI',
            'seo': ['AEO for Ecommerce: Get Your Products Recommended by AI',
                    'AEO for ecommerce and Shopify stores: how to get products recommended by AI assistants with clean product data, structured data, buying guides and reviews.',
                    'aeo for ecommerce'],
            'tldr': 'Shoppers now ask AI assistants what to buy. AEO for ecommerce makes your products easy to recommend: consistent product data, Product and Offer structured data, a healthy merchant feed, buying guides, category FAQs and genuine reviews. On Shopify, most of this is done with the theme, collections and content you already have.',
            'intro': 'AEO for ecommerce (Answer Engine Optimization) is the practice of making an online store easy for AI assistants to understand, compare and recommend. It combines accurate product data, structured data, merchant feeds, buying guides, category FAQs and reviews, so that when shoppers ask ChatGPT, Gemini or Google which product to buy, your store appears.',
            'body': [
                ['h2', 'How shoppers use AI assistants to buy'],
                ['p', 'Product research used to start with a search and ten tabs. Today many shoppers ask an assistant directly: "best running shoes for flat feet under $150", "compare these two espresso machines" or "which sunscreen is safe for kids". The assistant answers with a short list, reasons for each option and, often, links to stores.'],
                ['p', 'To make that list, assistants need facts they can trust: what the product is, who it is for, what it costs, whether it is in stock and what buyers think of it. Stores that publish those facts clearly and consistently are easier to recommend than stores that hide them in images or scripts.'],
                ['h2', 'Start with product data quality'],
                ['p', 'Product data is the base of AEO for ecommerce. Review each product page with these questions in mind:'],
                ['ul', [
                    '<strong>Titles</strong>: descriptive and specific (brand, product type, key attribute), not only a creative name.',
                    '<strong>Attributes and specs</strong>: size, material, dimensions, compatibility and use case written as text, ideally in a simple table.',
                    '<strong>Prices and availability</strong>: the same on the page, in your structured data and in your merchant feed.',
                    '<strong>Descriptions</strong>: who the product is for and what problem it solves, not only adjectives.',
                    '<strong>Policies</strong>: shipping, returns and warranty visible and easy to find.',
                ]],
                ['p', 'Inconsistent data is a common problem. If the page says one price, the feed says another and a marketplace listing says a third, assistants have a reason to doubt all of them.'],
                ['h2', 'Product, Offer and Review structured data'],
                ['p', 'Structured data tells machines exactly what each page contains. For a store, the essentials are Product (name, brand, image, description, identifiers such as GTIN or SKU), Offer (price, currency, availability, condition) and AggregateRating or Review when you have genuine reviews on the page. Add BreadcrumbList for navigation and Organization for your brand. Validate the markup with the Rich Results Test and keep it in sync with what users see. We cover the details in <a href="{post:aeo-schema}">our guide to schema for AEO</a>.'],
                ['h2', 'Buying guides and category FAQs'],
                ['p', 'Product pages answer "what is this". Buying guides and category FAQs answer the questions that come before: which type do I need, how do these options compare, what size fits me. These are exactly the questions shoppers ask assistants. Write guides that answer the question in the first lines, compare options honestly and link to the relevant products and collections. Add a short FAQ to each key category page with real questions from customer service, chats and reviews.'],
                ['h2', 'Reviews and third-party mentions'],
                ['p', 'Assistants look beyond your store. Reviews on your site and on review platforms, mentions in comparison articles, gift guides, forums and creator content all shape which brands get suggested. Ask customers for reviews after delivery, answer questions publicly and pursue coverage in the publications your buyers read. Keep the facts about your products the same everywhere you appear.'],
                ['h2', 'Shopping features in AI assistants and Google'],
                ['p', 'Google Shopping results, AI Overviews and several AI assistants show product listings with prices and availability. On Google, much of that data comes from Google Merchant Center, so a complete and accurate merchant feed matters for organic listings too, not only for ads. Fix feed errors, use precise product categories and attributes, and make sure your feed prices match your site. Other assistants are adding their own shopping experiences, and the same principle applies: clean, consistent product data.'],
                ['h2', 'Shopify specifics'],
                ['ul', [
                    '<strong>Theme structured data</strong>: many Shopify themes include Product markup, but check what yours outputs and fill the gaps (brand, GTIN, reviews) instead of stacking duplicate markup.',
                    '<strong>Collections as category pages</strong>: add a short intro that answers what the collection is and who it is for, plus a brief FAQ below the products.',
                    '<strong>Blog and guides</strong>: use the Shopify blog for buying guides and comparisons, linked from collections and products.',
                    '<strong>Apps, carefully</strong>: review and SEO apps can help, but each one adds scripts and sometimes conflicting markup. Audit what they inject and remove what you do not use.',
                    '<strong>Google and YouTube channel</strong>: connects your catalog to Merchant Center, so keep product data clean at the source.',
                ]],
                ['h2', 'How to measure AI referral traffic'],
                ['p', 'In GA4, create a channel group or exploration for sessions from AI tools (for example chatgpt.com, perplexity.ai, gemini.google.com and copilot.microsoft.com) and track their conversions separately. Check Merchant Center for free listing performance. Every month, run a fixed list of shopping prompts in the main assistants and note whether your products appear and how they are described.'],
                ['p', 'If your store needs a technical base that supports all of this, see our <a href="{service:website}">websites and e-commerce services</a>. For the content and visibility side, our <a href="{seo-aeo}">AEO and SEO services</a> can help your products become the answer.'],
            ],
            'faq_title': 'Frequently asked questions',
            'faq': [
                ['Does AEO for ecommerce replace product SEO?', 'No. AEO for ecommerce builds on product SEO. Assistants still rely on pages they can crawl and understand, so indexable product and collection pages, fast load times and clean internal links remain the base. AEO adds consistent product data, structured data, buying guides and review signals that make your products easier to recommend.'],
                ['Is Shopify good for AEO?', 'Yes, Shopify gives you a solid starting point: clean URLs, product markup in many themes, a built-in blog and an easy connection to Google Merchant Center. The work is in the details: complete product data, collection intros and FAQs, useful buying guides and a careful choice of apps so they do not add conflicting markup.'],
                ['Do I need a Google Merchant Center account if I do not run ads?', 'It is worth having one. Merchant Center feeds power free product listings on Google, not only Shopping ads, and they give Google structured product facts such as price and availability. A clean, accurate feed makes it easier for Google surfaces to show your products when shoppers compare options.'],
            ],
            'takeaways': [
                'Shoppers ask AI assistants what to buy, so your product facts need to be easy to read.',
                'Keep titles, specs, prices and availability consistent on your site, feed and marketplaces.',
                'Product and Offer structured data, buying guides and category FAQs give assistants material to cite.',
                'On Shopify, use collections, the blog and Merchant Center, and audit apps carefully.',
            ],
        },
        'es': {
            'slug': 'aeo-para-ecommerce',
            'title': 'AEO para ecommerce: cómo lograr que la IA recomiende tus productos',
            'seo': ['AEO para ecommerce: que la IA recomiende tus productos',
                    'AEO para ecommerce y tiendas Shopify: cómo lograr que los asistentes de IA recomienden tus productos con datos claros, datos estructurados, guías y reseñas.',
                    'AEO para ecommerce'],
            'tldr': 'Los compradores ya preguntan a los asistentes de IA qué comprar. El AEO para ecommerce hace que tus productos sean fáciles de recomendar: datos de producto coherentes, datos estructurados Product y Offer, un feed de comercio sano, guías de compra, preguntas frecuentes por categoría y reseñas reales. En Shopify, casi todo se trabaja con el tema, las colecciones y el contenido que ya tienes.',
            'intro': 'El AEO para ecommerce (Answer Engine Optimization) es la práctica de lograr que los asistentes de IA entiendan, comparen y recomienden los productos de una tienda en línea. Combina datos de producto precisos, datos estructurados, feeds de comercio, guías de compra, preguntas frecuentes y reseñas, para que tu tienda aparezca cuando alguien pregunta a ChatGPT, Gemini o Google qué comprar.',
            'body': [
                ['h2', 'Cómo usan los compradores los asistentes de IA'],
                ['p', 'Antes, investigar un producto empezaba con una búsqueda y diez pestañas abiertas. Hoy muchos compradores le preguntan directo a un asistente: "mejores tenis para correr con pie plano por menos de 150 dólares", "compara estas dos cafeteras" o "qué protector solar es seguro para niños". El asistente responde con una lista corta, razones para cada opción y, muchas veces, enlaces a tiendas.'],
                ['p', 'Para armar esa lista, los asistentes necesitan datos confiables: qué es el producto, para quién es, cuánto cuesta, si hay stock y qué opinan los compradores. Las tiendas que publican esos datos de forma clara y coherente son más fáciles de recomendar que las que los esconden en imágenes o scripts.'],
                ['h2', 'Empieza por la calidad de los datos de producto'],
                ['p', 'Los datos de producto son la base del AEO para ecommerce. Revisa cada página de producto con estas preguntas en mente:'],
                ['ul', [
                    '<strong>Títulos</strong>: claros y específicos (marca, tipo de producto, atributo clave), no solo un nombre creativo.',
                    '<strong>Atributos y especificaciones</strong>: talla, material, medidas, compatibilidad y uso escritos en texto, idealmente en una tabla simple.',
                    '<strong>Precios y disponibilidad</strong>: los mismos en la página, en los datos estructurados y en el feed de comercio.',
                    '<strong>Descripciones</strong>: para quién es el producto y qué problema resuelve, no solo adjetivos.',
                    '<strong>Políticas</strong>: envíos, devoluciones y garantía visibles y fáciles de encontrar.',
                ]],
                ['p', 'Los datos inconsistentes son un problema común. Si la página dice un precio, el feed otro y un marketplace un tercero, los asistentes tienen razones para dudar de todos.'],
                ['h2', 'Datos estructurados Product, Offer y Review'],
                ['p', 'Los datos estructurados le dicen a las máquinas qué contiene cada página. En una tienda, lo esencial es Product (nombre, marca, imagen, descripción e identificadores como GTIN o SKU), Offer (precio, moneda, disponibilidad y condición) y AggregateRating o Review cuando tienes reseñas reales en la página. Suma BreadcrumbList para la navegación y Organization para tu marca. Valida el marcado con la prueba de resultados enriquecidos y mantenlo igual a lo que ven los usuarios. Lo explicamos en <a href="{post:aeo-schema}">nuestra guía de schema para AEO</a>.'],
                ['h2', 'Guías de compra y preguntas frecuentes por categoría'],
                ['p', 'Las páginas de producto responden "qué es esto". Las guías de compra y las preguntas frecuentes por categoría responden lo que viene antes: qué tipo necesito, en qué se diferencian estas opciones, qué talla me queda. Son justo las preguntas que los compradores hacen a los asistentes. Escribe guías que respondan en las primeras líneas, comparen opciones con honestidad y enlacen a los productos y colecciones. Suma una sección breve de preguntas frecuentes en cada categoría clave, con preguntas reales de atención al cliente, chats y reseñas.'],
                ['h2', 'Reseñas y menciones externas'],
                ['p', 'Los asistentes miran más allá de tu tienda. Las reseñas en tu sitio y en plataformas de opiniones, las menciones en artículos comparativos, guías de regalos, foros y contenido de creadores influyen en qué marcas se sugieren. Pide reseñas después de la entrega, responde preguntas en público y busca presencia en los medios que leen tus compradores. Mantén los datos de tus productos iguales en todos los lugares donde apareces.'],
                ['h2', 'Funciones de compra en asistentes de IA y en Google'],
                ['p', 'Google Shopping, los AI Overviews y varios asistentes de IA muestran fichas de producto con precio y disponibilidad. En Google, buena parte de esos datos viene de Google Merchant Center, así que un feed completo y preciso importa también para las fichas orgánicas, no solo para los anuncios. Corrige los errores del feed, usa categorías y atributos precisos y verifica que los precios coincidan con tu sitio. Otros asistentes están sumando sus propias experiencias de compra, y el principio es el mismo: datos de producto limpios y coherentes.'],
                ['h2', 'Lo específico de Shopify'],
                ['ul', [
                    '<strong>Datos estructurados del tema</strong>: muchos temas de Shopify incluyen marcado Product, pero revisa qué genera el tuyo y completa lo que falta (marca, GTIN, reseñas) en lugar de duplicar marcado.',
                    '<strong>Colecciones como páginas de categoría</strong>: suma una introducción corta que explique qué es la colección y para quién es, y una breve sección de preguntas debajo de los productos.',
                    '<strong>Blog y guías</strong>: usa el blog de Shopify para guías de compra y comparativas, enlazadas desde colecciones y productos.',
                    '<strong>Apps, con cuidado</strong>: las apps de reseñas y SEO pueden ayudar, pero cada una suma scripts y a veces marcado que choca con el del tema. Revisa qué insertan y quita las que no uses.',
                    '<strong>Canal de Google y YouTube</strong>: conecta tu catálogo con Merchant Center, así que mantén los datos limpios desde el origen.',
                ]],
                ['h2', 'Cómo medir el tráfico que llega desde la IA'],
                ['p', 'En GA4, crea un grupo de canales o una exploración para las sesiones que llegan desde herramientas de IA (por ejemplo chatgpt.com, perplexity.ai, gemini.google.com y copilot.microsoft.com) y mide sus conversiones por separado. Revisa en Merchant Center el rendimiento de las fichas gratuitas. Cada mes, prueba una lista fija de preguntas de compra en los principales asistentes y anota si aparecen tus productos y cómo los describen.'],
                ['p', 'Si tu tienda necesita una base técnica que sostenga todo esto, mira nuestros <a href="{service:website}">servicios de sitios web y e-commerce</a>. Para el contenido y la visibilidad, nuestros <a href="{seo-aeo}">servicios de AEO y SEO</a> pueden ayudar a que tus productos sean la respuesta.'],
            ],
            'faq_title': 'Preguntas frecuentes',
            'faq': [
                ['¿El AEO para ecommerce reemplaza al SEO de productos?', 'No. El AEO para ecommerce se apoya en el SEO de productos. Los asistentes siguen usando páginas que pueden rastrear y entender, así que las páginas de producto y colección indexables, la velocidad y los enlaces internos siguen siendo la base. El AEO suma datos coherentes, datos estructurados, guías de compra y reseñas que facilitan la recomendación.'],
                ['¿Shopify sirve para hacer AEO?', 'Sí, Shopify es un buen punto de partida: URL limpias, marcado de producto en muchos temas, un blog integrado y una conexión sencilla con Google Merchant Center. El trabajo está en los detalles: datos de producto completos, introducciones y preguntas en las colecciones, guías de compra útiles y una elección cuidadosa de apps para evitar marcado duplicado.'],
                ['¿Necesito Google Merchant Center si no hago anuncios?', 'Conviene tenerlo. Los feeds de Merchant Center alimentan las fichas gratuitas de productos en Google, no solo los anuncios de Shopping, y le dan a Google datos estructurados como precio y disponibilidad. Un feed limpio y preciso facilita que Google muestre tus productos cuando los compradores comparan opciones antes de decidir.'],
            ],
            'takeaways': [
                'Los compradores preguntan a la IA qué comprar, así que tus datos de producto deben ser fáciles de leer.',
                'Mantén títulos, especificaciones, precios y disponibilidad iguales en tu sitio, tu feed y los marketplaces.',
                'Los datos estructurados, las guías de compra y las preguntas por categoría le dan material a la IA.',
                'En Shopify, aprovecha colecciones, blog y Merchant Center, y revisa las apps con cuidado.',
            ],
        },
    },

    # -----------------------------------------------------------------------
    # AEO para negocios locales en Florida
    # -----------------------------------------------------------------------
    {
        'key': 'aeo-local-florida',
        'publish_gmt': '2026-12-15 13:00:00',
        'cat': 'local',
        'image': 'post-aeo-local-florida',
        'en': {
            'slug': 'aeo-for-local-businesses-florida',
            'title': 'AEO in Florida: How Local Businesses Get Recommended by AI',
            'seo': ['AEO in Florida: How Local Businesses Get Recommended by AI',
                    'Local AEO for Florida businesses: how to get recommended by AI assistants in Tampa, Orlando or Lakeland with a strong Google profile, reviews and local answers.',
                    'aeo florida'],
            'tldr': 'People in Florida ask AI assistants for the best local provider, and the answers draw on your Google Business Profile, reviews, directories and website. Local AEO makes those signals complete and consistent, adds service and city pages with direct answers and serves both English and Spanish speakers.',
            'intro': 'AEO in Florida for local businesses (local Answer Engine Optimization) is the work of making a local company easy for AI assistants to recommend when people ask for the best provider in their city. It combines a complete Google Business Profile, reviews, consistent business data, service and city pages with direct answers and bilingual content.',
            'body': [
                ['h2', 'How people ask AI assistants for local businesses'],
                ['p', 'Local searches are becoming conversations. Instead of typing "plumber Tampa", people ask "who is the best plumber near me that works on weekends?", "which dentist in Orlando speaks Spanish?" or "recommend a roofing company in Lakeland with good reviews". Assistants such as Gemini, ChatGPT and the AI features in Google Search answer with a few names and a reason for each.'],
                ['p', 'Those answers are built from signals you can influence: your Google Business Profile, reviews, directory listings, local mentions and the content on your website. Local AEO works on each of them.'],
                ['h2', 'Complete your Google Business Profile'],
                ['p', 'For local questions, your Google Business Profile is often the first source. Fill in every field that applies:'],
                ['ul', [
                    'Primary and secondary categories that match what you actually do.',
                    'Services and products with short descriptions and, when possible, prices.',
                    'Service areas, hours (including holidays) and attributes such as "Spanish spoken" if it is true.',
                    'Recent photos of your team, location and work.',
                    'Questions and answers, plus regular updates about offers or news.',
                ]],
                ['h2', 'Reviews that describe what you do'],
                ['p', 'Reviews help assistants decide who to recommend and why. Ask every satisfied customer for a review, make it easy with a direct link and reply to all of them, positive or negative. Reviews that mention the service and the city ("fixed our AC in Lakeland the same day") give assistants useful context. Never buy or filter reviews: it breaks platform rules and erodes trust.'],
                ['h2', 'Consistent NAP across directories'],
                ['p', 'NAP stands for name, address and phone. Keep them identical on your website, Google Business Profile, Apple Business Connect, Bing Places, Yelp, industry directories and social profiles. Small differences, such as an old suite number or a tracking phone, make it harder for AI tools to confirm that all those listings are the same business.'],
                ['h2', 'Service and city pages with direct answers'],
                ['p', 'Create one page per core service and, where you truly serve them, one page per city or area. Start each page with a two or three sentence answer: what you offer, where and for whom. Then add details that assistants and customers look for: process, typical timelines, what affects the price, areas covered and real photos. Avoid copying the same text across city pages with only the name changed.'],
                ['h2', 'Bilingual content for Florida customers'],
                ['p', 'Florida has a large Spanish-speaking population, and many people ask assistants in Spanish. If you serve customers in Spanish, publish your key pages in both languages with proper hreflang tags, write natural Spanish rather than machine translation and say clearly on your profile and site that your team speaks Spanish. It is also a trust signal for customers who want to be served in their language.'],
                ['h2', 'Local FAQs that answer before the call'],
                ['p', 'Collect the questions your team hears every week and answer them on your site in 40 to 60 words each:'],
                ['ul', [
                    'How much does it cost, and what changes the price?',
                    'How long does it take, and how soon can you start?',
                    'Which cities and neighborhoods do you serve?',
                    'Do you offer service in Spanish?',
                    'What do I need to prepare before the appointment?',
                ]],
                ['h2', 'LocalBusiness schema and local mentions'],
                ['p', 'Add LocalBusiness structured data (or a more specific type, such as Dentist or Plumber) with your name, address, phone, hours, service area and profile links, matching your Google Business Profile exactly. Then build local mentions: chambers of commerce, local media, community sponsorships, business associations and partners who can link to you. These are the sources that help AI tools see you as a real part of your community.'],
                ['p', 'We explain the local SEO base in <a href="{post:lakeland-local-seo}">our guide to local SEO in Lakeland</a>. If you want a team to handle it, see our <a href="{seo-aeo}">AEO and SEO services</a>, our <a href="{lakeland}">SEO and digital marketing services in Lakeland</a> or our <a href="{florida}">performance marketing agency in Florida</a>.'],
            ],
            'faq_title': 'Frequently asked questions',
            'faq': [
                ['Is local AEO different from local SEO?', 'Local AEO builds on local SEO. Both rely on a complete Google Business Profile, reviews, consistent business data and good local pages. Local AEO adds a focus on direct answers to the questions people ask assistants, bilingual content and local mentions, so AI tools can describe and recommend your business with confidence.'],
                ['Do I need separate pages for each Florida city?', 'Only for the cities you really serve and where you have something specific to say, such as local projects, travel times or area details. A few strong city pages work better than dozens of copies with the city name swapped. Link each one to the relevant services and keep your service areas consistent everywhere.'],
                ['Should a Florida business publish content in Spanish?', 'If you serve Spanish-speaking customers, yes. Many people in Florida search and ask assistants in Spanish, and a well written Spanish page is easier to recommend for those questions than an English page alone. Translate your key service pages and FAQs, use hreflang tags and mention on your profile that you offer service in Spanish.'],
            ],
            'takeaways': [
                'People ask AI assistants for the best local provider, and your local signals shape the answer.',
                'A complete Google Business Profile, genuine reviews and consistent NAP are the base.',
                'Service and city pages with direct answers and local FAQs give assistants material to cite.',
                'Bilingual content and local mentions help Florida businesses stand out.',
            ],
        },
        'es': {
            'slug': 'aeo-para-negocios-locales-en-florida',
            'title': 'AEO en Florida: cómo lograr que la IA recomiende tu negocio local',
            'seo': ['AEO en Florida: que la IA recomiende tu negocio local',
                    'AEO local para negocios en Florida: cómo lograr que la IA te recomiende en Tampa, Orlando o Lakeland con un buen perfil de Google, reseñas y respuestas locales.',
                    'AEO en Florida'],
            'tldr': 'En Florida la gente pregunta a los asistentes de IA por el mejor proveedor local, y las respuestas se apoyan en tu Perfil de Empresa de Google, tus reseñas, los directorios y tu sitio. El AEO local hace que esas señales estén completas y sean coherentes, suma páginas por servicio y ciudad con respuestas directas y atiende a clientes en inglés y en español.',
            'intro': 'El AEO en Florida para negocios locales (Answer Engine Optimization local) es el trabajo de lograr que los asistentes de IA recomienden a una empresa local cuando alguien pregunta por el mejor proveedor de su ciudad. Combina un Perfil de Empresa de Google completo, reseñas, datos coherentes, páginas por servicio y ciudad con respuestas directas y contenido bilingüe.',
            'body': [
                ['h2', 'Cómo le piden las personas negocios locales a la IA'],
                ['p', 'Las búsquedas locales se están volviendo conversaciones. En lugar de escribir "plomero Tampa", la gente pregunta "¿quién es el mejor plomero cerca de mí que trabaje los fines de semana?", "¿qué dentista en Orlando habla español?" o "recomiéndame una empresa de techos en Lakeland con buenas reseñas". Asistentes como Gemini, ChatGPT y las funciones de IA de Google responden con pocos nombres y una razón para cada uno.'],
                ['p', 'Esas respuestas se arman con señales en las que puedes influir: tu Perfil de Empresa de Google, las reseñas, los directorios, las menciones locales y el contenido de tu sitio. El AEO local trabaja cada una de ellas.'],
                ['h2', 'Completa tu Perfil de Empresa de Google'],
                ['p', 'Para las preguntas locales, tu Perfil de Empresa de Google suele ser la primera fuente. Completa todos los campos que apliquen:'],
                ['ul', [
                    'Categorías principal y secundarias que coincidan con lo que realmente haces.',
                    'Servicios y productos con descripciones cortas y, cuando se pueda, precios.',
                    'Zonas de servicio, horarios (incluidos feriados) y atributos como "se habla español" si es cierto.',
                    'Fotos recientes de tu equipo, tu local y tu trabajo.',
                    'Preguntas y respuestas, además de publicaciones regulares con ofertas o novedades.',
                ]],
                ['h2', 'Reseñas que describen lo que haces'],
                ['p', 'Las reseñas ayudan a los asistentes a decidir a quién recomendar y por qué. Pide una reseña a cada cliente satisfecho, facilítalo con un enlace directo y responde todas, positivas o negativas. Las reseñas que mencionan el servicio y la ciudad ("arreglaron nuestro aire acondicionado en Lakeland el mismo día") le dan contexto útil a la IA. Nunca compres ni filtres reseñas: rompe las reglas de las plataformas y daña la confianza.'],
                ['h2', 'NAP coherente en todos los directorios'],
                ['p', 'NAP significa nombre, dirección y teléfono (name, address, phone). Mantenlos idénticos en tu sitio, tu Perfil de Empresa de Google, Apple Business Connect, Bing Places, Yelp, directorios del sector y redes sociales. Las pequeñas diferencias, como un número de oficina antiguo o un teléfono de seguimiento, hacen que a la IA le cueste confirmar que todos esos perfiles son el mismo negocio.'],
                ['h2', 'Páginas por servicio y ciudad con respuestas directas'],
                ['p', 'Crea una página por cada servicio principal y, donde realmente trabajes, una página por ciudad o zona. Empieza cada página con una respuesta de dos o tres oraciones: qué ofreces, dónde y para quién. Luego suma los detalles que buscan los asistentes y los clientes: proceso, plazos habituales, qué influye en el precio, zonas que cubres y fotos reales. Evita copiar el mismo texto en todas las páginas de ciudad cambiando solo el nombre.'],
                ['h2', 'Contenido bilingüe para clientes en Florida'],
                ['p', 'Florida tiene una gran población hispanohablante, y mucha gente le pregunta a los asistentes en español. Si atiendes clientes en español, publica tus páginas clave en ambos idiomas con etiquetas hreflang, escribe un español natural en lugar de una traducción automática y deja claro en tu perfil y en tu sitio que tu equipo habla español. También es una señal de confianza para quienes prefieren ser atendidos en su idioma.'],
                ['h2', 'Preguntas frecuentes locales que responden antes de la llamada'],
                ['p', 'Junta las preguntas que tu equipo escucha cada semana y respóndelas en tu sitio en 40 a 60 palabras cada una:'],
                ['ul', [
                    '¿Cuánto cuesta y qué hace variar el precio?',
                    '¿Cuánto tarda y cuándo pueden empezar?',
                    '¿En qué ciudades y barrios trabajan?',
                    '¿Atienden en español?',
                    '¿Qué debo preparar antes de la cita?',
                ]],
                ['h2', 'Schema LocalBusiness y menciones locales'],
                ['p', 'Suma datos estructurados LocalBusiness (o un tipo más específico, como Dentist o Plumber) con tu nombre, dirección, teléfono, horarios, zona de servicio y enlaces a tus perfiles, idénticos a tu Perfil de Empresa de Google. Después construye menciones locales: cámaras de comercio, medios locales, patrocinios comunitarios, asociaciones empresariales y socios que puedan enlazarte. Son las fuentes que ayudan a la IA a verte como parte real de tu comunidad.'],
                ['p', 'Explicamos la base del SEO local en <a href="{post:lakeland-local-seo}">nuestra guía de SEO local en Lakeland</a>. Si quieres que un equipo lo haga, mira nuestros <a href="{seo-aeo}">servicios de AEO y SEO</a>, nuestros <a href="{lakeland}">servicios de SEO y marketing digital en Lakeland</a> o nuestra <a href="{florida}">agencia de performance marketing en Florida</a>.'],
            ],
            'faq_title': 'Preguntas frecuentes',
            'faq': [
                ['¿El AEO local es distinto del SEO local?', 'El AEO local se apoya en el SEO local. Ambos dependen de un Perfil de Empresa de Google completo, reseñas, datos coherentes y buenas páginas locales. El AEO local suma el foco en respuestas directas a las preguntas que la gente hace a los asistentes, el contenido bilingüe y las menciones locales, para que la IA te recomiende con confianza.'],
                ['¿Necesito una página para cada ciudad de Florida?', 'Solo para las ciudades donde realmente trabajas y donde tienes algo específico que decir, como proyectos locales, tiempos de traslado o detalles de la zona. Unas pocas páginas sólidas funcionan mejor que decenas de copias con el nombre de la ciudad cambiado. Enlaza cada una a sus servicios y mantén tus zonas de servicio coherentes.'],
                ['¿Un negocio en Florida debería publicar contenido en español?', 'Si atiendes clientes hispanohablantes, sí. Mucha gente en Florida busca y pregunta a los asistentes en español, y una buena página en español es más fácil de recomendar para esas preguntas que una página solo en inglés. Traduce tus páginas de servicios y preguntas frecuentes, usa hreflang e indica en tu perfil que atiendes en español.'],
            ],
            'takeaways': [
                'La gente pide a la IA el mejor proveedor local, y tus señales locales definen la respuesta.',
                'Un Perfil de Empresa de Google completo, reseñas reales y un NAP coherente son la base.',
                'Las páginas por servicio y ciudad con respuestas directas y preguntas locales le dan material a la IA.',
                'El contenido bilingüe y las menciones locales ayudan a destacar en Florida.',
            ],
        },
    },

    # -----------------------------------------------------------------------
    # Plan de marketing 2027
    # -----------------------------------------------------------------------
    {
        'key': 'plan-2027',
        'publish_gmt': '2026-12-22 13:00:00',
        'cat': 'performance',
        'image': 'post-plan-2027',
        'en': {
            'slug': 'marketing-plan-2027',
            'title': 'Marketing Plan 2027: How to Split Your Budget Across SEO, AEO and Paid Media',
            'seo': ['Marketing Plan 2027: Split Budget Across SEO, AEO and Ads',
                    'Build your marketing plan 2027: start from revenue goals and unit economics, then split budget across paid search, paid social, SEO and AEO with a test reserve.',
                    'marketing plan 2027'],
            'tldr': 'A good marketing plan for 2027 starts from revenue goals and unit economics, not from last year\'s budget. Audit what worked in 2026, split spend by role (capturing demand, creating demand and compounding channels such as SEO and AEO), keep a reserve for tests, fix measurement first and review every quarter.',
            'intro': 'A marketing plan 2027 is the document that turns next year\'s revenue goals into channels, budgets and metrics. It defines how much you can pay to acquire a customer, which channels capture and create demand, how much goes to compounding channels such as SEO and AEO, what you will test and how you will measure results.',
            'body': [
                ['h2', 'Start from revenue goals and unit economics'],
                ['p', 'Before talking about channels, answer three questions with your own numbers:'],
                ['ul', [
                    '<strong>CAC (customer acquisition cost)</strong>: how much you spend in marketing and sales to win one customer.',
                    '<strong>LTV (lifetime value)</strong>: how much gross margin a customer brings over the whole relationship.',
                    '<strong>Payback</strong>: how many months it takes to recover the CAC from that margin.',
                ]],
                ['p', 'Work backwards from the revenue goal: how many new customers you need, at what CAC you can afford them and how long you can wait for payback given your cash. That gives you a realistic budget ceiling and a target cost per acquisition for each channel. If you do not have reliable numbers yet, making them reliable is the first project of 2027.'],
                ['h2', 'Audit your 2026 channels'],
                ['p', 'Look at the last twelve months channel by channel. For each one, list spend, conversions, cost per conversion, revenue or pipeline influenced and what you learned. Separate what worked, what did not and what you could not measure. Be honest about the last group: a channel you cannot measure is not necessarily a bad channel, but it is one you should not scale blindly.'],
                ['h2', 'A framework to split budget by stage'],
                ['p', 'Instead of splitting by platform, split by the role each channel plays:'],
                ['h3', 'Demand capture: paid search'],
                ['p', 'People already looking for what you sell. Paid search on Google and Bing, brand campaigns and Shopping for e-commerce. It is usually the most measurable spend and the first to fund, up to the point where extra budget only buys more expensive clicks.'],
                ['h3', 'Demand creation: paid social and content'],
                ['p', 'People who fit your customer profile but are not searching yet. Paid social on Meta, LinkedIn or TikTok, video, newsletters and content that educates. It fills the pipeline for the months ahead and needs patience and creative testing.'],
                ['h3', 'Compounding channels: SEO and AEO'],
                ['p', 'Content, technical work and brand signals that keep bringing traffic, leads and mentions in AI answers without paying per click. Results take months, but each piece of work adds to the next. Protect this line in the budget even when paid channels look more urgent. Our <a href="{seo-aeo}">AEO and SEO services</a> cover this layer.'],
                ['h2', 'Illustrative starting points (not benchmarks)'],
                ['p', 'The splits below are scenarios to start a conversation, not data or industry averages. The right mix depends on your margins, sales cycle, competition, market and how much demand already exists for your product.'],
                ['ul', [
                    '<strong>A local service business with existing search demand</strong> might start heavier on paid search and local SEO, with a smaller share for paid social and a test reserve.',
                    '<strong>A new product in a category people do not search for yet</strong> might start heavier on demand creation, with paid search limited to brand and high intent terms.',
                    '<strong>An established brand with organic traffic</strong> might move more budget into SEO, AEO and content, and use paid media to fill specific gaps.',
                ]],
                ['h2', 'Keep a test budget reserve'],
                ['p', 'Set aside a fixed part of the budget for experiments: a new platform, a new audience, a new offer or a new format. Define each test before launching it: hypothesis, budget, duration and the metric that decides whether it scales. Tests that win move into the main plan next quarter; tests that lose are stopped without drama.'],
                ['h2', 'Build the measurement plan before spending'],
                ['ul', [
                    'Review GA4 events and key events so they reflect real business actions, not only page views.',
                    'Connect conversions to Google Ads and Meta, with enhanced conversions or the Conversions API where appropriate.',
                    'Import offline conversions (qualified leads, closed deals) from your CRM, so platforms optimize for revenue and not only for form fills.',
                    'Create a channel group for AI referral traffic and track mentions in AI answers, as we explain in <a href="{post:aeo-measure}">how to measure AEO</a>.',
                    'Agree on one dashboard and one source of truth for the numbers.',
                ]],
                ['h2', 'Review every quarter'],
                ['p', 'A yearly plan is a starting point. Every quarter, compare each channel against its target CAC and payback, move budget from what underperforms to what works, graduate or stop tests and update the forecast. Leave room for changes in the market, in AI search and in your own offer.'],
                ['p', 'If you want help building your 2027 plan, our <a href="{service:consulting}">marketing strategy consulting</a> starts from your numbers, and our <a href="{service:performance-marketing}">performance marketing services</a> can run the paid media side.'],
            ],
            'faq_title': 'Frequently asked questions',
            'faq': [
                ['How much should I spend on marketing in 2027?', 'There is no universal number. Start from your revenue goal, the number of new customers you need and the acquisition cost you can afford given your margins and payback period. That gives you a budget range grounded in your business. Then adjust it by channel as results come in during quarterly reviews.'],
                ['Should I move budget from SEO to AEO?', 'It is usually not a choice between them. AEO builds on SEO: technical health, useful content and a trustworthy brand support both. What changes is the format and the measurement. Most plans keep one budget line for SEO and AEO together, with part of the work focused on answering questions for AI assistants.'],
                ['How big should the test budget be?', 'It depends on the total budget and your appetite for risk. The key is that it is large enough for each test to reach a clear result in a reasonable time and small enough that a failed test does not hurt the core plan. Define the hypothesis, duration and deciding metric before starting.'],
            ],
            'takeaways': [
                'Build the 2027 plan from revenue goals, CAC, LTV and payback, not from last year\'s budget.',
                'Split budget by role: demand capture, demand creation and compounding channels such as SEO and AEO.',
                'Keep a test reserve and fix measurement, including offline conversions, before scaling.',
                'Treat example splits as starting points and review the mix every quarter.',
            ],
        },
        'es': {
            'slug': 'plan-de-marketing-2027',
            'title': 'Plan de marketing 2027: cómo repartir el presupuesto entre SEO, AEO y medios pagados',
            'seo': ['Plan de marketing 2027: presupuesto para SEO, AEO y ads',
                    'Arma tu plan de marketing 2027: parte de tus metas de ingresos y tu economía unitaria y reparte el presupuesto entre búsqueda paga, redes, SEO y AEO.',
                    'plan de marketing 2027'],
            'tldr': 'Un buen plan de marketing para 2027 parte de las metas de ingresos y de la economía unitaria, no del presupuesto del año anterior. Revisa qué funcionó en 2026, reparte la inversión según el rol de cada canal (captar demanda, crear demanda y canales que se acumulan, como SEO y AEO), guarda una reserva para pruebas, ordena la medición primero y revisa cada trimestre.',
            'intro': 'Un plan de marketing 2027 es el documento que convierte las metas de ingresos del próximo año en canales, presupuestos y métricas. Define cuánto puedes pagar por conseguir un cliente, qué canales captan y crean demanda, cuánto va a canales que se acumulan, como SEO y AEO, qué vas a probar y cómo medirás los resultados.',
            'body': [
                ['h2', 'Parte de las metas de ingresos y la economía unitaria'],
                ['p', 'Antes de hablar de canales, responde tres preguntas con tus propios números:'],
                ['ul', [
                    '<strong>CAC (costo de adquisición de clientes)</strong>: cuánto gastas en marketing y ventas para ganar un cliente.',
                    '<strong>LTV (valor de vida del cliente)</strong>: cuánto margen bruto deja un cliente durante toda la relación.',
                    '<strong>Payback (periodo de recuperación)</strong>: cuántos meses tardas en recuperar el CAC con ese margen.',
                ]],
                ['p', 'Trabaja hacia atrás desde la meta de ingresos: cuántos clientes necesitas sumar, a qué CAC puedes pagarlos y cuánto tiempo puedes esperar la recuperación según tu caja. Así obtienes un tope de presupuesto realista y un costo por adquisición objetivo para cada canal. Si todavía no tienes números confiables, lograrlos es el primer proyecto de 2027.'],
                ['h2', 'Revisa tus canales de 2026'],
                ['p', 'Mira los últimos doce meses canal por canal. Para cada uno, anota inversión, conversiones, costo por conversión, ingresos o pipeline influido y lo que aprendiste. Separa lo que funcionó, lo que no y lo que no pudiste medir. Sé honesto con ese último grupo: un canal que no puedes medir no es necesariamente malo, pero no conviene escalarlo a ciegas.'],
                ['h2', 'Un marco para repartir el presupuesto por etapa'],
                ['p', 'En lugar de repartir por plataforma, reparte según el rol de cada canal:'],
                ['h3', 'Captar demanda: búsqueda paga'],
                ['p', 'Personas que ya buscan lo que vendes. Búsqueda paga en Google y Bing, campañas de marca y Shopping para e-commerce. Suele ser la inversión más medible y la primera en financiarse, hasta el punto en que más presupuesto solo compra clics más caros.'],
                ['h3', 'Crear demanda: redes pagas y contenido'],
                ['p', 'Personas que encajan con tu perfil de cliente pero todavía no buscan. Publicidad en Meta, LinkedIn o TikTok, video, newsletters y contenido que educa. Llena el pipeline de los próximos meses y necesita paciencia y pruebas creativas.'],
                ['h3', 'Canales que se acumulan: SEO y AEO'],
                ['p', 'Contenido, trabajo técnico y señales de marca que siguen trayendo tráfico, contactos y menciones en las respuestas de la IA sin pagar por clic. Los resultados toman meses, pero cada trabajo suma al siguiente. Protege esta línea del presupuesto aunque los canales pagados parezcan más urgentes. Nuestros <a href="{seo-aeo}">servicios de AEO y SEO</a> cubren esta capa.'],
                ['h2', 'Puntos de partida de ejemplo (no son referencias del mercado)'],
                ['p', 'Los repartos de abajo son escenarios para empezar la conversación, no datos ni promedios del sector. La mezcla correcta depende de tus márgenes, tu ciclo de venta, la competencia, tu mercado y cuánta demanda existe ya para tu producto.'],
                ['ul', [
                    '<strong>Un negocio de servicios locales con demanda de búsqueda</strong> podría empezar con más peso en búsqueda paga y SEO local, una parte menor para redes pagas y una reserva de pruebas.',
                    '<strong>Un producto nuevo en una categoría que la gente todavía no busca</strong> podría empezar con más peso en crear demanda, con búsqueda paga limitada a marca y términos de alta intención.',
                    '<strong>Una marca consolidada con tráfico orgánico</strong> podría mover más presupuesto a SEO, AEO y contenido, y usar medios pagados para cubrir huecos concretos.',
                ]],
                ['h2', 'Guarda una reserva para pruebas'],
                ['p', 'Separa una parte fija del presupuesto para experimentos: una plataforma nueva, una audiencia nueva, una oferta nueva o un formato nuevo. Define cada prueba antes de lanzarla: hipótesis, presupuesto, duración y la métrica que decide si escala. Las pruebas que ganan pasan al plan principal el trimestre siguiente; las que pierden se detienen sin drama.'],
                ['h2', 'Arma el plan de medición antes de invertir'],
                ['ul', [
                    'Revisa los eventos y eventos clave de GA4 para que reflejen acciones reales del negocio, no solo visitas.',
                    'Conecta las conversiones con Google Ads y Meta, con conversiones mejoradas o la API de Conversiones cuando corresponda.',
                    'Importa conversiones offline (contactos calificados, ventas cerradas) desde tu CRM, para que las plataformas optimicen por ingresos y no solo por formularios.',
                    'Crea un grupo de canales para el tráfico que llega desde la IA y mide las menciones en sus respuestas, como explicamos en <a href="{post:aeo-measure}">cómo medir el AEO</a>.',
                    'Acuerden un solo tablero y una sola fuente de verdad para los números.',
                ]],
                ['h2', 'Revisa cada trimestre'],
                ['p', 'Un plan anual es un punto de partida. Cada trimestre, compara cada canal con su CAC y periodo de recuperación objetivo, mueve presupuesto de lo que rinde menos a lo que funciona, gradúa o detén las pruebas y actualiza la proyección. Deja margen para los cambios del mercado, de la búsqueda con IA y de tu propia oferta.'],
                ['p', 'Si quieres ayuda para armar tu plan 2027, nuestra <a href="{service:consulting}">consultoría de estrategia de marketing</a> parte de tus números, y nuestros <a href="{service:performance-marketing}">servicios de performance marketing</a> pueden gestionar los medios pagados.'],
            ],
            'faq_title': 'Preguntas frecuentes',
            'faq': [
                ['¿Cuánto debería invertir en marketing en 2027?', 'No hay un número universal. Parte de tu meta de ingresos, de la cantidad de clientes que necesitas sumar y del costo de adquisición que puedes pagar según tus márgenes y tu periodo de recuperación. Eso te da un rango de presupuesto basado en tu negocio. Después ajústalo por canal según los resultados de cada revisión trimestral.'],
                ['¿Debería pasar presupuesto del SEO al AEO?', 'No hace falta elegir. El AEO se apoya en el SEO: la salud técnica, el contenido útil y una marca confiable sostienen a ambos. Lo que cambia es el formato y la medición. La mayoría de los planes mantiene una sola línea para SEO y AEO, con parte del trabajo enfocado en responder preguntas para los asistentes de IA.'],
                ['¿Qué tan grande debe ser el presupuesto de pruebas?', 'Depende del presupuesto total y de cuánto riesgo aceptas. Lo importante es que alcance para que cada prueba llegue a un resultado claro en un tiempo razonable, y que sea lo bastante chico para que una prueba fallida no afecte el plan principal. Define la hipótesis, la duración y la métrica de decisión antes de empezar.'],
            ],
            'takeaways': [
                'Arma el plan 2027 desde las metas de ingresos, el CAC, el LTV y el payback, no desde el presupuesto anterior.',
                'Reparte el presupuesto por rol: captar demanda, crear demanda y canales que se acumulan, como SEO y AEO.',
                'Guarda una reserva para pruebas y ordena la medición, incluidas las conversiones offline, antes de escalar.',
                'Toma los repartos de ejemplo como puntos de partida y revisa la mezcla cada trimestre.',
            ],
        },
    },
]
