"""Ajustes SEO (grupo B): website, growth-hacking, analytics, ai-assistants, marketing-automation. Tuplas (ES, EN)."""

SEO = {
    'website': dict(
        kw=('desarrollo de e-commerce', 'e-commerce development'),
        title=('Desarrollo de e-commerce y sitios web | FL Marketing',
               'E-commerce Development &amp; Websites | FL Marketing'),
        desc=('Desarrollo de e-commerce en Shopify, WordPress y Wix: tiendas rápidas, listas para SEO y con medición integrada, pensadas para vender más. Conversemos.',
              'E-commerce development on Shopify, WordPress and Wix: fast, SEO-ready stores with tracking built in, designed to turn visitors into buyers. Let’s talk.'),
        lead=('El desarrollo de e-commerce consiste en construir una tienda online rápida, fácil de usar, optimizada para SEO y pensada para convertir visitas en clientes. Desarrollamos tiendas y sitios web en Shopify, Wix y WordPress conectados a tu estrategia de marketing y a tu medición desde el primer día, para que cada campaña llegue a un sitio que vende.',
              'E-commerce development is building an online store that is fast, easy to use, SEO-ready and designed to turn visitors into customers. We build stores and websites on Shopify, Wix and WordPress, connected to your marketing strategy and your measurement from day one, so every campaign lands on a site that sells.'),
        h1=('Desarrollo de e-commerce y sitios web que venden',
            'E-commerce development: stores and websites that sell'),
        h_inc=('Qué incluye nuestro desarrollo de e-commerce',
               'What our e-commerce development includes'),
        h_faq=('Desarrollo de e-commerce: preguntas frecuentes',
               'E-commerce development: frequently asked questions'),
        guide=dict(
            label=('Cómo planificarlo', 'How to plan it'),
            h2=('¿Cómo planificar un proyecto de desarrollo de e-commerce?',
                'How should you plan an e-commerce development project?'),
            intro=('La mayoría de los proyectos de tienda que salen mal fallan antes de escribir código: alcance poco claro, ningún plan para las URLs existentes o una medición que se agrega al final. Planificar bien el desarrollo de e-commerce significa decidir qué debe hacer la tienda por tu negocio, qué debe conservar del sitio anterior y cómo sabrás que funciona. Estas son las tres preguntas que resolvemos primero.',
                   'Most store projects that go wrong fail before a single line of code: unclear scope, no plan for existing URLs or tracking added at the end. Planning e-commerce development well means deciding what the store must do for your business, what it must keep from the old site and how you will know it works. These are the three questions we settle with you first, before any design or development work begins.'),
            items=[
                ('Define el alcance por ingresos, no por funciones',
                 'Define scope by revenue, not features',
                 'Empieza por el recorrido que genera ventas: ficha de producto, carrito, checkout y correos posteriores a la compra. Cada función adicional (filtros, packs, suscripciones, un formulario de cotización) debe responder una pregunta clara: ¿ayuda a alguien a encontrar, confiar o comprar? Lo que no pase esa prueba puede esperar a una segunda fase. Una primera versión acotada sale antes y te da datos reales para decidir qué construir después.',
                 'Start with the path that produces sales: product page, cart, checkout and post-purchase emails. Every extra feature (filters, bundles, subscriptions, a quote form) should answer a clear question: does it help someone find, trust or buy? Features that fail that test can wait for a second phase. A lean first version launches sooner and gives you real data to decide what to build next.'),
                ('Protege el posicionamiento al migrar',
                 'Protect rankings in a migration',
                 'Si vienes de otra plataforma, haz una lista de cada URL que recibe tráfico orgánico o enlaces externos y asígnale su nueva dirección con redirecciones 301. Conserva títulos, descripciones y datos estructurados donde sigan aplicando, y revisa que las páginas de producto y categoría mantengan su contenido. Después del lanzamiento, vigila Search Console durante las primeras semanas y corrige rápido las redirecciones rotas.',
                 'If you are moving from another platform, list every URL that receives organic traffic or backlinks and map it to its new address with 301 redirects. Keep titles, descriptions and structured data where they still apply, and check that product and category pages keep their content. After launch, watch Search Console during the first weeks and fix broken redirects quickly, before search engines drop the old pages from their index.'),
                ('Conecta la tienda con tu stack',
                 'Connect the store to your stack',
                 'Una tienda vale tanto como los datos que comparte. Antes de lanzar, confirma que GA4 y Google Tag Manager registran las compras con su valor, que los píxeles publicitarios reciben los mismos eventos y que los clientes nuevos llegan a tu CRM o plataforma de email. Cuando tienda, medición y flujos de email están conectados, el desarrollo de e-commerce deja de ser un proyecto aislado y se convierte en la base de cada campaña.',
                 'A store is only as useful as the data it shares. Before launch, confirm that GA4 and Google Tag Manager capture purchases with their value, that ad pixels receive the same events and that new customers reach your CRM or email platform. When storefront, tracking and email flows are connected, e-commerce development stops being a one-off project and becomes the base for every campaign.'),
            ],
        ),
        ref=None,
    ),

    'growth-hacking': dict(
        kw=('growth hacking', 'growth hacking'),
        title=('Growth hacking: experimentos que escalan | FL Marketing',
               'Growth Hacking: Experiments That Scale | FL Marketing'),
        desc=('Growth hacking para marcas que buscan crecer de forma medible: experimentos priorizados, pruebas A/B y retención para escalar solo lo que funciona. Empieza hoy.',
              'Growth hacking for brands that want measurable growth: prioritized experiments, A/B tests and retention work that scale only what works. Start testing today.'),
        lead=('El growth hacking es un método para crecer más rápido probando ideas de adquisición, activación y retención de forma sistemática. Diseñamos experimentos, medimos su impacto y escalamos solo lo que demuestra resultados, combinando marketing, producto y datos en un mismo proceso que tu equipo puede sostener.',
              'Growth hacking is a method to grow faster by systematically testing acquisition, activation and retention ideas. We design experiments, measure their impact and scale only what proves results, combining marketing, product and data in a single process your team can keep running.'),
        h1=('Growth hacking con datos y experimentación',
            'Growth hacking powered by data and experimentation'),
        h_inc=('Qué incluye nuestro servicio de growth hacking',
               'What our growth hacking service includes'),
        h_faq=('Growth hacking: preguntas frecuentes',
               'Growth hacking: frequently asked questions'),
        guide=dict(
            label=('Cómo funciona', 'How it works'),
            h2=('¿Cómo funciona un programa de growth hacking en la práctica?',
                'How does a growth hacking program work in practice?'),
            intro=('El growth hacking tiene menos de trucos ingeniosos y más de ritmo constante: eliges una métrica, pruebas ideas contra ella y te quedas con lo que funciona. El valor viene de correr muchos experimentos de crecimiento pequeños con reglas claras, no de una gran apuesta. Así suele desarrollarse un programa de experimentación, los errores que lo frenan y cómo se conecta con las herramientas que ya usas.',
                   'Growth hacking is less about clever tricks and more about a steady rhythm: pick a metric, test ideas against it and keep what works. The value comes from running many small growth experiments with clear rules, not from one big bet. Here is how an experimentation program usually unfolds, the mistakes that stall it and how it plugs into the tools your team already uses every day.'),
            items=[
                ('Los primeros meses',
                 'The first months',
                 'Las primeras semanas se dedican a la medición: confirmar que GA4 registra los pasos clave del funnel y que cada prueba se puede leer sin ambigüedad. Luego viene un backlog priorizado según impacto esperado, confianza y esfuerzo. Las primeras pruebas suelen ser simples, sobre landing pages, ofertas y correos de bienvenida. Al cerrar el trimestre deberías tener claro qué palancas mueven tu métrica principal.',
                 'The first weeks go to measurement: confirming that GA4 records the key steps of the funnel and that each test can be read cleanly. Then comes a prioritized backlog, scored by expected impact, confidence and effort. Early tests are usually simple ones on landing pages, offers and welcome emails. By the end of the quarter you should know which levers move your main metric and which ideas to drop.'),
                ('Errores que frenan el crecimiento',
                 'Mistakes that stall growth',
                 'El más común es probar sin tráfico suficiente y declarar un ganador a partir de ruido. Otros: cambiar varias cosas a la vez sin saber cuál funcionó, hacer pruebas de adquisición mientras el producto pierde usuarios después del registro, y no documentar los resultados. Un registro simple de experimentos (hipótesis, métrica, resultado, decisión) evita repetir ideas y convierte cada prueba, incluso una fallida, en aprendizaje.',
                 'The most common one is testing without enough traffic, then declaring a winner from noise. Others: changing several things at once so no one knows what worked, running acquisition tests while the product loses users after signup, and never writing down results. A simple experiment log (hypothesis, metric, result, decision) prevents repeated ideas and turns every test, even a failed one, into learning.'),
                ('Cómo se integra con tu stack',
                 'How it fits your stack',
                 'Las pruebas de adquisición y retención corren sobre las herramientas que ya tienes. Las variantes de landing viven en Shopify o WordPress, los eventos se registran con Google Tag Manager y se leen en GA4, y los experimentos de retención pasan por tu plataforma de email o tu CRM. Cuando una prueba gana, el cambio se aplica de forma permanente en esa misma herramienta y la mejora se mantiene.',
                 'Acquisition and retention tests run on the tools you already have. Landing page variants live in Shopify or WordPress, events are tracked through Google Tag Manager and read in GA4, and retention experiments run through your email platform or CRM. When a test wins, the change is rolled out permanently in that same tool, so the gain stays in place after the experiment ends.'),
            ],
        ),
        ref=(('Documentación de Google Analytics', 'Google Analytics documentation'), 'https://developers.google.com/analytics'),
    ),

    'analytics': dict(
        kw=('analítica de marketing', 'marketing analytics'),
        title=('Analítica de marketing con GA4 y GTM | FL Marketing',
               'Marketing Analytics with GA4 &amp; GTM | FL Marketing'),
        desc=('Analítica de marketing con GA4 y Google Tag Manager: medición confiable, dashboards claros e insights para saber dónde invertir. Pide una revisión de tus datos.',
              'Marketing analytics with GA4 and Google Tag Manager: reliable tracking, clear dashboards and insights that show where to invest next. Book a data review.'),
        lead=('La analítica de marketing mide el impacto real de cada canal y cada campaña para que tomes decisiones con datos confiables. Configuramos la medición con GA4 y Google Tag Manager, construimos dashboards claros y convertimos los números en recomendaciones concretas para crecer e invertir mejor.',
              'Marketing analytics measures the real impact of every channel and campaign so you can make decisions with reliable data. We set up tracking with GA4 and Google Tag Manager, build clear dashboards and turn numbers into concrete recommendations to grow and invest your budget better.'),
        h1=('Analítica de marketing para decidir con datos',
            'Marketing analytics to make data-driven decisions'),
        h_inc=('Qué incluye nuestro servicio de analítica de marketing',
               'What our marketing analytics service includes'),
        h_faq=('Analítica de marketing: preguntas frecuentes',
               'Marketing analytics: frequently asked questions'),
        guide=dict(
            label=('Plan de medición', 'Measurement plan'),
            h2=('¿Cómo saber si tu analítica de marketing es confiable?',
                'How do you know your marketing analytics can be trusted?'),
            intro=('Un dashboard vale tanto como los datos que lo alimentan. Antes de cualquier informe, la analítica de marketing necesita un plan de medición por escrito: qué preguntas del negocio quieres responder, qué eventos las responden y de dónde sale cada número. Con ese plan definido, puedes revisar la configuración pieza por pieza. Estas son las tres áreas donde solemos encontrar los vacíos.',
                   'A dashboard is only as good as the data behind it. Before any report, marketing analytics needs a written measurement plan: which business questions you want to answer, which events answer them and where each number comes from. With that plan in place, you can check the setup piece by piece. These are the three areas where we usually find the gaps.'),
            items=[
                ('Parte de las preguntas del negocio',
                 'Start from business questions',
                 'Anota las decisiones que tomas cada mes (a dónde mover presupuesto, qué campaña pausar, qué producto impulsar) y trabaja hacia atrás hasta los eventos y parámetros que necesitas. Una tienda suele necesitar vistas de producto, agregados al carrito, pasos del checkout y compras con valor; un negocio de leads necesita envíos de formulario con su fuente y una forma de saber qué leads se convirtieron en clientes. Lo que no responde ninguna pregunta es ruido.',
                 'List the decisions you make each month (where to move budget, which campaign to pause, which product to push) and work backward to the events and parameters you need. A store usually needs product views, add to cart, checkout steps and purchases with value; a lead business needs form submissions with their source and a way to know which leads became customers. Anything that answers no question is noise.'),
                ('Errores de medición frecuentes',
                 'Common tracking errors',
                 'Eventos de compra duplicados, valores o moneda ausentes, checkouts en otro dominio que reinician la sesión y etiquetas UTM usadas sin un criterio común entre campañas. La configuración de consentimiento también puede ocultar datos si no está bien hecha. Una forma rápida de detectar problemas es comparar las compras de GA4 con los pedidos de Shopify o de tu sistema para la misma semana: una diferencia grande indica que hay que revisar antes de leer los informes.',
                 'Duplicate purchase events, missing values or currency, cross-domain checkouts that restart sessions, and UTM tags used inconsistently across campaigns. Consent settings can also hide data if they are not configured correctly. A quick way to spot problems is to compare GA4 purchases with orders in Shopify or your back office for the same week: a large gap means the setup needs review before anyone reads the reports.'),
                ('Conecta los datos con los ingresos',
                 'Connect data to revenue',
                 'El tráfico y los clics son fáciles de contar; lo que importa son los ingresos. Vincular GA4 con Google Ads, enviar las conversiones de tu CRM a las plataformas publicitarias y registrar qué leads cierran te permite ver el costo por cliente, no solo el costo por clic. Ahí la analítica de marketing deja de describir el pasado y empieza a indicar hacia dónde debe ir el presupuesto.',
                 'Traffic and clicks are easy to count; revenue is what matters. Linking GA4 with Google Ads, sending conversions from your CRM back to ad platforms and tracking which leads close lets you see cost per customer, not just cost per click. That is when marketing analytics stops describing the past and starts showing where the next part of your budget should go.'),
            ],
        ),
        ref=None,
    ),

    'ai-assistants': dict(
        kw=('asistentes de IA a medida', 'custom AI assistants'),
        title=('Asistentes de IA a medida para empresas | FL Marketing',
               'Custom AI Assistants for Business | FL Marketing'),
        desc=('Asistentes de IA a medida que responden consultas, califican leads y automatizan tareas en tu CRM, Slack o WhatsApp, con control total. Cuéntanos tu caso.',
              'Custom AI assistants that answer questions, qualify leads and automate tasks inside your CRM, Slack or WhatsApp, with full control. Tell us your case.'),
        lead=('Los asistentes de IA a medida son sistemas que resuelven tareas repetitivas, procesan información y apoyan a tu equipo con modelos de inteligencia artificial conectados a tus herramientas. Los diseñamos para marketing, ventas, soporte y operaciones, con lógica clara, revisión humana donde importa y control total sobre lo que pueden ver y hacer.',
              'Custom AI assistants are systems that handle repetitive tasks, process information and support your team using AI models connected to your tools. We design them for marketing, sales, support and operations, with clear logic, human review where it matters and full control over what they can see and do.'),
        h1=('Asistentes de IA a medida para tu negocio',
            'Custom AI assistants for your business'),
        h_inc=('Qué incluyen nuestros asistentes de IA a medida',
               'What our custom AI assistants include'),
        h_faq=('Asistentes de IA a medida: preguntas frecuentes',
               'Custom AI assistants: frequently asked questions'),
        guide=dict(
            label=('Por dónde empezar', 'Where to start'),
            h2=('¿Cómo elegir el primer caso para asistentes de IA a medida?',
                'How do you pick the first use case for custom AI assistants?'),
            intro=('El mejor primer proyecto de asistentes de IA a medida casi nunca es el más ambicioso. Es una tarea que tu equipo repite cada día, con entradas claras, una respuesta correcta conocida y una persona que puede revisar el resultado. Empezar ahí te permite medir el tiempo ahorrado, ajustar la lógica y generar confianza antes de darle más responsabilidad. Tres criterios te ayudan a elegir bien.',
                   'The best first project for custom AI assistants is rarely the most ambitious one. It is a task your team repeats every day, with clear inputs, a known good answer and a person who can review the output. Starting there lets you measure time saved, adjust the logic and build trust before giving an assistant more responsibility. Three criteria help you choose well.'),
            items=[
                ('Busca tareas repetitivas y acotadas',
                 'Look for repetitive, bounded tasks',
                 'Buenos candidatos: responder preguntas frecuentes de clientes a partir de tus propias políticas, calificar leads entrantes antes de que lleguen a ventas, resumir notas de llamadas en el CRM o redactar descripciones de producto desde una ficha técnica. Cada uno tiene una fuente de información definida y un resultado que alguien puede verificar. Las tareas que dependen de criterio, excepciones de precio o decisiones sensibles conviene dejarlas en manos de una persona, con el asistente preparando la información.',
                 'Good candidates include answering frequent customer questions from your own policies, qualifying inbound leads before they reach sales, summarizing call notes into the CRM or drafting product descriptions from a spec sheet. Each has a defined source of information and a result someone can check. Tasks that depend on judgment calls, pricing exceptions or sensitive decisions are better kept with a person, with the assistant preparing the information.'),
                ('Define qué puede ver y hacer',
                 'Decide what it can see and do',
                 'Antes de construir, deja por escrito qué datos puede leer el asistente, qué acciones puede ejecutar (crear un ticket, actualizar un contacto, enviar un mensaje) y cuándo debe derivar a una persona. Mantener permisos acotados y registrar cada conversación facilita rastrear errores. En esta etapa también se elige el modelo, según la tarea, los idiomas que necesitas y cómo deben tratarse tus datos.',
                 'Before building, write down which data the assistant can read, which actions it can take (create a ticket, update a contact, send a message) and when it must hand off to a person. Keeping permissions narrow and logging every conversation makes errors easy to trace. This is also when you choose the model, based on the task, the languages you need and how your data must be handled.'),
                ('Cómo se conecta y mejora',
                 'How it connects and improves',
                 'Los asistentes suelen vivir donde tu equipo ya trabaja: el chat del sitio, WhatsApp, Slack o dentro del CRM, conectados por API o con una herramienta de orquestación como n8n. En las primeras semanas, revisa conversaciones reales, corrige respuestas incorrectas y actualiza la base de conocimiento. Los asistentes de IA a medida mejoran con esa rutina de revisión y ajuste, así que reserva tiempo para ella desde el inicio.',
                 'Assistants usually live where your team already works: a website chat, WhatsApp, Slack or inside the CRM, connected through APIs or an orchestration tool such as n8n. In the first weeks, review real conversations, correct wrong answers and update the knowledge base. Custom AI assistants improve through that routine of review and adjustment, so plan time for it from the start.'),
            ],
        ),
        ref=(('Documentación de la API de Gemini, Google', 'Gemini API documentation by Google'), 'https://ai.google.dev/gemini-api/docs'),
    ),

    'marketing-automation': dict(
        kw=('automatización de marketing', 'marketing automation'),
        title=('Automatización de marketing, CRM y email | FL Marketing',
               'Marketing Automation, CRM &amp; Email | FL Marketing'),
        desc=('Automatización de marketing con CRM y email: flujos que nutren leads, recuperan carritos y fidelizan clientes sin trabajo manual. Diseñemos juntos tus flujos.',
              'Marketing automation with CRM and email: automated flows that nurture leads, recover carts and keep customers buying, without manual work. Let’s map your flows.'),
        lead=('La automatización de marketing usa plataformas como CRM y email marketing para gestionar contactos, nutrir leads y fidelizar clientes sin tareas manuales. Elegimos, implementamos y conectamos las herramientas Martech que tu negocio necesita, con flujos automáticos que mejoran la eficiencia y la experiencia del cliente.',
              'Marketing automation uses platforms such as CRM and email marketing to manage contacts, nurture leads and retain customers without manual work. We select, implement and connect the Martech tools your business needs, with automated flows that improve efficiency and customer experience.'),
        h1=('Automatización de marketing e implementación Martech',
            'Marketing automation &amp; Martech implementation'),
        h_inc=('Qué incluye nuestra automatización de marketing',
               'What our marketing automation service includes'),
        h_faq=('Automatización de marketing: preguntas frecuentes',
               'Marketing automation: frequently asked questions'),
        guide=dict(
            label=('Antes de automatizar', 'Before you automate'),
            h2=('¿Qué necesitas antes de invertir en automatización de marketing?',
                'What do you need before investing in marketing automation?'),
            intro=('Los flujos automáticos valen tanto como los datos que los activan. Antes de elegir software o escribir correos, la automatización de marketing necesita contactos limpios, eventos confiables y una definición compartida de qué es un lead y qué es un cliente. Resolver esta base evita mensajes enviados a las personas equivocadas e informes en los que nadie confía. Estas son las tres piezas que conviene revisar primero.',
                   'Automated flows are only as good as the data that triggers them. Before choosing software or writing emails, marketing automation needs clean contacts, reliable events and a shared definition of what a lead and a customer are. Getting this foundation right avoids messages sent to the wrong people and reports nobody trusts. These are the three pieces worth checking first, whatever platform you end up choosing.'),
            items=[
                ('Datos de contacto limpios y conectados',
                 'Clean, connected contact data',
                 'Une los contactos duplicados, acuerda qué campos son obligatorios y registra el consentimiento de cada canal. Luego define cuál es la fuente de verdad: normalmente el CRM para los leads y la plataforma de la tienda, como Shopify, para los pedidos. Sincronizar ambos con tu herramienta de email hace que un cliente que acaba de comprar deje de recibir el descuento pensado para convencerlo, y que ventas vea el historial completo de cada contacto.',
                 'Merge duplicate contacts, agree on required fields and record consent for each channel. Then decide which system is the source of truth: usually the CRM for leads and the store platform, such as Shopify, for orders. Syncing both with your email tool means a customer who just bought stops receiving the discount meant to convince them, and your sales team sees the full history of each contact in one place.'),
                ('Eventos que activan los flujos',
                 'Events that trigger flows',
                 'Los flujos parten de un comportamiento: un formulario enviado, un producto visto, un carrito abandonado, una compra o varios días sin actividad. Esos eventos salen de tu sitio, se capturan con Google Tag Manager o con integraciones nativas de cada plataforma, y deben llegar a la herramienta de automatización con los datos correctos. Si un evento se dispara dos veces o no se dispara, el flujo hace lo mismo, así que prueba cada disparador antes de activarlo.',
                 'Flows start from behavior: a form submission, a viewed product, an abandoned cart, a purchase or days without activity. Those events come from your site, captured through Google Tag Manager or native platform integrations, and must reach the automation tool with the right data attached. If an event fires twice or not at all, the flow does the same, so test each trigger before switching it on.'),
                ('Mide más allá de las aperturas',
                 'Measure beyond open rates',
                 'Las aperturas y los clics muestran interés, pero la pregunta real es si un flujo cambia el comportamiento. Compara los ingresos o los leads calificados de los contactos que pasaron por el flujo con un grupo que no lo hizo, y revisa cada flujo con una frecuencia fija. Una buena automatización de marketing se mantiene como un producto: los mensajes se actualizan, los segmentos se afinan y los flujos que ya no ayudan se apagan.',
                 'Opens and clicks show engagement, but the real question is whether a flow changes behavior. Compare revenue or qualified leads from contacts who went through the flow with a group that did not, and review each flow on a regular schedule. Good marketing automation is maintained like a product: messages get updated, segments get refined and flows that no longer help get switched off.'),
            ],
        ),
        ref=(('Documentación de Google Tag Manager', 'Google Tag Manager documentation'), 'https://developers.google.com/tag-platform/tag-manager'),
    ),
}
