# Contenido adicional para SEO/AEO: meta, comparativa, conceptos, FAQ (40-60 palabras), prueba y equipo
TESTI = {
 "leo": ("«Trabajar con FL Marketing Management ha sido fantástico para nuestra startup. En los últimos 4 años, nuestro e-commerce ha crecido significativamente gracias a sus estrategias efectivas y su profundo conocimiento de marketing.»",
         "“Working with FL Marketing Management has been fantastic for our startup. Over the past 4 years, our eCommerce has grown significantly thanks to their effective strategies and deep marketing knowledge.”",
         "Leonardo Rangel", ("CEO y fundador, RMPartes.cl","CEO &amp; Founder, RMPartes.cl")),
 "carol": ("«Trabajar con ustedes ha tenido un impacto real en nuestra agencia. Su enfoque estratégico y su apoyo constante mejoraron significativamente cómo gestionamos marcas de vino en cinco países.»",
           "“Working with you has been truly impactful for our agency. Your strategic approach and consistent support have significantly improved how we manage wine brands across five countries.”",
           "Carol Sánchez", ("Directora general, Gig","Managing Director, Gig")),
 "manuel": ("«Desde que empezamos a trabajar juntos, hemos vivido una transformación significativa en nuestro marketing. Sus estrategias innovadoras y su apoyo cercano llevaron a mejoras notables en nuestros resultados.»",
            "“Since we started working together, we’ve experienced a significant transformation in our marketing efforts. Your innovative strategies and hands-on support have led to remarkable improvements in our results.”",
            "Manuel Trigo", ("CEO y fundador, PolariGlass","CEO &amp; Founder, PolariGlass")),
}
X = {
"consulting": dict(
 desc=("Consultoría de marketing digital para definir objetivos, canales y presupuesto con metas medibles. Estrategia senior para marcas en EE. UU. y Latinoamérica.",
       "Digital marketing consulting to define goals, channels and budget with measurable targets. Senior strategy for growing brands in the US and Latin America."),
 cmp=(("¿Consultoría o agencia de ejecución?","Consulting or execution agency?"),
      ("Consultoría","Consulting"),("Agencia de ejecución","Execution agency"),
      [("Qué entrega","What you get","Diagnóstico, plan y dirección estratégica","Audit, plan and strategic direction","Campañas y piezas en funcionamiento","Live campaigns and assets"),
       ("Quién ejecuta","Who executes","Tu equipo, con nuestro acompañamiento","Your team, with our guidance","La agencia","The agency"),
       ("Ideal para","Best for","Equipos internos que necesitan dirección","In-house teams that need direction","Empresas sin equipo de marketing","Companies without a marketing team"),
       ("Duración","Duration","Semanas o acompañamiento mensual","Weeks or monthly advisory","Contrato continuo","Ongoing contract")]),
 defs=[("Plan de marketing","Marketing plan","Documento que define objetivos, audiencias, canales, mensajes y presupuesto para un período concreto.","A document that sets goals, audiences, channels, messaging and budget for a specific period."),
       ("KPI","KPI","Indicador clave de desempeño: la métrica que muestra si una estrategia cumple su objetivo, como ventas o costo por cliente.","Key performance indicator: the metric that shows whether a strategy meets its goal, such as sales or cost per customer."),
       ("Mix de canales","Channel mix","Combinación de canales (buscadores, redes, email, contenido) y el peso de cada uno en el presupuesto.","The combination of channels (search, social, email, content) and the share of budget each one receives.")],
 faq=[("¿Qué incluye una consultoría de marketing digital?","What does digital marketing consulting include?",
       "Incluye un diagnóstico de tus canales, datos y competencia; un plan estratégico con objetivos, canales, mensajes y presupuesto; la definición de KPIs conectados a ventas y sesiones de seguimiento. El resultado es una hoja de ruta concreta que tu equipo puede ejecutar o que podemos ejecutar nosotros.",
       "It includes an audit of your channels, data and competitors; a strategic plan with goals, channels, messaging and budget; a KPI framework tied to revenue; and follow-up sessions. The result is a concrete roadmap that your team can execute, or that we can execute for you from start to finish."),
      ("¿Cuánto dura una consultoría?","How long does a consulting engagement take?",
       "El diagnóstico y el plan inicial suelen tomar entre dos y cuatro semanas, según el tamaño de la cuenta y la cantidad de canales. Después, el acompañamiento puede ser mensual o por proyecto, dependiendo de la madurez de tu equipo y de los objetivos del negocio.",
       "The audit and initial plan usually take two to four weeks, depending on account size and the number of channels involved. After that, advisory can be monthly or per project, depending on your team’s maturity and your business goals for the following months."),
      ("¿Trabajan con equipos internos?","Do you work with in-house teams?",
       "Sí. Podemos liderar la estrategia y dejar la ejecución a tu equipo, trabajar en conjunto o hacernos cargo de todo. En cualquier caso, documentamos las decisiones y compartimos el conocimiento para que tu equipo gane claridad y autonomía, no dependencia de la agencia.",
       "Yes. We can lead strategy and leave execution to your team, work side by side, or take care of everything. In every case, we document decisions and share knowledge so your team gains clarity and autonomy instead of becoming dependent on the agency."),
      ("¿Cuándo conviene contratar una consultoría?","When should I hire a marketing consultant?",
       "Conviene cuando inviertes en marketing pero no sabes qué canales generan ventas, cuando vas a entrar a un nuevo mercado o canal, o cuando tu equipo necesita dirección senior. Un diagnóstico externo suele revelar oportunidades y gastos innecesarios que desde dentro cuesta ver.",
       "It makes sense when you invest in marketing but don’t know which channels drive sales, when you are entering a new market or channel, or when your team needs senior direction. An outside audit usually reveals opportunities and wasted spend that are hard to see from the inside.")],
 testi="carol", team=["Alejandro Lovera","Nicole Arancibia","Felipe Ríos Barraza"], ref=None),

"performance-marketing": dict(
 desc=("Agencia de performance marketing: campañas en Google, Meta, TikTok y LinkedIn optimizadas por ROAS, CPA y ventas reales. Estrategia senior y reportes claros.",
       "Performance marketing agency running Google, Meta, TikTok and LinkedIn campaigns optimized for ROAS, CPA and real revenue. Senior strategy, clear reporting."),
 cmp=(("Performance marketing vs. marketing de marca","Performance marketing vs. brand marketing"),
      ("Performance marketing","Performance marketing"),("Marketing de marca","Brand marketing"),
      [("Objetivo","Goal","Ventas, leads y retorno medible","Sales, leads and measurable return","Recordación y percepción de marca","Awareness and brand perception"),
       ("Métricas","Metrics","ROAS, CPA, tasa de conversión","ROAS, CPA, conversion rate","Alcance, frecuencia, recordación","Reach, frequency, recall"),
       ("Plazo","Timeframe","Resultados en semanas","Results in weeks","Resultados en meses o años","Results in months or years"),
       ("Optimización","Optimization","Continua, según datos","Continuous, data-driven","Por campaña o temporada","Per campaign or season")]),
 defs=[("ROAS","ROAS","Retorno sobre la inversión publicitaria: ingresos generados por cada peso invertido en anuncios. Un ROAS de 4 significa 4 de ingreso por cada 1 invertido.","Return on ad spend: revenue generated for every dollar spent on ads. A ROAS of 4 means 4 in revenue for every 1 spent."),
       ("CPA","CPA","Costo por adquisición: lo que cuesta, en promedio, conseguir una venta o un lead con publicidad.","Cost per acquisition: the average ad cost to get one sale or lead."),
       ("Tasa de conversión","Conversion rate","Porcentaje de personas que realizan la acción deseada, como comprar o dejar sus datos, después de hacer clic en un anuncio.","The percentage of people who complete the desired action, such as buying or submitting a form, after clicking an ad."),
       ("CAC","CAC","Costo de adquisición de cliente: inversión total en marketing y ventas dividida por los clientes nuevos obtenidos.","Customer acquisition cost: total marketing and sales spend divided by the number of new customers acquired.")],
 faq=[("¿Qué es el performance marketing?","What is performance marketing?",
       "Es un modelo de publicidad digital donde cada decisión se toma según resultados medibles, como ventas, leads o ROAS. Las campañas se optimizan de forma continua con datos, pruebas creativas y ajustes de presupuesto para mejorar el retorno de cada peso invertido, en lugar de pagar solo por visibilidad.",
       "It is a digital advertising model where every decision is based on measurable results, such as sales, leads or ROAS. Campaigns are continuously optimized with data, creative testing and budget adjustments to improve the return on every dollar spent, instead of paying only for visibility."),
      ("¿En qué plataformas trabajan?","Which platforms do you work with?",
       "Gestionamos campañas en Google Ads, Meta (Facebook e Instagram), TikTok, LinkedIn y YouTube. Elegimos la combinación según tu público, tu producto, tu ticket promedio y tu objetivo de negocio, y la ajustamos con datos a medida que vemos qué canal genera mejores resultados.",
       "We manage campaigns on Google Ads, Meta (Facebook and Instagram), TikTok, LinkedIn and YouTube. We choose the mix based on your audience, product, average order value and business goal, and we adjust it with data as we learn which channel delivers the best results."),
      ("¿Cuándo se ven resultados?","When will I see results?",
       "Las primeras señales aparecen en las primeras semanas, pero una cuenta suele estabilizarse entre uno y tres meses, cuando los algoritmos aprenden y las pruebas muestran qué funciona. Desde el primer día reportamos avances con métricas claras, como CPA, ROAS y tasa de conversión.",
       "Early signals appear within the first weeks, but an account usually stabilizes within one to three months, once algorithms learn and tests show what works. From day one, we report progress with clear metrics such as CPA, ROAS and conversion rate."),
      ("¿Cómo miden el éxito de una campaña?","How do you measure campaign success?",
       "Medimos el éxito con métricas conectadas a tu negocio: ventas, leads calificados, CPA, ROAS y, cuando hay datos, costo de adquisición de cliente. Antes de lanzar, revisamos que la medición esté bien configurada, porque sin datos confiables no es posible optimizar con precisión.",
       "We measure success with metrics tied to your business: sales, qualified leads, CPA, ROAS and, when data allows, customer acquisition cost. Before launching, we make sure tracking is set up correctly, because without reliable data it is impossible to optimize accurately.")],
 testi="leo", team=["Lusry Montilla","Alejandro Lovera","María Silvia Andueza"],
 ref=(("Definición de tasa de conversión, Ayuda de Google Ads","Conversion rate definition, Google Ads Help"),"https://support.google.com/google-ads/answer/2684489")),

"seo-aeo": dict(
 desc=("Servicios de AEO y SEO para posicionar en Google y ser citado por ChatGPT, Gemini, Perplexity y AI Overviews: SEO técnico, contenido y optimización para IA.",
       "AEO and SEO services to rank on Google and get cited by ChatGPT, Gemini, Perplexity and AI Overviews: technical SEO, content and AI answer optimization."),
 cmp=(("SEO vs. AEO","SEO vs. AEO"),("SEO","SEO"),("AEO","AEO"),
      [("Dónde aparece","Where you appear","Resultados de Google y otros buscadores","Google and other search results","Respuestas de ChatGPT, Gemini, Perplexity","Answers from ChatGPT, Gemini, Perplexity"),
       ("Objetivo","Goal","Tráfico orgánico calificado","Qualified organic traffic","Ser citado y recomendado por la IA","Being cited and recommended by AI"),
       ("Qué optimiza","What it optimizes","Palabras clave, técnica, enlaces","Keywords, technical health, links","Respuestas directas, entidades, datos","Direct answers, entities, facts"),
       ("Cómo se mide","How it’s measured","Posiciones, clics, tráfico","Rankings, clicks, traffic","Menciones y citas en respuestas de IA","Mentions and citations in AI answers")]),
 defs=[("SEO","SEO","Search Engine Optimization: prácticas técnicas y de contenido para mejorar la posición de un sitio en buscadores como Google.","Search Engine Optimization: technical and content practices that improve a site’s position on search engines like Google."),
       ("AEO","AEO","Answer Engine Optimization: optimización del contenido para que asistentes de IA lo entiendan, lo citen y lo recomienden en sus respuestas.","Answer Engine Optimization: optimizing content so AI assistants understand it, cite it and recommend it in their answers."),
       ("GEO","GEO","Generative Engine Optimization: trabajo para que los modelos de IA generativa, como ChatGPT, Gemini y Perplexity, encuentren tu marca, confíen en ella y la mencionen al escribir una respuesta.","Generative Engine Optimization: work that helps generative AI models such as ChatGPT, Gemini and Perplexity find your brand, trust it and mention it when they write an answer."),
       ("Intención de búsqueda","Search intent","El objetivo real detrás de una búsqueda: informarse, comparar o comprar.","The real goal behind a search: learning, comparing or buying."),
       ("Datos estructurados","Structured data","Código (schema.org) que describe el contenido de una página para que buscadores e IA lo interpreten mejor.","Code (schema.org) that describes a page’s content so search engines and AI can interpret it better.")],
 faq=[("¿Qué incluyen los servicios de AEO?","What do AEO services include?",
       "Los servicios de AEO incluyen revisar cómo describen hoy tu marca los asistentes de IA, identificar las preguntas que hacen tus compradores, reestructurar páginas con respuestas directas, preguntas frecuentes y datos estructurados, reforzar las señales de entidad en la web y medir mes a mes las menciones en ChatGPT, Gemini, Perplexity y AI Overviews.",
       "AEO services include auditing how AI assistants describe your brand today, finding the questions your buyers ask, restructuring pages with direct answers, FAQs and structured data, strengthening entity signals across the web, and tracking mentions in ChatGPT, Gemini, Perplexity and Google AI Overviews month by month to guide the next round of content."),
      ("¿Cómo optimizan para Gemini y los AI Overviews de Google?","How do you optimize for Gemini and Google AI Overviews?",
       "Gemini y los AI Overviews se apoyan en el índice de Google, por eso un SEO técnico sólido es la base. Sobre eso escribimos respuestas concisas a preguntas específicas, agregamos datos estructurados, mantenemos los datos de tu marca coherentes en el sitio y en tus perfiles, y creamos páginas que cubren un tema completo.",
       "Gemini and AI Overviews draw on Google’s index, so strong technical SEO is the base. On top of that, we write concise answers to specific questions, add structured data, keep your brand facts consistent across your site and profiles, and build pages that cover a topic completely, which makes your content easier to select and cite."),
      ("¿Ofrecen AEO para empresas SaaS y B2B?","Do you offer AEO for SaaS and B2B companies?",
       "Sí. Los compradores de SaaS y B2B usan cada vez más asistentes de IA para comparar herramientas y armar su lista de proveedores antes de hablar con ventas. Identificamos esas preguntas de comparación y de uso, hacemos que tus páginas de producto, documentación y comparativas las respondan con claridad y medimos si la IA menciona tu marca.",
       "Yes. SaaS and B2B buyers increasingly ask AI assistants to compare tools and shortlist vendors before they talk to sales. We map those comparison and use-case questions, make sure your product pages, docs and comparisons answer them clearly, and track whether AI assistants mention your brand when buyers research your category."),
      ("¿Qué diferencia hay entre SEO y AEO?","What is the difference between SEO and AEO?",
       "El SEO busca que tu sitio aparezca en los resultados de Google y otros buscadores. El AEO busca que asistentes de IA como ChatGPT o Gemini usen tu contenido como fuente en sus respuestas. Se complementan: el SEO atrae tráfico calificado y el AEO construye autoridad y presencia en la búsqueda con IA.",
       "SEO aims to get your site into Google and other search results. AEO aims to get AI assistants like ChatGPT or Gemini to use your content as a source in their answers. They complement each other: SEO drives qualified traffic, while AEO builds authority and presence in AI-powered search."),
      ("¿Qué es el GEO y en qué se diferencia del AEO?","What is GEO and how is it different from AEO?",
       "El GEO (Generative Engine Optimization) y el AEO se superponen mucho. El AEO busca dar respuestas directas que los asistentes citen; el GEO mira cómo perciben tu marca los modelos generativos: menciones en la web, reseñas, datos coherentes y autoridad temática. En la práctica trabajamos ambos y medimos cuántas veces la IA te menciona y te cita.",
       "GEO (Generative Engine Optimization) and AEO overlap heavily. AEO focuses on giving direct answers that assistants can cite; GEO looks more broadly at how generative models perceive your brand: mentions across the web, reviews, consistent facts and topical authority. In practice we work on both and measure how often AI answers mention and cite you."),
      ("¿Cuánto tarda el SEO en dar resultados?","How long does SEO take to work?",
       "Las mejoras técnicas pueden notarse en semanas, pero el posicionamiento orgánico sólido suele tomar entre tres y seis meses, según la competencia y el estado inicial del sitio. Es una inversión acumulativa: el contenido y la autoridad que se construyen siguen generando tráfico durante mucho tiempo.",
       "Technical fixes can show impact within weeks, but solid organic rankings usually take three to six months, depending on competition and the site’s starting point. It is a compounding investment: the content and authority you build keep generating traffic long after the work is done."),
      ("¿Cómo se mide la visibilidad en la IA?","How do you measure AI visibility?",
       "Revisamos con qué frecuencia los principales modelos de IA mencionan tu marca frente a la competencia en preguntas relevantes de tu industria. Con esos datos priorizamos qué contenido crear o mejorar, y seguimos la evolución de las menciones mes a mes para medir el avance.",
       "We track how often major AI models mention your brand versus competitors for relevant questions in your industry. With that data, we prioritize which content to create or improve, and we follow how mentions evolve month by month to measure progress."),
      ("¿Necesito SEO si ya invierto en publicidad?","Do I need SEO if I already run ads?",
       "Sí. La publicidad genera tráfico mientras pagas; el SEO construye un canal propio que sigue funcionando sin costo por clic. Además, un buen SEO mejora la calidad de las páginas a las que llegan los anuncios, lo que suele reducir costos y aumentar la conversión.",
       "Yes. Ads bring traffic only while you pay; SEO builds an owned channel that keeps working without a cost per click. Good SEO also improves the quality of the pages your ads send people to, which usually lowers costs and increases conversion.")],
 testi="leo", team=["Antonio Araya","Daniel Mansutti","Felipe Ríos Barraza"],
 ref=(("Documentación de Google Search Central","Google Search Central documentation"),"https://developers.google.com/search/docs")),

"aeo-content": dict(
 desc=("Contenido AEO para búsqueda con IA: páginas, guías y FAQ estructuradas para que ChatGPT, Gemini y Perplexity entiendan, citen y recomienden tu marca.",
       "AEO content for AI search: pages, guides and FAQs structured so ChatGPT, Gemini and Perplexity understand, cite and recommend your brand to customers."),
 cmp=(("Contenido AEO vs. contenido SEO tradicional","AEO content vs. traditional SEO content"),("Contenido AEO","AEO content"),("SEO tradicional","Traditional SEO"),
      [("Pensado para","Written for","Personas y modelos de lenguaje","People and language models","Personas y buscadores","People and search engines"),
       ("Estructura","Structure","Respuestas directas y bloques autónomos","Direct answers and self-contained blocks","Artículos largos por palabra clave","Long articles by keyword"),
       ("Éxito","Success","Ser citado en respuestas de IA","Being cited in AI answers","Posicionar en Google","Ranking on Google"),
       ("Clave","Key factor","Claridad, datos verificables, autoría","Clarity, verifiable facts, authorship","Palabras clave y enlaces","Keywords and links")]),
 defs=[("LLM","LLM","Modelo de lenguaje de gran tamaño, como los que usan ChatGPT, Gemini o Claude para generar respuestas.","Large language model, like those behind ChatGPT, Gemini or Claude, used to generate answers."),
       ("Bloque de respuesta","Answer block","Párrafo breve, de unas 40 a 60 palabras, que responde una pregunta de forma directa y sin depender del resto de la página.","A short paragraph, around 40 to 60 words, that answers a question directly without relying on the rest of the page."),
       ("Entidad","Entity","Persona, marca, lugar o concepto que buscadores e IA reconocen de forma única y relacionan con otros temas.","A person, brand, place or concept that search engines and AI recognize uniquely and connect to other topics."),
       ("E-E-A-T","E-E-A-T","Experiencia, pericia, autoridad y confianza: señales que ayudan a buscadores e IA a decidir en qué contenido confiar.","Experience, expertise, authoritativeness and trust: signals that help search engines and AI decide which content to rely on.")],
 faq=[("¿Qué es el contenido AEO?","What is AEO content?",
       "Es contenido escrito y estructurado para que asistentes de IA como ChatGPT, Gemini o Perplexity lo entiendan y lo usen como fuente. Usa respuestas directas, definiciones claras, datos verificables y una estructura lógica que facilita que los modelos lo citen con precisión y asocien tu marca al tema.",
       "It is content written and structured so AI assistants like ChatGPT, Gemini or Perplexity can understand it and use it as a source. It relies on direct answers, clear definitions, verifiable facts and a logical structure that helps models cite it accurately and connect your brand to the topic."),
      ("¿El contenido AEO reemplaza al SEO?","Does AEO content replace SEO?",
       "No. El contenido AEO se apoya en las bases del SEO, como una buena estructura, velocidad de carga, datos estructurados y enlaces internos. Lo ideal es trabajarlos juntos para tener visibilidad tanto en los resultados de Google como en las respuestas generadas por la IA.",
       "No. AEO content builds on SEO foundations such as good structure, fast load times, structured data and internal linking. Ideally, both are worked together so your brand gains visibility in Google results and in AI-generated answers at the same time."),
      ("¿Dónde se aplica el contenido AEO?","Where is AEO content used?",
       "En páginas de servicio, guías educativas, secciones de preguntas frecuentes, comparativas y artículos explicativos. Cada pieza responde preguntas reales que tu público hace en buscadores y en herramientas de IA, con un formato fácil de citar para los modelos de lenguaje.",
       "On service pages, educational guides, FAQ sections, comparisons and explainer articles. Each piece answers real questions your audience asks in search engines and AI tools, in a format that language models can easily quote and attribute to your brand."),
      ("¿Cómo saben qué preguntas responder?","How do you choose which questions to answer?",
       "Analizamos las búsquedas de tu industria, las preguntas frecuentes de tus clientes y las respuestas que hoy dan los modelos de IA sobre tu categoría. Así detectamos temas donde tu marca no aparece y priorizamos el contenido con más potencial de ser citado.",
       "We analyze searches in your industry, your customers’ frequent questions and the answers AI models currently give about your category. That shows us topics where your brand is missing, and we prioritize the content with the highest potential to be cited.")],
 testi="leo", team=["Antonio Araya","Daniel Mansutti","Luz Muñoz Pereira"],
 ref=(("Funciones de IA y tu sitio web, Google Search Central","AI features and your website, Google Search Central"),"https://developers.google.com/search/docs/appearance/ai-features")),

"design-branding": dict(
 desc=("Branding, diseño gráfico y contenido creativo para redes, anuncios y video, en alianza con Vero Design: más de 200 marcas creadas en más de 7 países.",
       "Branding, graphic design and creative content for social, ads and video, in partnership with Vero Design: 200+ brands created across 7+ countries worldwide."),
 cmp=(("Branding vs. diseño gráfico","Branding vs. graphic design"),("Branding","Branding"),("Diseño gráfico","Graphic design"),
      [("Qué es","What it is","La identidad y percepción de tu marca","Your brand’s identity and perception","Las piezas visuales que la comunican","The visual assets that communicate it"),
       ("Entregables","Deliverables","Logo, paleta, tipografías, manual","Logo, palette, typography, guidelines","Posts, anuncios, presentaciones, video","Posts, ads, decks, video"),
       ("Frecuencia","Frequency","Se define una vez y evoluciona","Defined once, evolves over time","Continua, según campañas","Ongoing, per campaign"),
       ("Impacto","Impact","Diferencia a la marca de la competencia","Sets the brand apart from competitors","Mantiene la marca activa en cada canal","Keeps the brand active on every channel")]),
 defs=[("Identidad visual","Visual identity","Conjunto de elementos gráficos (logo, colores, tipografías, estilo) que hacen reconocible a una marca.","The set of graphic elements (logo, colors, typography, style) that make a brand recognizable."),
       ("Manual de marca","Brand guidelines","Documento con las reglas de uso de la identidad visual para mantener la coherencia en todos los canales.","A document with the rules for using the visual identity to keep it consistent across channels."),
       ("Creatividad de performance","Performance creative","Pieza publicitaria diseñada para testear y mejorar resultados medibles, como clics o ventas.","An ad asset designed to be tested and to improve measurable results, such as clicks or sales.")],
 faq=[("¿Qué incluye un servicio de branding?","What does a branding service include?",
       "Incluye la definición de la identidad visual: logo, paleta de colores, tipografías y reglas de uso reunidas en un manual de marca, además de aplicaciones para redes, web y materiales comerciales. El objetivo es que tu marca se vea coherente y reconocible en todos los canales.",
       "It includes defining the visual identity: logo, color palette, typography and usage rules gathered in brand guidelines, plus applications for social media, web and sales materials. The goal is for your brand to look consistent and recognizable on every channel where customers find it."),
      ("¿Crean contenido para anuncios?","Do you create content for ads?",
       "Sí. Diseñamos creatividades pensadas para performance, con variaciones de mensaje, imagen y formato para testear en Meta, Google, TikTok y otras plataformas. Así el equipo de medios puede identificar rápido qué funciona y escalar las piezas con mejores resultados.",
       "Yes. We design creatives built for performance, with variations in message, image and format to test on Meta, Google, TikTok and other platforms. That way the media team can quickly identify what works and scale the assets that deliver the best results."),
      ("¿Quién hace el diseño?","Who does the design work?",
       "El diseño se desarrolla en alianza con Vero Design, un estudio especializado en identidad visual con más de 200 marcas creadas en más de 7 países. Su trabajo se integra con nuestra estrategia de marketing para que cada pieza, además de verse bien, cumpla un objetivo.",
       "Design is developed in partnership with Vero Design, a studio specialized in visual identity with 200+ brands created across 7+ countries. Their work is integrated with our marketing strategy, so every asset not only looks good but also serves a clear business goal."),
      ("¿También producen video?","Do you also produce video?",
       "Sí. Producimos y editamos video para redes, anuncios y contenido de marca, con foco en storytelling. Adaptamos cada pieza a su formato, como reels, historias o anuncios horizontales, para que funcione en la plataforma donde se va a publicar.",
       "Yes. We produce and edit video for social media, ads and branded content, with a focus on storytelling. We adapt each piece to its format, such as reels, stories or horizontal ads, so it performs well on the platform where it will be published.")],
 testi="manuel", team=["Veronica Guadagno","Nicolás González","Paul Guzmán"], ref=None),

"website": dict(
 desc=("Desarrollo de e-commerce y sitios web en Shopify, WordPress y Wix: rápidos, optimizados para SEO, con medición integrada y diseñados para convertir.",
       "E-commerce and website development on Shopify, WordPress and Wix: fast, SEO-ready, with built-in tracking and designed to turn visitors into customers."),
 cmp=(("Shopify vs. WordPress","Shopify vs. WordPress"),("Shopify","Shopify"),("WordPress","WordPress"),
      [("Ideal para","Best for","Tiendas online que quieren vender rápido","Online stores that want to sell fast","Sitios con mucho contenido y flexibilidad","Content-heavy, flexible sites"),
       ("E-commerce","E-commerce","Nativo y muy estable","Native and very stable","Con WooCommerce","With WooCommerce"),
       ("Mantenimiento","Maintenance","Bajo, la plataforma lo gestiona","Low, the platform handles it","Medio, requiere actualizaciones","Medium, needs updates"),
       ("SEO","SEO","Sólido de base, con apps de apoyo","Solid out of the box, plus apps","Muy flexible con plugins","Highly flexible with plugins")]),
 defs=[("Tasa de conversión","Conversion rate","Porcentaje de visitas que terminan en una compra o en la acción deseada.","The percentage of visits that end in a purchase or the desired action."),
       ("Core Web Vitals","Core Web Vitals","Métricas de Google que miden la velocidad de carga, la respuesta y la estabilidad visual de una página.","Google metrics that measure a page’s loading speed, responsiveness and visual stability."),
       ("Redirección 301","301 redirect","Indicación permanente de que una página cambió de URL; conserva el posicionamiento al migrar un sitio.","A permanent signal that a page moved to a new URL; it preserves rankings during a site migration.")],
 faq=[("¿Qué plataforma me conviene para mi e-commerce?","Which platform is best for my online store?",
       "Depende de tu catálogo, tu presupuesto y tu equipo. Shopify suele ser la mejor opción para vender online con rapidez y estabilidad; WordPress con WooCommerce da más flexibilidad de contenido y Wix funciona bien para sitios simples. Te recomendamos la que mejor se adapte a tu caso.",
       "It depends on your catalog, budget and team. Shopify is usually the best choice for selling online quickly and reliably; WordPress with WooCommerce offers more content flexibility, and Wix works well for simpler sites. We recommend the platform that best fits your case."),
      ("¿El sitio queda optimizado para SEO?","Is the site SEO-ready?",
       "Sí. Cada proyecto incluye una arquitectura limpia, buena velocidad de carga, metadatos, datos estructurados y enlaces internos, además de una base preparada para posicionar en Google y aparecer en respuestas de IA desde el lanzamiento. También entregamos el sitio con Google Search Console y la medición configuradas.",
       "Yes. Every project includes clean architecture, fast load times, metadata, structured data and internal linking, plus a foundation ready to rank on Google and appear in AI-generated answers from the day the site launches. We also hand over the site with Google Search Console and tracking fully configured."),
      ("¿Pueden migrar mi tienda actual?","Can you migrate my current store?",
       "Sí. Migramos productos, clientes y contenido desde otras plataformas, y configuramos redirecciones 301 para no perder el posicionamiento que ya tienes en buscadores. Antes del cambio revisamos todo en un entorno de prueba para evitar caídas en las ventas.",
       "Yes. We migrate products, customers and content from other platforms, and set up 301 redirects so you keep the search rankings you already have. Before switching, we test everything in a staging environment to avoid any drop in sales."),
      ("¿Qué hace que un e-commerce convierta más?","What makes an online store convert better?",
       "Una tienda convierte más cuando carga rápido, se usa bien en el celular, muestra información clara del producto, genera confianza con reseñas y políticas visibles y tiene un checkout simple. Medimos cada paso del proceso de compra para detectar dónde se pierden clientes.",
       "A store converts better when it loads fast, works well on mobile, shows clear product information, builds trust with visible reviews and policies, and has a simple checkout. We measure every step of the purchase process to find where customers drop off.")],
 testi="leo", team=["Juan Jorquera","Veronica Guadagno","Alejandro Lovera"],
 ref=(("Core Web Vitals, web.dev (Google)","Core Web Vitals, web.dev (Google)"),"https://web.dev/articles/vitals")),

"growth-hacking": dict(
 desc=("Growth hacking para captar y retener clientes: experimentos A/B, análisis del funnel y retención con datos. Crecimiento más rápido y medible para tu negocio.",
       "Growth hacking to acquire and retain customers: A/B experiments, funnel analysis and data-driven retention. Faster, measurable growth for your business."),
 cmp=(("Growth hacking vs. marketing tradicional","Growth hacking vs. traditional marketing"),("Growth hacking","Growth hacking"),("Marketing tradicional","Traditional marketing"),
      [("Enfoque","Approach","Experimentos cortos y medibles","Short, measurable experiments","Campañas largas planificadas","Long, pre-planned campaigns"),
       ("Alcance","Scope","Todo el funnel, incluido producto","The whole funnel, including product","Principalmente adquisición","Mainly acquisition"),
       ("Decisiones","Decisions","Basadas en datos de cada prueba","Based on data from each test","Basadas en planificación previa","Based on upfront planning"),
       ("Presupuesto","Budget","Se mueve hacia lo que funciona","Shifts toward what works","Fijo por campaña","Fixed per campaign")]),
 defs=[("Funnel","Funnel","Recorrido del cliente desde que conoce la marca hasta que compra y vuelve a comprar.","The customer journey from first discovering a brand to buying and buying again."),
       ("Prueba A/B","A/B test","Experimento que compara dos versiones de una página, mensaje u oferta para ver cuál funciona mejor.","An experiment that compares two versions of a page, message or offer to see which performs better."),
       ("Retención","Retention","Capacidad de un negocio de mantener a sus clientes activos y comprando en el tiempo.","A business’s ability to keep customers active and buying over time."),
       ("North Star Metric","North Star Metric","Métrica principal que mejor refleja el valor que el cliente recibe y guía todas las decisiones de crecimiento.","The main metric that best reflects the value customers receive and guides every growth decision.")],
 faq=[("¿Qué es el growth hacking?","What is growth hacking?",
       "Es un enfoque de crecimiento basado en experimentos rápidos y medibles a lo largo de todo el funnel: adquisición, activación, retención y recomendación. En lugar de apostar todo a una sola campaña, se prueban muchas ideas pequeñas, se miden con datos y se escalan solo las que funcionan.",
       "It is a growth approach based on fast, measurable experiments across the whole funnel: acquisition, activation, retention and referral. Instead of betting everything on one campaign, many small ideas are tested, measured with data, and only the winners are scaled."),
      ("¿En qué se diferencia del marketing tradicional?","How is it different from traditional marketing?",
       "El marketing tradicional suele planificar campañas largas con un presupuesto fijo. El growth hacking trabaja en ciclos cortos de prueba y aprendizaje, usa datos para decidir dónde invertir y abarca también el producto, el onboarding y la retención, no solo la publicidad.",
       "Traditional marketing usually plans long campaigns with a fixed budget. Growth hacking works in short test-and-learn cycles, uses data to decide where to invest, and also covers product, onboarding and retention, not just advertising. The goal is sustainable growth, not a one-time spike in traffic."),
      ("¿Cuántos experimentos se hacen al mes?","How many experiments run per month?",
       "Depende del tráfico y de los recursos disponibles. Lo importante no es la cantidad, sino que cada experimento tenga una hipótesis clara, una métrica de éxito definida y suficiente volumen de datos para sacar conclusiones confiables antes de escalar. Documentamos cada resultado para que el aprendizaje quede en tu equipo.",
       "It depends on traffic and available resources. What matters is not volume, but that each experiment has a clear hypothesis, a defined success metric and enough data to draw reliable conclusions before anything is scaled. We document every result so the learning stays with your team, even when a test fails."),
      ("¿El growth hacking sirve para empresas B2B?","Does growth hacking work for B2B companies?",
       "Sí. En B2B los experimentos suelen enfocarse en la generación de leads calificados, la conversión de demos, el onboarding y la retención de cuentas. Los ciclos son más largos, por eso ajustamos las métricas y el volumen de cada prueba a la realidad del negocio.",
       "Yes. In B2B, experiments usually focus on qualified lead generation, demo conversion, onboarding and account retention. Sales cycles are longer, so we adjust metrics and test volume to fit the reality of the business and focus on the metrics that predict revenue.")],
 testi="carol", team=["Felipe Ríos Barraza","Nicole Arancibia","Gever Salazar"], ref=None),

"analytics": dict(
 desc=("Analítica de marketing con GA4 y Google Tag Manager: tracking confiable, dashboards claros e insights accionables para invertir mejor en cada canal.",
       "Marketing analytics with GA4 and Google Tag Manager: reliable tracking, clear dashboards and actionable insights to invest smarter in every channel."),
 cmp=(("GA4 vs. datos de las plataformas publicitarias","GA4 vs. ad platform data"),("Google Analytics 4","Google Analytics 4"),("Plataformas publicitarias","Ad platforms"),
      [("Visión","View","Todos los canales en un solo lugar","All channels in one place","Solo su propio canal","Only their own channel"),
       ("Atribución","Attribution","Modelo común para comparar canales","A common model to compare channels","Tiende a atribuirse más ventas","Tends to claim more sales"),
       ("Uso ideal","Best use","Decidir inversión entre canales","Deciding budget across channels","Optimizar dentro de cada plataforma","Optimizing inside each platform"),
       ("Precisión","Accuracy","Depende de la configuración de eventos","Depends on event setup","Condicionada por sus propias ventanas de conversión","Shaped by their own conversion windows")]),
 defs=[("GA4","GA4","Google Analytics 4: la herramienta de Google para medir el comportamiento de los usuarios en sitios web y apps mediante eventos.","Google Analytics 4: Google’s tool for measuring user behavior on websites and apps through events."),
       ("Google Tag Manager","Google Tag Manager","Herramienta que permite gestionar las etiquetas de medición de un sitio sin modificar su código cada vez.","A tool to manage a site’s tracking tags without changing its code every time."),
       ("Atribución","Attribution","Método para asignar el mérito de una venta a los canales y puntos de contacto que participaron en ella.","A method to assign credit for a sale to the channels and touchpoints involved."),
       ("Evento","Event","Cada acción que se mide en un sitio, como una visita, un clic, un formulario enviado o una compra.","Each action measured on a site, such as a page view, click, form submission or purchase.")],
 faq=[("¿Por qué es importante la analítica de marketing?","Why does marketing analytics matter?",
       "Sin datos confiables es imposible saber qué canales generan ventas y cuáles solo consumen presupuesto. La analítica permite invertir mejor, detectar oportunidades, corregir a tiempo y demostrar el retorno del marketing con números claros, en lugar de decidir por intuición.",
       "Without reliable data, it is impossible to know which channels drive sales and which only consume budget. Analytics lets you invest better, spot opportunities, correct course in time and prove marketing’s return with clear numbers, instead of deciding on gut feeling."),
      ("¿Qué herramientas usan?","Which tools do you use?",
       "Trabajamos principalmente con Google Analytics 4, Google Tag Manager, píxeles de plataformas publicitarias y herramientas de dashboards como Looker Studio. Elegimos el stack según tu negocio, tus sistemas actuales y las preguntas que necesitas responder con los datos.",
       "We mainly work with Google Analytics 4, Google Tag Manager, ad platform pixels and dashboard tools such as Looker Studio. We choose the stack based on your business, your existing systems and the questions you need your data to answer."),
      ("¿Pueden revisar mi medición actual?","Can you review my current tracking?",
       "Sí. Hacemos una auditoría de tu medición para detectar conversiones duplicadas, eventos rotos, datos faltantes o configuraciones incorrectas, y te entregamos un plan de corrección priorizado según el impacto que cada problema tiene en tus decisiones. Si lo necesitas, también implementamos las correcciones.",
       "Yes. We audit your tracking to find duplicate conversions, broken events, missing data or incorrect settings, and deliver a fix plan prioritized by the impact each issue has on your business decisions. If needed, we also implement the fixes and validate that every event records correctly."),
      ("¿Por qué los números de GA4 no coinciden con los de Meta o Google Ads?","Why don’t GA4 numbers match Meta or Google Ads?",
       "Cada herramienta usa su propio modelo de atribución, ventanas de conversión y métodos de conteo, por eso los números casi nunca coinciden. No significa que uno esté mal: hay que entender qué mide cada uno y cruzarlos para tomar decisiones con una visión real.",
       "Each tool uses its own attribution model, conversion windows and counting methods, so the numbers rarely match. That doesn’t mean one is wrong: you need to understand what each one measures and combine them to make decisions with a true picture.")],
 testi="leo", team=["Gever Salazar","Alejandro Lovera","Antonio Araya"],
 ref=(("Presentación de Google Analytics 4, Ayuda de Analytics","Introducing Google Analytics 4, Analytics Help"),"https://support.google.com/analytics/answer/10089681")),

"ai-assistants": dict(
 desc=("Asistentes de IA a medida para empresas: automatizan tareas, responden consultas y conectan tus herramientas como CRM, Slack y WhatsApp, con control total.",
       "Custom AI assistants for business: they automate tasks, answer questions and connect your tools such as CRM, Slack and WhatsApp, with full control."),
 cmp=(("Asistente de IA vs. chatbot tradicional","AI assistant vs. traditional chatbot"),("Asistente de IA","AI assistant"),("Chatbot tradicional","Traditional chatbot"),
      [("Cómo responde","How it responds","Entiende lenguaje natural y contexto","Understands natural language and context","Sigue reglas y menús fijos","Follows fixed rules and menus"),
       ("Qué puede hacer","What it can do","Consultar datos, resumir, actuar en herramientas","Query data, summarize, act in tools","Responder preguntas predefinidas","Answer predefined questions"),
       ("Integraciones","Integrations","CRM, Slack, WhatsApp, Google Workspace","CRM, Slack, WhatsApp, Google Workspace","Limitadas","Limited"),
       ("Mejora","Improvement","Se ajusta con uso y documentación","Improves with use and documentation","Requiere reprogramar reglas","Requires rewriting rules")]),
 defs=[("Asistente de IA","AI assistant","Sistema que usa modelos de lenguaje para entender instrucciones, procesar información y ejecutar tareas dentro de tus herramientas.","A system that uses language models to understand instructions, process information and carry out tasks in your tools."),
       ("Integración (API)","Integration (API)","Conexión que permite al asistente leer y escribir datos en otras plataformas, como un CRM o una hoja de cálculo.","A connection that lets the assistant read and write data in other platforms, such as a CRM or spreadsheet."),
       ("Automatización de flujos","Workflow automation","Secuencia de acciones que se ejecuta sola cuando ocurre un evento, como un formulario nuevo o un mensaje entrante.","A sequence of actions that runs automatically when an event happens, such as a new form or an incoming message.")],
 faq=[("¿Qué puede hacer un asistente de IA en mi empresa?","What can an AI assistant do for my company?",
       "Puede responder consultas frecuentes, clasificar y resumir información, preparar reportes, mover datos entre herramientas y apoyar a tu equipo en tareas repetitivas de marketing, ventas, soporte u operaciones. Así las personas se enfocan en el trabajo que realmente requiere criterio humano.",
       "It can answer frequent questions, classify and summarize information, prepare reports, move data between tools and support your team with repetitive tasks in marketing, sales, support or operations. That frees people to focus on the work that truly requires human judgment."),
      ("¿Se conecta con mis herramientas actuales?","Does it connect to my current tools?",
       "Sí. Integramos los asistentes con herramientas como tu CRM, Slack, WhatsApp, Google Workspace y plataformas de analítica, para que trabajen con tus datos reales y en tiempo real, dentro de los flujos que tu equipo ya usa todos los días.",
       "Yes. We integrate assistants with tools such as your CRM, Slack, WhatsApp, Google Workspace and analytics platforms, so they work with your real data in real time, inside the workflows your team already uses every day, without forcing anyone to change tools or learn a new platform."),
      ("¿Mis datos están seguros?","Is my data safe?",
       "Diseñamos cada asistente con permisos definidos, acceso limitado solo a la información necesaria y proveedores que no entrenan modelos con tus datos. Además, documentamos la lógica del sistema para que siempre sepas qué hace, con qué información y bajo qué reglas.",
       "We design each assistant with defined permissions, access limited to only the information it needs and providers that don’t train models on your data. We also document the system’s logic so you always know what it does, with which data and under which rules."),
      ("¿Cuánto tarda en implementarse un asistente?","How long does it take to implement an assistant?",
       "Un primer asistente con un caso de uso concreto puede estar funcionando en pocas semanas. Empezamos por una tarea de alto impacto, medimos el ahorro de tiempo y, con esos resultados, ampliamos a nuevos procesos de forma gradual y controlada.",
       "A first assistant with a specific use case can be running within a few weeks. We start with one high-impact task, measure the time saved and, based on those results, expand to new processes gradually and in a controlled way.")],
 testi="manuel", team=["Juan Jorquera","Alejandro Lovera","Antonio Araya"], ref=None),

"marketing-automation": dict(
 desc=("Automatización de marketing e implementación Martech: CRM, email marketing y flujos automáticos para gestionar contactos, nutrir leads y fidelizar clientes.",
       "Marketing automation and Martech implementation: CRM, email marketing and automated flows to manage contacts, nurture leads and retain customers longer."),
 cmp=(("Gestión automatizada vs. gestión manual","Automated vs. manual management"),("Con automatización","With automation"),("Gestión manual","Manual management"),
      [("Seguimiento de leads","Lead follow-up","Inmediato y constante","Immediate and consistent","Depende de la disponibilidad del equipo","Depends on team availability"),
       ("Personalización","Personalization","Según comportamiento y etapa","Based on behavior and stage","Genérica o limitada","Generic or limited"),
       ("Datos","Data","Centralizados en un CRM","Centralized in a CRM","Dispersos en planillas y correos","Scattered in spreadsheets and inboxes"),
       ("Escalabilidad","Scalability","Crece sin sumar tareas manuales","Scales without extra manual work","Requiere más personas","Requires more people")]),
 defs=[("CRM","CRM","Plataforma que centraliza los datos de contactos y clientes, y el historial de cada interacción comercial.","A platform that centralizes contact and customer data and the history of every sales interaction."),
       ("Lead nurturing","Lead nurturing","Serie de mensajes que acompaña a un posible cliente con información útil hasta que está listo para comprar.","A series of messages that guides a potential customer with useful information until they are ready to buy."),
       ("Flujo automatizado","Automated flow","Secuencia de emails o acciones que se activa sola según el comportamiento de cada contacto.","A sequence of emails or actions triggered automatically by each contact’s behavior."),
       ("Segmentación","Segmentation","División de la base de contactos en grupos con características o comportamientos similares.","Dividing a contact list into groups with similar characteristics or behaviors.")],
 faq=[("¿Qué es la automatización de marketing?","What is marketing automation?",
       "Es el uso de plataformas para ejecutar acciones de marketing de forma automática según el comportamiento de cada contacto, como enviar un email de bienvenida, recordar un carrito abandonado o asignar un lead al equipo comercial. Ahorra tiempo, reduce errores y mejora la relación con el cliente.",
       "It is the use of platforms to run marketing actions automatically based on each contact’s behavior, such as sending a welcome email, reminding an abandoned cart or assigning a lead to sales. It saves time, reduces errors and improves customer relationships."),
      ("¿Qué herramientas implementan?","Which tools do you implement?",
       "Trabajamos con CRM y plataformas de email y automatización como Klaviyo, además de herramientas de integración como n8n, entre otras. Recomendamos el stack según el tamaño de tu empresa, tu presupuesto, tus procesos actuales y las herramientas que tu equipo ya usa.",
       "We work with CRMs and email and automation platforms such as Klaviyo, plus integration tools like n8n, among others. We recommend the stack based on your company size, budget, current processes and the tools your team already uses."),
      ("¿Cuánto tarda una implementación?","How long does an implementation take?",
       "Una implementación básica de CRM o email marketing puede estar lista en pocas semanas. Los proyectos con más integraciones o migraciones de datos toman más tiempo, y siempre se entregan por etapas para que empieces a ver resultados desde el principio.",
       "A basic CRM or email marketing setup can be ready in a few weeks. Projects with more integrations or data migrations take longer, and they are always delivered in stages so you start seeing results from the very beginning."),
      ("¿Qué flujos automáticos conviene tener primero?","Which automated flows should I set up first?",
       "Para un e-commerce, los primeros suelen ser bienvenida, carrito abandonado, post compra y reactivación de clientes inactivos. En B2B, la calificación y asignación de leads y el nurturing por email. Son los que más impacto tienen con menos esfuerzo.",
       "For e-commerce, the first ones are usually welcome, abandoned cart, post-purchase and win-back for inactive customers. In B2B, lead scoring and routing plus email nurturing. These deliver the most impact for the least effort, and they create a solid base for more advanced automations later.")],
 testi="manuel", team=["Juan Jorquera","María Silvia Andueza","Antonio Araya"], ref=None),
}
