# Contenido de las páginas de servicio (EN por defecto, ES alternativo)
S = [
dict(slug="consulting", n="01",
 name=("Estrategia de marketing","Marketing strategy"),
 title=("Consultoría y estrategia de marketing digital | FL Marketing","Digital Marketing Strategy & Consulting | FL Marketing"),
 desc=("Consultoría de marketing digital para definir objetivos, canales y presupuesto con metas medibles. Estrategia senior para marcas en EE. UU. y Latinoamérica.",
       "Digital marketing consulting to define goals, channels and budget with measurable targets. Senior strategy for brands in the US and Latin America."),
 h1=("Estrategia y consultoría de marketing digital","Digital marketing strategy &amp; consulting"),
 lead=("La consultoría de marketing digital define qué hacer, en qué canales y con qué presupuesto para que tu marca crezca de forma medible. Analizamos tu situación actual, detectamos oportunidades y construimos un plan con metas claras por etapa, que tu equipo o el nuestro puede ejecutar.",
       "Digital marketing consulting defines what to do, on which channels and with what budget so your brand grows in a measurable way. We analyze your current situation, find opportunities and build a plan with clear targets for each stage, ready for your team or ours to execute."),
 inc=[("Diagnóstico de marketing","Marketing audit","Revisión de cuentas, canales, datos y competencia.","Review of accounts, channels, data and competitors."),
      ("Plan estratégico","Strategic plan","Objetivos, canales, mensajes y presupuesto por etapa.","Goals, channels, messaging and budget by stage."),
      ("Definición de KPIs","KPI framework","Métricas conectadas a ventas, no a vanidad.","Metrics tied to revenue, not vanity."),
      ("Acompañamiento","Ongoing advisory","Sesiones periódicas para revisar avances y ajustar.","Regular sessions to review progress and adjust.")],
 who=[("Marcas que invierten en marketing sin una estrategia clara.","Brands investing in marketing without a clear strategy."),
      ("Equipos internos que necesitan dirección senior.","In-house teams that need senior direction."),
      ("Empresas que entran a un nuevo mercado o canal.","Companies entering a new market or channel.")],
 faq=[("¿Qué incluye una consultoría de marketing digital?","What does digital marketing consulting include?",
       "Incluye un diagnóstico de tus canales y datos, un plan estratégico con objetivos, canales y presupuesto, la definición de KPIs y sesiones de seguimiento. El resultado es una hoja de ruta concreta que tu equipo puede ejecutar o que podemos ejecutar nosotros.",
       "It includes an audit of your channels and data, a strategic plan with goals, channels and budget, a KPI framework and follow-up sessions. The result is a concrete roadmap your team can execute, or that we can execute for you."),
      ("¿Cuánto dura una consultoría?","How long does a consulting engagement take?",
       "El diagnóstico y el plan inicial suelen tomar entre dos y cuatro semanas, según el tamaño de la cuenta. Después, el acompañamiento puede ser mensual o por proyecto, dependiendo de lo que necesite tu equipo.",
       "The audit and initial plan usually take two to four weeks, depending on account size. After that, advisory can be monthly or per project, depending on what your team needs."),
      ("¿Trabajan con equipos internos?","Do you work with in-house teams?",
       "Sí. Podemos liderar la estrategia y dejar la ejecución a tu equipo, trabajar en conjunto o hacernos cargo de todo. La idea es que tu equipo gane claridad y autonomía, no dependencia.",
       "Yes. We can lead strategy and leave execution to your team, work side by side, or take care of everything. The goal is for your team to gain clarity and autonomy, not dependency.")],
 rel=["performance-marketing","analytics","growth-hacking"]),

dict(slug="performance-marketing", n="02",
 name=("Performance Marketing","Performance Marketing"),
 title=("Agencia de performance marketing | FL Marketing Management","Performance Marketing Agency | FL Marketing Management"),
 desc=("Campañas de performance marketing en Google, Meta, TikTok y LinkedIn enfocadas en ROAS, eficiencia y crecimiento medible.",
       "Performance marketing campaigns on Google, Meta, TikTok and LinkedIn focused on ROAS, efficiency and measurable growth."),
 h1=("Performance marketing enfocado en ventas","Performance marketing built around revenue"),
 lead=("El performance marketing es publicidad digital que se paga y se optimiza según resultados: ventas, leads o retorno sobre la inversión. Diseñamos, ejecutamos y optimizamos campañas en Google, Meta, TikTok y LinkedIn con objetivos claros, datos limpios y pruebas constantes para escalar lo que funciona.",
       "Performance marketing is digital advertising that is paid for and optimized based on results: sales, leads or return on ad spend. We design, run and optimize campaigns on Google, Meta, TikTok and LinkedIn with clear goals, clean data and constant testing to scale what works."),
 inc=[("Estrategia de medios","Media strategy","Canales, audiencias y presupuesto según tus objetivos.","Channels, audiences and budget based on your goals."),
      ("Gestión de campañas","Campaign management","Google Ads, Meta, TikTok, LinkedIn y YouTube.","Google Ads, Meta, TikTok, LinkedIn and YouTube."),
      ("Testeo creativo","Creative testing","Pruebas continuas de anuncios, mensajes y formatos.","Ongoing tests of ads, messaging and formats."),
      ("Optimización y reportes","Optimization &amp; reporting","Ajustes semanales y reportes claros de ROAS y CPA.","Weekly adjustments and clear ROAS and CPA reports.")],
 who=[("Marcas que quieren escalar la adquisición de forma rentable.","Brands that want to scale acquisition profitably."),
      ("Equipos que necesitan orden y claridad en sus cuentas.","Teams that need structure and clarity in their ad accounts."),
      ("E-commerce y B2B enfocados en resultados, no en likes.","E-commerce and B2B businesses focused on results, not likes.")],
 faq=[("¿Qué es el performance marketing?","What is performance marketing?",
       "Es un modelo de publicidad digital donde cada decisión se toma según resultados medibles, como ventas, leads o ROAS. Las campañas se optimizan de forma continua con datos, pruebas y ajustes de presupuesto para mejorar el retorno de cada peso invertido.",
       "It is a digital advertising model where every decision is based on measurable results, such as sales, leads or ROAS. Campaigns are continuously optimized with data, tests and budget adjustments to improve the return on every dollar spent."),
      ("¿En qué plataformas trabajan?","Which platforms do you work with?",
       "Gestionamos campañas en Google Ads, Meta (Facebook e Instagram), TikTok, LinkedIn y YouTube. Elegimos la combinación según tu público, tu producto y tu objetivo de negocio, no por moda.",
       "We manage campaigns on Google Ads, Meta (Facebook and Instagram), TikTok, LinkedIn and YouTube. We choose the mix based on your audience, product and business goal, not on trends."),
      ("¿Cuándo se ven resultados?","When will I see results?",
       "Las primeras señales aparecen en las primeras semanas, pero una cuenta suele estabilizarse entre uno y tres meses, cuando los algoritmos aprenden y las pruebas muestran qué funciona. Desde el inicio reportamos avances con métricas claras.",
       "Early signals appear within the first weeks, but an account usually stabilizes within one to three months, once algorithms learn and tests show what works. We report progress with clear metrics from day one.")],
 rel=["analytics","seo-aeo","growth-hacking"]),

dict(slug="seo-aeo", n="03",
 name=("SEO + AEO","SEO + AEO"),
 title=("Servicios de SEO y AEO para Google y la IA | FL Marketing","SEO &amp; AEO Services for Google and AI Search | FL Marketing"),
 desc=("SEO técnico y de contenido más AEO para que tu marca aparezca en Google y en respuestas de ChatGPT, Gemini y Perplexity.",
       "Technical and content SEO plus AEO so your brand shows up on Google and in answers from ChatGPT, Gemini and Perplexity."),
 h1=("SEO y AEO: visibilidad en Google y en la IA","SEO &amp; AEO: visibility on Google and in AI search"),
 lead=("El SEO mejora tu posicionamiento en buscadores como Google; el AEO (Answer Engine Optimization) prepara tu contenido para que asistentes de IA como ChatGPT, Gemini y Perplexity lo entiendan, lo citen y lo recomienden. Trabajamos ambos juntos para que tu marca sea encontrada y elegida.",
       "SEO improves your ranking on search engines like Google; AEO (Answer Engine Optimization) prepares your content so AI assistants like ChatGPT, Gemini and Perplexity can understand, cite and recommend it. We work on both together so your brand gets found and chosen."),
 inc=[("SEO técnico","Technical SEO","Velocidad, indexación, estructura y datos estructurados.","Speed, indexing, site structure and structured data."),
      ("Investigación de palabras clave","Keyword research","Búsquedas reales según intención de compra.","Real searches mapped to buying intent."),
      ("Optimización on-page","On-page optimization","Títulos, contenido y enlaces internos.","Titles, content and internal linking."),
      ("Optimización para IA","AI search optimization","Contenido pensado para ser citado por LLMs.","Content built to be cited by LLMs.")],
 who=[("Empresas B2B y B2C con productos o servicios complejos.","B2B and B2C companies with complex products or services."),
      ("Marcas que dependen demasiado de la publicidad pagada.","Brands that rely too heavily on paid ads."),
      ("Negocios que quieren aparecer en respuestas de IA.","Businesses that want to appear in AI answers.")],
 faq=[("¿Qué diferencia hay entre SEO y AEO?","What is the difference between SEO and AEO?",
       "El SEO busca que tu sitio aparezca en los resultados de Google y otros buscadores. El AEO busca que asistentes de IA como ChatGPT o Gemini usen tu contenido como fuente en sus respuestas. Se complementan: el SEO atrae tráfico y el AEO construye autoridad en la IA.",
       "SEO aims to get your site into Google and other search results. AEO aims to get AI assistants like ChatGPT or Gemini to use your content as a source in their answers. They complement each other: SEO drives traffic and AEO builds authority in AI search."),
      ("¿Cuánto tarda el SEO en dar resultados?","How long does SEO take to work?",
       "Las mejoras técnicas pueden notarse en semanas, pero el posicionamiento orgánico sólido suele tomar entre tres y seis meses, según la competencia y el estado del sitio. Es una inversión acumulativa: lo que se construye sigue rindiendo en el tiempo.",
       "Technical fixes can show impact within weeks, but solid organic rankings usually take three to six months, depending on competition and the site’s starting point. It is a compounding investment: what you build keeps paying off over time."),
      ("¿Cómo se mide la visibilidad en la IA?","How do you measure AI visibility?",
       "Revisamos con qué frecuencia los principales modelos de IA mencionan tu marca frente a la competencia en preguntas relevantes de tu industria. Con eso priorizamos qué contenido crear o mejorar para ganar presencia en esas respuestas.",
       "We track how often major AI models mention your brand versus competitors for relevant questions in your industry. That tells us which content to create or improve to gain presence in those answers.")],
 rel=["aeo-content","analytics","website"]),

dict(slug="aeo-content", n="04",
 name=("Contenido AEO","AEO content"),
 title=("Contenido AEO para búsqueda con IA y LLMs | FL Marketing","AEO Content for AI Search &amp; LLM Visibility | FL Marketing"),
 desc=("Contenido AEO diseñado para que ChatGPT, Gemini y Perplexity entiendan, citen y recomienden tu marca.",
       "AEO content designed so ChatGPT, Gemini and Perplexity understand, cite and recommend your brand."),
 h1=("Contenido AEO para aparecer en respuestas de IA","AEO content that gets cited by AI"),
 lead=("El contenido AEO es contenido estructurado para que los motores de respuesta basados en IA puedan entenderlo, resumirlo y recomendar tu marca. Creamos páginas, guías y preguntas frecuentes con definiciones claras, respuestas directas y datos verificables, pensadas tanto para personas como para modelos de lenguaje.",
       "AEO content is content structured so AI-powered answer engines can understand it, summarize it and recommend your brand. We create pages, guides and FAQs with clear definitions, direct answers and verifiable facts, written for both people and language models."),
 inc=[("Estrategia de temas","Topic strategy","Preguntas reales que hace tu público a la IA.","Real questions your audience asks AI tools."),
      ("Contenido estructurado","Structured content","Respuestas directas, definiciones y listas claras.","Direct answers, definitions and clear lists."),
      ("Optimización semántica","Semantic optimization","Entidades y contexto que la IA puede asociar a tu marca.","Entities and context AI can link to your brand."),
      ("Señales de autoridad","Authority signals","Autoría, fuentes y consistencia (E-E-A-T).","Authorship, sources and consistency (E-E-A-T).")],
 who=[("Marcas que quieren presencia en respuestas generadas por IA.","Brands that want presence in AI-generated answers."),
      ("Empresas que apuestan por relevancia en búsqueda a largo plazo.","Companies investing in long-term search relevance."),
      ("Negocios en mercados digitales muy competidos.","Businesses in highly competitive digital markets.")],
 faq=[("¿Qué es el contenido AEO?","What is AEO content?",
       "Es contenido escrito y estructurado para que asistentes de IA como ChatGPT, Gemini o Perplexity lo entiendan y lo usen como fuente. Usa respuestas directas, definiciones claras, datos verificables y una estructura lógica que facilita que los modelos lo citen correctamente.",
       "It is content written and structured so AI assistants like ChatGPT, Gemini or Perplexity can understand it and use it as a source. It relies on direct answers, clear definitions, verifiable facts and a logical structure that makes it easy for models to cite it accurately."),
      ("¿El contenido AEO reemplaza al SEO?","Does AEO content replace SEO?",
       "No. El contenido AEO se apoya en las bases del SEO, como una buena estructura, velocidad y enlaces internos. Lo ideal es trabajarlos juntos para tener visibilidad tanto en los resultados de Google como en las respuestas de la IA.",
       "No. AEO content builds on SEO foundations such as good structure, speed and internal linking. Ideally, both are worked together to gain visibility in Google results and in AI answers."),
      ("¿Dónde se aplica el contenido AEO?","Where is AEO content used?",
       "En páginas de servicio, guías educativas, secciones de preguntas frecuentes, comparativas y artículos explicativos. Cada pieza responde preguntas reales que tu público hace en buscadores y en herramientas de IA.",
       "On service pages, educational guides, FAQ sections, comparisons and explainer articles. Each piece answers real questions your audience asks in search engines and AI tools.")],
 rel=["seo-aeo","design-branding","consulting"]),

dict(slug="design-branding", n="05",
 name=("Contenido creativo y multimedia","Creative &amp; multimedia content"),
 title=("Diseño gráfico, branding y contenido creativo | FL Marketing","Graphic Design, Branding &amp; Creative Content | FL Marketing"),
 desc=("Identidad visual, diseño gráfico y contenido para redes y anuncios, en alianza con Vero Design. Más de 200 marcas creadas en 7 países.",
       "Visual identity, graphic design and content for social and ads, in partnership with Vero Design. 200+ brands created across 7+ countries."),
 h1=("Branding, diseño y contenido creativo","Branding, design &amp; creative content"),
 lead=("El contenido creativo y el branding le dan a tu marca una identidad visual coherente y piezas que comunican con claridad en cada canal. En alianza con Vero Design, con más de 200 marcas creadas en más de 7 países, creamos identidades, piezas para redes, anuncios y video con criterio estratégico.",
       "Creative content and branding give your brand a consistent visual identity and assets that communicate clearly on every channel. In partnership with Vero Design, with 200+ brands created across 7+ countries, we create identities, social content, ads and video with a strategic approach."),
 inc=[("Identidad visual","Visual identity","Logo, paleta, tipografías y sistema de marca.","Logo, palette, typography and brand system."),
      ("Contenido para redes","Social content","Piezas y calendarios para redes sociales.","Assets and calendars for social media."),
      ("Creatividades para anuncios","Ad creatives","Formatos pensados para performance.","Formats built for performance."),
      ("Video y multimedia","Video &amp; multimedia","Piezas en movimiento para campañas y marca.","Motion assets for campaigns and brand.")],
 who=[("Marcas nuevas que necesitan una identidad sólida.","New brands that need a solid identity."),
      ("Empresas con una imagen inconsistente entre canales.","Companies with an inconsistent image across channels."),
      ("Equipos de performance que necesitan creatividades para testear.","Performance teams that need creatives to test.")],
 faq=[("¿Qué incluye un servicio de branding?","What does a branding service include?",
       "Incluye la definición de la identidad visual: logo, paleta de colores, tipografías y reglas de uso, además de aplicaciones para redes, web y materiales comerciales. El objetivo es que tu marca se vea coherente y reconocible en todos los canales.",
       "It includes defining the visual identity: logo, color palette, typography and usage rules, plus applications for social media, web and sales materials. The goal is for your brand to look consistent and recognizable across every channel."),
      ("¿Crean contenido para anuncios?","Do you create content for ads?",
       "Sí. Diseñamos creatividades pensadas para performance, con variaciones de mensaje y formato para testear en Meta, Google, TikTok y otras plataformas. Así el equipo de medios puede escalar lo que mejor funciona.",
       "Yes. We design creatives built for performance, with message and format variations to test on Meta, Google, TikTok and other platforms. That way the media team can scale what works best."),
      ("¿Quién hace el diseño?","Who does the design work?",
       "El diseño se desarrolla en alianza con Vero Design, un estudio especializado en identidad visual con más de 200 marcas creadas en más de 7 países, integrado con nuestra estrategia de marketing.",
       "Design is developed in partnership with Vero Design, a studio specialized in visual identity with 200+ brands created across 7+ countries, integrated with our marketing strategy.")],
 rel=["performance-marketing","aeo-content","website"]),

dict(slug="website", n="06",
 name=("E-commerce y sitios web","E-commerce &amp; websites"),
 title=("Desarrollo de e-commerce y sitios web | FL Marketing","E-commerce &amp; Website Development | FL Marketing"),
 desc=("Tiendas online y sitios web en Shopify, Wix y WordPress: rápidos, optimizados para SEO y diseñados para convertir.",
       "Online stores and websites on Shopify, Wix and WordPress: fast, SEO-ready and designed to convert."),
 h1=("E-commerce y sitios web que venden","E-commerce stores and websites that sell"),
 lead=("Un buen sitio web o e-commerce no es solo diseño: debe ser rápido, fácil de usar, estar optimizado para SEO y estar pensado para convertir visitas en clientes. Desarrollamos tiendas y sitios en Shopify, Wix y WordPress conectados a tu estrategia de marketing y a tu medición.",
       "A good website or online store is more than design: it must be fast, easy to use, SEO-ready and built to turn visitors into customers. We build stores and websites on Shopify, Wix and WordPress, connected to your marketing strategy and measurement."),
 inc=[("Diseño y UX","Design &amp; UX","Estructura clara del descubrimiento a la compra.","Clear structure from discovery to purchase."),
      ("Desarrollo a medida","Custom development","Temas y funcionalidades según tu negocio.","Themes and features built for your business."),
      ("Bases de SEO","SEO foundations","Arquitectura, velocidad y datos estructurados.","Architecture, speed and structured data."),
      ("Medición integrada","Built-in tracking","GA4, píxeles y conversiones desde el día uno.","GA4, pixels and conversions from day one.")],
 who=[("Marcas que lanzan su primera tienda online.","Brands launching their first online store."),
      ("Negocios que migran desde otra plataforma.","Businesses migrating from another platform."),
      ("Empresas con un sitio lento o que no convierte.","Companies with a slow site or one that doesn’t convert.")],
 faq=[("¿Qué plataforma me conviene para mi e-commerce?","Which platform is best for my online store?",
       "Depende de tu catálogo, tu presupuesto y tu equipo. Shopify suele ser la mejor opción para vender online con rapidez y estabilidad; WordPress da más flexibilidad de contenido y Wix funciona bien para sitios simples. Te recomendamos la que mejor se adapte a tu caso.",
       "It depends on your catalog, budget and team. Shopify is usually the best choice for selling online quickly and reliably; WordPress offers more content flexibility and Wix works well for simpler sites. We recommend the one that fits your case."),
      ("¿El sitio queda optimizado para SEO?","Is the site SEO-ready?",
       "Sí. Cada proyecto incluye una arquitectura limpia, buena velocidad de carga, metadatos, datos estructurados y una base preparada para posicionar en Google y aparecer en respuestas de IA.",
       "Yes. Every project includes clean architecture, fast load times, metadata, structured data and a foundation ready to rank on Google and appear in AI answers."),
      ("¿Pueden migrar mi tienda actual?","Can you migrate my current store?",
       "Sí. Migramos productos, clientes y contenido desde otras plataformas, cuidando las redirecciones para no perder el posicionamiento que ya tienes en buscadores.",
       "Yes. We migrate products, customers and content from other platforms, handling redirects so you keep the search rankings you already have.")],
 rel=["seo-aeo","analytics","performance-marketing"]),

dict(slug="growth-hacking", n="07",
 name=("Growth Hacking","Growth Hacking"),
 title=("Growth hacking: adquisición y retención con datos | FL Marketing","Growth Hacking: Data-Driven Acquisition &amp; Retention | FL Marketing"),
 desc=("Estrategias de growth hacking para captar y retener clientes con experimentación constante, datos y herramientas digitales.",
       "Growth hacking strategies to acquire and retain customers through constant experimentation, data and digital tools."),
 h1=("Growth hacking con datos y experimentación","Growth hacking powered by data and experimentation"),
 lead=("El growth hacking es un método para crecer más rápido probando ideas de adquisición, activación y retención de forma sistemática. Diseñamos experimentos, medimos su impacto y escalamos solo lo que demuestra resultados, combinando marketing, producto y datos en un mismo proceso.",
       "Growth hacking is a method to grow faster by systematically testing acquisition, activation and retention ideas. We design experiments, measure their impact and scale only what proves results, combining marketing, product and data in a single process."),
 inc=[("Mapa del funnel","Funnel mapping","Dónde se pierden clientes y por qué.","Where customers drop off and why."),
      ("Backlog de experimentos","Experiment backlog","Ideas priorizadas por impacto y esfuerzo.","Ideas prioritized by impact and effort."),
      ("Pruebas A/B","A/B testing","Landings, mensajes, ofertas y flujos.","Landing pages, messaging, offers and flows."),
      ("Retención","Retention","Onboarding, email y reactivación de clientes.","Onboarding, email and customer reactivation.")],
 who=[("Startups y empresas digitales en etapa de crecimiento.","Startups and digital companies in growth stage."),
      ("Negocios con tráfico pero baja conversión.","Businesses with traffic but low conversion."),
      ("Marcas que quieren mejorar la retención de clientes.","Brands that want to improve customer retention.")],
 faq=[("¿Qué es el growth hacking?","What is growth hacking?",
       "Es un enfoque de crecimiento basado en experimentos rápidos y medibles a lo largo de todo el funnel: adquisición, activación, retención y recomendación. En lugar de apostar todo a una sola campaña, se prueban muchas ideas pequeñas y se escalan las que funcionan.",
       "It is a growth approach based on fast, measurable experiments across the whole funnel: acquisition, activation, retention and referral. Instead of betting everything on one campaign, many small ideas are tested and the winners are scaled."),
      ("¿En qué se diferencia del marketing tradicional?","How is it different from traditional marketing?",
       "El marketing tradicional suele planificar campañas largas con un presupuesto fijo. El growth hacking trabaja en ciclos cortos de prueba y aprendizaje, usa datos para decidir y abarca también producto y retención, no solo la publicidad.",
       "Traditional marketing usually plans long campaigns with a fixed budget. Growth hacking works in short test-and-learn cycles, uses data to decide and also covers product and retention, not just advertising."),
      ("¿Cuántos experimentos se hacen al mes?","How many experiments run per month?",
       "Depende del tráfico y de los recursos disponibles. Lo importante no es la cantidad, sino que cada experimento tenga una hipótesis clara, una métrica de éxito y suficiente volumen para sacar conclusiones confiables.",
       "It depends on traffic and available resources. What matters is not volume, but that each experiment has a clear hypothesis, a success metric and enough data to draw reliable conclusions.")],
 rel=["analytics","performance-marketing","marketing-automation"]),

dict(slug="analytics", n="08",
 name=("Analítica e insights","Analytics &amp; insights"),
 title=("Analítica de marketing y dashboards | FL Marketing","Marketing Analytics &amp; Dashboards | FL Marketing"),
 desc=("Medición con GA4 y GTM, dashboards y análisis de datos para medir cada acción de marketing y tomar mejores decisiones.",
       "GA4 and GTM tracking, dashboards and data analysis to measure every marketing action and make better decisions."),
 h1=("Analítica de marketing para decidir con datos","Marketing analytics to make data-driven decisions"),
 lead=("La analítica de marketing mide el impacto real de cada canal y cada campaña para que tomes decisiones con datos confiables. Configuramos la medición con GA4 y Google Tag Manager, construimos dashboards claros y convertimos los números en recomendaciones concretas para crecer.",
       "Marketing analytics measures the real impact of every channel and campaign so you can make decisions with reliable data. We set up tracking with GA4 and Google Tag Manager, build clear dashboards and turn numbers into concrete recommendations for growth."),
 inc=[("Implementación de tracking","Tracking setup","GA4, GTM, píxeles y conversiones.","GA4, GTM, pixels and conversions."),
      ("Auditoría de datos","Data audit","Detectamos errores, duplicados y vacíos.","We find errors, duplicates and gaps."),
      ("Dashboards","Dashboards","Reportes automáticos y fáciles de leer.","Automated, easy-to-read reports."),
      ("Insights accionables","Actionable insights","Qué hacer con los datos, no solo qué pasó.","What to do with the data, not just what happened.")],
 who=[("Empresas que no confían en sus datos actuales.","Companies that don’t trust their current data."),
      ("Equipos que invierten en medios sin saber qué funciona.","Teams spending on media without knowing what works."),
      ("Directivos que necesitan reportes claros.","Leaders who need clear reporting.")],
 faq=[("¿Por qué es importante la analítica de marketing?","Why does marketing analytics matter?",
       "Sin datos confiables es imposible saber qué canales generan ventas y cuáles solo consumen presupuesto. La analítica permite invertir mejor, detectar oportunidades y corregir a tiempo, en lugar de decidir por intuición.",
       "Without reliable data, it is impossible to know which channels drive sales and which only consume budget. Analytics lets you invest better, spot opportunities and correct course in time, instead of deciding on gut feeling."),
      ("¿Qué herramientas usan?","Which tools do you use?",
       "Trabajamos principalmente con Google Analytics 4, Google Tag Manager, píxeles de plataformas publicitarias y herramientas de dashboards como Looker Studio. Elegimos el stack según tu negocio y tus sistemas actuales.",
       "We mainly work with Google Analytics 4, Google Tag Manager, ad platform pixels and dashboard tools such as Looker Studio. We choose the stack based on your business and existing systems."),
      ("¿Pueden revisar mi medición actual?","Can you review my current tracking?",
       "Sí. Hacemos una auditoría de tu medición para detectar conversiones duplicadas, eventos rotos o datos faltantes, y te entregamos un plan de corrección priorizado.",
       "Yes. We audit your tracking to find duplicate conversions, broken events or missing data, and deliver a prioritized fix plan.")],
 rel=["performance-marketing","growth-hacking","consulting"]),

dict(slug="ai-assistants", n="09",
 name=("Asistentes de IA","AI assistants"),
 title=("Asistentes de IA a medida para empresas | FL Marketing","Custom AI Assistants for Business | FL Marketing"),
 desc=("Asistentes de IA a medida que automatizan tareas, apoyan a tu equipo y escalan operaciones con integraciones a tus herramientas.",
       "Custom AI assistants that automate tasks, support your team and scale operations, integrated with your tools."),
 h1=("Asistentes de IA a medida para tu negocio","Custom AI assistants for your business"),
 lead=("Un asistente de IA es un sistema que realiza tareas repetitivas, procesa información y apoya a tu equipo usando modelos de inteligencia artificial conectados a tus herramientas. Diseñamos asistentes a medida para marketing, ventas, soporte y operaciones, con lógica clara y control total.",
       "An AI assistant is a system that handles repetitive tasks, processes information and supports your team using AI models connected to your tools. We design custom assistants for marketing, sales, support and operations, with clear logic and full control."),
 inc=[("Asistentes a medida","Custom assistants","Diseñados según tus procesos y reglas de negocio.","Designed around your processes and business rules."),
      ("Integraciones","Integrations","CRM, Slack, WhatsApp, Google Workspace y más.","CRM, Slack, WhatsApp, Google Workspace and more."),
      ("Procesamiento de datos","Data processing","Clasificación, resúmenes y enriquecimiento.","Classification, summaries and enrichment."),
      ("Monitoreo","Monitoring","Documentación y mejoras continuas.","Documentation and continuous improvement.")],
 who=[("Equipos que quieren automatizar sin perder control.","Teams that want to automate without losing control."),
      ("Negocios con alto volumen de consultas u operaciones.","Businesses with high inquiry or operational volume."),
      ("Empresas que buscan eficiencia sin sumar personal.","Companies seeking efficiency without adding headcount.")],
 faq=[("¿Qué puede hacer un asistente de IA en mi empresa?","What can an AI assistant do for my company?",
       "Puede responder consultas frecuentes, clasificar y resumir información, preparar reportes, mover datos entre herramientas y apoyar a tu equipo en tareas repetitivas. Así las personas se enfocan en el trabajo de mayor valor.",
       "It can answer frequent questions, classify and summarize information, prepare reports, move data between tools and support your team with repetitive tasks. That frees people to focus on higher-value work."),
      ("¿Se conecta con mis herramientas actuales?","Does it connect to my current tools?",
       "Sí. Integramos los asistentes con herramientas como tu CRM, Slack, WhatsApp, Google Workspace y plataformas de analítica, para que trabajen con tus datos reales y en tiempo real.",
       "Yes. We integrate assistants with tools such as your CRM, Slack, WhatsApp, Google Workspace and analytics platforms, so they work with your real data in real time."),
      ("¿Mis datos están seguros?","Is my data safe?",
       "Diseñamos cada asistente con permisos definidos, acceso limitado a la información necesaria y proveedores que no entrenan modelos con tus datos. Documentamos la lógica para que siempre sepas qué hace el sistema.",
       "We design each assistant with defined permissions, access limited to the information it needs and providers that don’t train models on your data. We document the logic so you always know what the system does.")],
 rel=["marketing-automation","analytics","aeo-content"]),

dict(slug="marketing-automation", n="10",
 name=("Automatización y Martech","Automation &amp; Martech"),
 title=("Automatización de marketing e implementación Martech | FL Marketing","Marketing Automation &amp; Martech Implementation | FL Marketing"),
 desc=("Implementamos CRM, email marketing y automatizaciones para gestionar contactos, nutrir leads y fidelizar clientes.",
       "We implement CRM, email marketing and automations to manage contacts, nurture leads and retain customers."),
 h1=("Automatización de marketing e implementación Martech","Marketing automation &amp; Martech implementation"),
 lead=("La automatización de marketing usa plataformas como CRM y email marketing para gestionar contactos, nutrir leads y fidelizar clientes sin tareas manuales. Elegimos, implementamos y conectamos las herramientas Martech que tu negocio necesita, con flujos automáticos que mejoran la eficiencia y la experiencia del cliente.",
       "Marketing automation uses platforms such as CRM and email marketing to manage contacts, nurture leads and retain customers without manual work. We select, implement and connect the Martech tools your business needs, with automated flows that improve efficiency and customer experience."),
 inc=[("Implementación de CRM","CRM implementation","Configuración, pipeline y migración de datos.","Setup, pipeline and data migration."),
      ("Email marketing","Email marketing","Flujos de bienvenida, carrito abandonado y más.","Welcome, abandoned cart and more flows."),
      ("Automatizaciones","Automations","Procesos conectados entre tus herramientas.","Connected processes across your tools."),
      ("Segmentación","Segmentation","Mensajes según comportamiento y etapa.","Messages based on behavior and stage.")],
 who=[("Empresas que gestionan contactos en planillas.","Companies managing contacts in spreadsheets."),
      ("E-commerce que quiere aumentar la recompra.","E-commerce brands that want more repeat purchases."),
      ("Equipos comerciales que necesitan leads más calificados.","Sales teams that need better-qualified leads.")],
 faq=[("¿Qué es la automatización de marketing?","What is marketing automation?",
       "Es el uso de plataformas para ejecutar acciones de marketing de forma automática según el comportamiento de cada contacto, como enviar un email de bienvenida, recordar un carrito abandonado o asignar un lead al equipo comercial. Ahorra tiempo y mejora la relación con el cliente.",
       "It is the use of platforms to run marketing actions automatically based on each contact’s behavior, such as sending a welcome email, reminding an abandoned cart or assigning a lead to sales. It saves time and improves customer relationships."),
      ("¿Qué herramientas implementan?","Which tools do you implement?",
       "Trabajamos con CRM y plataformas de email y automatización como Klaviyo y herramientas de integración como n8n, entre otras. Recomendamos el stack según tu tamaño, tu presupuesto y tus procesos.",
       "We work with CRMs and email and automation platforms such as Klaviyo and integration tools like n8n, among others. We recommend the stack based on your size, budget and processes."),
      ("¿Cuánto tarda una implementación?","How long does an implementation take?",
       "Una implementación básica de CRM o email marketing puede estar lista en pocas semanas. Proyectos con más integraciones o migraciones de datos toman más tiempo, y siempre se entregan por etapas para que empieces a ver valor pronto.",
       "A basic CRM or email marketing setup can be ready in a few weeks. Projects with more integrations or data migrations take longer, and are always delivered in stages so you see value early.")],
 rel=["ai-assistants","growth-hacking","analytics"]),
]
