"""Ajustes SEO (parte A): consulting, performance-marketing, seo-aeo, aeo-content, design-branding. Tuplas (ES, EN)."""

SEO = {
    'consulting': dict(
        kw=('estrategia de marketing digital', 'digital marketing strategy'),
        title=('Estrategia de marketing digital y consultoría | FL Marketing',
               'Digital Marketing Strategy &amp; Consulting | FL Marketing'),
        desc=('Estrategia de marketing digital y consultoría senior para definir objetivos, canales y presupuesto con metas medibles. Conversemos sobre tu próximo paso.',
              'Digital marketing strategy and senior consulting to set goals, channels and budget with measurable targets for US and LATAM brands. Plan your next step.'),
        lead=('Una estrategia de marketing digital define qué hacer, en qué canales y con qué presupuesto para que tu marca crezca de forma medible. En nuestra consultoría analizamos tu situación actual, detectamos oportunidades y construimos un plan con metas claras por etapa, listo para que lo ejecute tu equipo o el nuestro.',
              'A digital marketing strategy defines what to do, on which channels and with what budget so your brand grows in a measurable way. In our consulting work, we analyze your current situation, find opportunities and build a plan with clear targets for each stage, ready for your team or ours to execute.'),
        h1=('Estrategia de marketing digital y consultoría',
            'Digital marketing strategy &amp; consulting'),
        h_inc=('¿Qué incluye nuestro servicio de estrategia de marketing digital?',
               'What does our digital marketing strategy service include?'),
        h_faq=('Estrategia de marketing digital: preguntas frecuentes',
               'Digital marketing strategy: frequently asked questions'),
        guide=dict(
            label=('Cómo evaluarla', 'How to evaluate it'),
            h2=('¿Cómo saber si una estrategia de marketing digital funciona?',
                'How do you know if a digital marketing strategy is working?'),
            intro=('Un plan solo tiene valor si cambia decisiones. Antes de aprobar cualquier documento, revisa que responda tres cosas: qué problema del negocio resuelve, cómo se medirá el avance y quién hace qué cada semana. Estas son las señales que buscamos al revisar una estrategia de marketing digital, ya sea que la hayamos escrito nosotros o que venga de otro equipo, y que puedes usar tú también.',
                   'A plan only has value if it changes decisions. Before you approve any document, check that it answers three things: which business problem it solves, how progress will be measured and who does what each week. These are the signs we look for when we review a digital marketing strategy, whether we wrote it or inherited it from another team, and you can use them too.'),
            items=[
                ('Parte del negocio, no del canal', 'Start from the business, not the channel',
                 'Una estrategia útil empieza por los márgenes, el ciclo de venta, el ticket promedio y la capacidad real de atender nuevos clientes. Recién después elige canales. Si un plan arranca con "necesitamos TikTok" o "hay que publicar más" sin explicar cómo eso se conecta con los ingresos, es una lista de tácticas. Pide el razonamiento detrás de cada canal y el rol que cumple en cada etapa, desde el descubrimiento hasta la recompra.',
                 'A useful strategy begins with margins, sales cycle, average order value and your real capacity to serve new customers. Only then does it choose channels. If a plan opens with "we need TikTok" or "we need more posts" without explaining how that connects to revenue, it is a list of tactics. Ask for the reasoning behind each channel and the role it plays at each stage, from discovery to repeat purchase.'),
                ('Errores frecuentes', 'Common mistakes',
                 'Los errores más comunes son repartir un presupuesto pequeño entre demasiados canales, fijar metas sin una línea base y medir el éxito con alcance o seguidores cuando el negocio necesita ventas. Otra falla habitual es la medición: si las conversiones no se registran bien, cada decisión posterior se apoya en suposiciones. Un buen plan corrige primero los datos, se concentra en menos canales y deja por escrito qué se va a dejar de hacer.',
                 'The most frequent mistakes are spreading a small budget across too many channels, setting goals without a baseline and measuring success with reach or followers when the business needs sales. Another common gap is tracking: if conversions are not recorded correctly, every later decision rests on guesses. A good plan fixes measurement first, focuses on fewer channels and states in writing what will be stopped, not only what will be added.'),
                ('Qué esperar los primeros meses', 'What to expect in the first months',
                 'Las primeras semanas se dedican al diagnóstico, a ordenar los datos y a acordar prioridades. Luego viene una etapa de pruebas en la que algunas ideas funcionan y otras se descartan, y eso es parte del proceso, no un fracaso. En los meses siguientes, el plan se revisa de forma periódica contra sus KPIs y se ajusta. Una estrategia de marketing digital es un documento vivo que tu equipo debe entender lo suficiente como para defender cada decisión.',
                 'The first weeks go to the audit, cleaning up data and agreeing on priorities. Then comes a testing phase where some ideas work and others are discarded; that is part of the process, not a failure. Over the following months, the plan is reviewed regularly against its KPIs and adjusted. A digital marketing strategy is a living document, and your team should understand it well enough to defend each decision it contains.'),
            ],
        ),
        ref=(('Think with Google', 'Think with Google'), 'https://www.thinkwithgoogle.com/'),
    ),

    'performance-marketing': dict(
        kw=('agencia de performance marketing', 'performance marketing agency'),
        title=('Agencia de performance marketing senior | FL Marketing',
               'Performance Marketing Agency: Google &amp; Meta | FL Marketing'),
        desc=('Agencia de performance marketing para campañas en Google, Meta, TikTok y LinkedIn optimizadas por ventas, CPA y ROAS. Revisemos juntos tu cuenta.',
              'Performance marketing agency for Google, Meta, TikTok and LinkedIn campaigns optimized for sales, CPA and ROAS, with clear reports. Let’s review your account.'),
        lead=('Como agencia de performance marketing, gestionamos publicidad digital que se paga y se optimiza según resultados: ventas, leads o retorno sobre la inversión. Diseñamos, ejecutamos y optimizamos campañas en Google, Meta, TikTok y LinkedIn con objetivos claros, datos limpios y pruebas constantes para escalar lo que funciona.',
              'As a performance marketing agency, we run digital advertising that is paid for and optimized based on results: sales, leads or return on ad spend. We design, run and optimize campaigns on Google, Meta, TikTok and LinkedIn with clear goals, clean data and constant testing to scale what works.'),
        h1=('Agencia de performance marketing enfocada en ventas',
            'Performance marketing agency built around revenue'),
        h_inc=('¿Qué incluye el servicio de nuestra agencia de performance marketing?',
               'What does our performance marketing agency service include?'),
        h_faq=('Agencia de performance marketing: preguntas frecuentes',
               'Performance marketing agency: frequently asked questions'),
        guide=dict(
            label=('Cómo elegir', 'How to choose'),
            h2=('¿Cómo elegir una agencia de performance marketing?',
                'How do you choose a performance marketing agency?'),
            intro=('Casi todas las agencias prometen resultados, así que la diferencia aparece en cómo trabajan día a día. Antes de firmar, pide ver cómo estructurarían tu cuenta, qué necesitan de tu parte y cómo reportan. Estos son los puntos que te sugerimos revisar al comparar opciones, incluida la nuestra, para que elijas una agencia de performance marketing con criterio y sin sorpresas.',
                   'Almost every agency promises results, so the difference shows up in how they work day to day. Before you sign, ask to see how they would structure your account, what they need from you and how they report. These are the points we suggest reviewing when you compare options, including us, so you can choose a performance marketing agency with confidence and no surprises.'),
            items=[
                ('Cuentas y datos a tu nombre', 'Account and data ownership',
                 'Tus cuentas publicitarias, píxeles, analítica y datos de conversión deben pertenecer a tu empresa, y la agencia debe trabajar como usuario con permisos. Eso protege tu historial si cambias de proveedor y hace la relación más transparente. Pregunta también cómo se valida la medición antes de lanzar: eventos del servidor, valores de conversión y deduplicación entre plataformas influyen directamente en cómo aprenden los algoritmos y en la precisión de los reportes.',
                 'Your ad accounts, pixels, analytics and conversion data should belong to your company, with the agency working as a user with permissions. That protects your history if you change partners and makes the relationship transparent. Also ask how tracking is validated before launch: server-side events, conversion values and deduplication between platforms directly affect how well the algorithms learn and how accurate your reports will be.'),
                ('Métricas conectadas a ingresos', 'Metrics tied to revenue',
                 'Un clic barato no es un buen resultado si nunca se convierte en cliente. Busca reportes que conecten la inversión con ventas o leads calificados, y que comparen los números de las plataformas con tu CRM o tu tienda. Las actualizaciones semanales deberían explicar qué cambió, por qué y cuál es el siguiente paso. Si un reporte solo muestra impresiones y clics, te costará decidir dónde invertir el próximo dólar.',
                 'A cheap click is not a good result if it never becomes a customer. Look for reports that connect spend to sales or qualified leads, and that compare platform numbers with your CRM or online store. Weekly updates should explain what changed, why and what comes next. If a report only shows impressions and clicks, you will struggle to decide where to invest the next dollar of your budget.'),
                ('Capacidad creativa y de pruebas', 'Creative and testing capacity',
                 'En plataformas como Meta y TikTok la segmentación es cada vez más automática, por lo que el creativo se vuelve una de las principales palancas. Pregunta con qué frecuencia se prueban anuncios nuevos, quién los produce y cómo se documentan los aprendizajes. Una agencia de performance marketing que trabaja junto al equipo de diseño convierte rápido los resultados en nuevos conceptos, en lugar de esperar semanas mientras el presupuesto sigue en anuncios desgastados.',
                 'On platforms like Meta and TikTok, targeting is increasingly automated, so creative becomes one of the main levers. Ask how often new ads are tested, who produces them and how learnings are documented. A performance marketing agency that works closely with design can turn test results into new concepts quickly, instead of waiting weeks for assets while the budget keeps running on tired ads.'),
            ],
        ),
        ref=None,
    ),

    'seo-aeo': dict(
        kw=('servicios de AEO y SEO', 'AEO and SEO services'),
        title=('Servicios de AEO y SEO para Google y la IA | FL Marketing',
               'AEO and SEO Services for Google and AI | FL Marketing'),
        desc=('Servicios de AEO y SEO para posicionar en Google y ser citado por ChatGPT, Gemini y Perplexity. SEO técnico, contenido y medición. Hablemos de tu sitio.',
              'AEO and SEO services to rank on Google and get cited by ChatGPT, Gemini and Perplexity: technical SEO, content and AI visibility tracking. Talk to our team.'),
        lead=('Nuestros servicios de AEO y SEO hacen que tu marca aparezca en Google y sea citada en las respuestas de la IA. El SEO mejora tu posición en buscadores; el AEO (Answer Engine Optimization) estructura tu contenido para que ChatGPT, Gemini, Perplexity y los AI Overviews lo entiendan, lo citen y lo recomienden. Trabajamos ambos como una sola estrategia.',
              'Our AEO and SEO services get your brand found on Google and cited in AI answers. SEO improves your ranking on search engines; AEO (Answer Engine Optimization) structures your content so ChatGPT, Gemini, Perplexity and Google AI Overviews can understand, cite and recommend it. We run both together as one strategy.'),
        h1=('Servicios de AEO y SEO: visibilidad en Google y en la IA',
            'AEO and SEO services: visibility on Google and in AI search'),
        h_inc=('¿Qué incluyen nuestros servicios de AEO y SEO?',
               'What do our AEO and SEO services include?'),
        h_faq=('Servicios de AEO y SEO: preguntas frecuentes',
               'AEO and SEO services: frequently asked questions'),
        guide=dict(
            label=('Primeros meses', 'First months'),
            h2=('¿Qué esperar de los servicios de AEO y SEO en los primeros meses?',
                'What should you expect from AEO and SEO services in the first months?'),
            intro=('La visibilidad orgánica se construye con el tiempo, por eso conviene saber cómo se ve cada etapa antes de empezar. El trabajo avanza desde corregir las bases, pasa por crear y mejorar contenido y llega a medir cómo responden tanto los buscadores como los asistentes de IA. Esta es la secuencia habitual de nuestros servicios de AEO y SEO, ajustada al punto de partida, la competencia y los recursos internos de cada sitio.',
                   'Organic visibility builds over time, so it helps to know what each phase looks like before you start. The work moves from fixing foundations to creating and improving content, and then to measuring how both search engines and AI assistants respond. This is the typical sequence of our AEO and SEO services, adjusted to each site’s starting point, competition and internal resources.'),
            items=[
                ('Primer mes: las bases', 'Month one: foundations',
                 'Empezamos con una auditoría técnica que cubre indexación, velocidad, estructura del sitio y datos estructurados, junto con una revisión de cómo describen hoy tu marca los asistentes de IA. También mapeamos las preguntas que hacen tus compradores y las comparamos con las páginas que ya tienes. El resultado es una lista priorizada: primero los arreglos que destraban el crecimiento y luego los vacíos de contenido con más valor comercial.',
                 'We start with a technical audit covering indexing, speed, site structure and structured data, plus a review of how AI assistants currently describe your brand. We also map the questions your buyers ask and compare them with the pages you already have. The output is a prioritized list: first the fixes that unblock growth, then the content gaps with the most commercial value for your business, so effort goes where it can pay back first.'),
                ('Del segundo al cuarto mes: contenido y autoridad', 'Months two to four: content and authority',
                 'Con la base lista, optimizamos las páginas existentes y publicamos otras nuevas que responden preguntas concretas de forma directa, con definiciones claras y datos de marca consistentes. En paralelo, reforzamos las señales fuera de tu sitio, como perfiles, directorios y menciones en publicaciones relevantes para tu industria. El enlazado interno conecta todo para que Google y los modelos de lenguaje entiendan qué página representa cada tema.',
                 'With the base in place, we optimize existing pages and publish new ones that answer specific questions directly, with clear definitions and consistent brand facts. At the same time, we strengthen signals outside your site, such as business profiles, directories and mentions in publications relevant to your industry. Internal linking connects everything so both Google and language models understand which page represents each topic.'),
                ('Cómo se reporta el avance', 'How progress is reported',
                 'Los reportes combinan métricas clásicas de búsqueda (impresiones, clics, posiciones y conversiones orgánicas) con visibilidad en IA: cuántas veces los asistentes mencionan o citan tu marca en las preguntas prioritarias frente a tus competidores. Los primeros avances suelen venir de las correcciones técnicas y de páginas que estaban cerca de posicionar. El contenido y la autoridad crecen más lento, por eso revisamos prioridades cada mes.',
                 'Reports combine classic search metrics (impressions, clicks, rankings and organic conversions) with AI visibility: how often assistants mention or cite your brand for priority questions compared with your competitors. Early wins usually come from technical fixes and from pages that were already close to ranking. Content and authority compound more slowly, which is why we review priorities every month instead of waiting for one final result, and we explain each change in plain language.'),
            ],
        ),
        ref=None,
    ),

    'aeo-content': dict(
        kw=('contenido AEO', 'AEO content'),
        title=('Contenido AEO para búsqueda con IA y LLMs | FL Marketing',
               'AEO Content for AI Search &amp; LLM Visibility | FL Marketing'),
        desc=('Contenido AEO para que ChatGPT, Gemini y Perplexity entiendan, citen y recomienden tu marca: páginas, guías y FAQs claras. Descubre qué preguntas responder.',
              'AEO content that ChatGPT, Gemini and Perplexity can understand, cite and recommend: clear pages, guides and FAQs built for AI search. See where to start.'),
        lead=('El contenido AEO es contenido estructurado para que los motores de respuesta basados en IA puedan entenderlo, resumirlo y recomendar tu marca. Creamos páginas, guías y preguntas frecuentes con definiciones claras, respuestas directas y datos verificables, pensadas tanto para personas como para modelos de lenguaje.',
              'AEO content is content structured so AI-powered answer engines can understand it, summarize it and recommend your brand. We create pages, guides and FAQs with clear definitions, direct answers and verifiable facts, written for both people and language models, so your expertise appears where customers now ask their questions.'),
        h1=('Contenido AEO para aparecer en respuestas de IA',
            'AEO content that gets cited by AI'),
        h_inc=('¿Qué incluye nuestro servicio de contenido AEO?',
               'What does our AEO content service include?'),
        h_faq=('Contenido AEO: preguntas frecuentes',
               'AEO content: frequently asked questions'),
        guide=dict(
            label=('Buenas prácticas', 'Best practices'),
            h2=('¿Cómo se escribe contenido AEO que la IA cite?',
                'How do you write AEO content that AI assistants cite?'),
            intro=('Que un asistente te cite depende menos del largo del texto y más de lo fácil que le resulte extraer una respuesta correcta y atribuírtela. Las prácticas que siguen guían cada pieza de contenido AEO que producimos, desde páginas de servicio hasta guías extensas. También puedes usarlas para revisar las páginas que ya tienes antes de crear otras nuevas.',
                   'Being cited depends less on length and more on how easy it is for a model to extract a correct answer and attribute it to you. The practices below guide every piece of AEO content we produce, from service pages to long guides. You can also use them to review the pages you already have before you invest in creating new ones, since improving an existing page is often faster than starting from zero.'),
            items=[
                ('Una pregunta, una respuesta', 'One question, one answer',
                 'Cada sección debería plantear una pregunta concreta en su título y responderla en las primeras oraciones, sin depender del contexto de otras partes de la página. Después viene el detalle: pasos, ejemplos, condiciones o excepciones. Esta estructura ayuda a quien lee en diagonal y le da a los modelos de lenguaje bloques autónomos que pueden citar con precisión. Las introducciones vagas que retrasan la respuesta alejan a ambos.',
                 'Each section should pose a specific question in its heading and answer it in the first sentences, without depending on context from other parts of the page. Then add the detail: steps, examples, conditions or exceptions. This structure helps readers who skim and gives language models self-contained blocks they can quote accurately. Vague introductions that delay the answer push both audiences away.'),
                ('Datos que se pueden verificar', 'Facts you can verify',
                 'Los modelos tienden a confiar en afirmaciones específicas y consistentes entre fuentes. Usa nombres exactos para productos, servicios y ubicaciones, y mantenlos idénticos en tu sitio, tus perfiles y los directorios donde apareces. Cuando menciones una cifra, indica de dónde viene y cuándo se publicó. Evita afirmaciones que no puedas respaldar: un dato inconsistente puede llevar a un asistente a describir tu marca de forma incorrecta.',
                 'Models tend to trust statements that are specific and consistent across sources. Use exact names for products, services and locations, and keep them identical on your site, your profiles and the directories where you appear. When you mention a figure, say where it comes from and when it was published. Avoid claims you cannot support: an inconsistent fact can lead an assistant to describe your brand incorrectly, and that error can repeat across many answers.'),
                ('Errores frecuentes', 'Common mistakes',
                 'El error más común es reescribir artículos antiguos con más palabras clave y llamarlo AEO. Otros son esconder las respuestas en imágenes o acordeones que no cargan en el HTML, publicar sin un autor identificado y crear decenas de páginas de preguntas frecuentes con poco fondo. El contenido AEO funciona mejor como un conjunto más pequeño de páginas completas y bien mantenidas, que actualizas cuando cambia tu oferta.',
                 'The most common mistake is rewriting old blog posts with more keywords and calling it AEO. Others include hiding answers inside images or accordions that do not load in the HTML, publishing without a named author and creating dozens of thin FAQ pages. AEO content works better as a smaller set of complete, well-maintained pages that you update whenever your offer, pricing or services change.'),
            ],
        ),
        ref=None,
    ),

    'design-branding': dict(
        kw=('diseño gráfico y branding', 'graphic design and branding'),
        title=('Diseño gráfico y branding con estrategia | FL Marketing',
               'Graphic Design and Branding Services | FL Marketing'),
        desc=('Diseño gráfico y branding con Vero Design: identidad visual, piezas para redes, anuncios y video coherentes en cada canal. Conversemos sobre tu marca hoy.',
              'Graphic design and branding with Vero Design: visual identity, social content, ad creatives and video that stay consistent on every channel. Let’s talk today.'),
        lead=('El diseño gráfico y branding le dan a tu marca una identidad visual coherente y piezas que comunican con claridad en cada canal. En alianza con Vero Design, con más de 200 marcas creadas en más de 7 países, creamos identidades, piezas para redes, anuncios y video con criterio estratégico.',
              'Graphic design and branding give your brand a consistent visual identity and assets that communicate clearly on every channel. In partnership with Vero Design, with 200+ brands created across 7+ countries, we create identities, social content, ads and video with a strategic approach tied to your business goals.'),
        h1=('Diseño gráfico y branding con enfoque estratégico',
            'Graphic design and branding with a strategic approach'),
        h_inc=('¿Qué incluye nuestro servicio de diseño gráfico y branding?',
               'What does our graphic design and branding service include?'),
        h_faq=('Diseño gráfico y branding: preguntas frecuentes',
               'Graphic design and branding: frequently asked questions'),
        guide=dict(
            label=('Cómo trabajamos', 'How we work'),
            h2=('Diseño gráfico y branding: ¿cómo apoyan tus resultados de marketing?',
                'How do graphic design and branding support your marketing results?'),
            intro=('El buen diseño no se trata solo de verse mejor. Una identidad reconocible hace que cada campaña se recuerde con más facilidad, y un sistema claro permite a tu equipo producir piezas más rápido sin perder coherencia. Así conectamos el diseño gráfico y branding con la estrategia: qué preparar antes de un proyecto y cómo sigue el trabajo una vez que la identidad está lanzada.',
                   'Good design is not only about looking better. A recognizable identity makes every campaign easier to remember, and a clear system lets your team produce assets faster without losing consistency. Here is how we connect graphic design and branding with strategy: what to prepare before a project starts and how the work continues once the new identity is launched and starts appearing in real campaigns.'),
            items=[
                ('Empieza por el posicionamiento', 'Start with positioning',
                 'Antes de bocetar un logo, definimos a quién le habla la marca, qué la hace diferente y qué sensación debe dejar. Esas decisiones guían el color, la tipografía y el tono, y evitan elecciones basadas solo en el gusto personal. Si ya cuentas con investigación, entrevistas a clientes o comentarios del equipo de ventas, compártelos al inicio: acortan el proceso y hacen más objetivas las rondas de revisión.',
                 'Before sketching a logo, we define who the brand speaks to, what makes it different and which feeling it should leave. Those decisions guide color, typography and tone, and they prevent choices based only on personal taste. If you already have research, customer interviews or feedback from your sales team, share it at the start: it shortens the process and makes review rounds more objective.'),
                ('Un sistema, no solo un logo', 'A system, not just a logo',
                 'Un logo por sí solo no mantiene la coherencia de una marca. Lo que ayuda es un sistema: reglas de color y tipografía, retícula, estilo fotográfico, iconografía y plantillas para formatos recurrentes como posts, anuncios y presentaciones. Tomamos como referencia guías como Material Design para cuidar la accesibilidad y la jerarquía, de modo que el texto siga siendo legible y el contraste funcione en pantallas pequeñas.',
                 'A logo alone does not keep a brand consistent. What helps is a system: color and type rules, grid, photography style, iconography and templates for recurring formats like posts, ads and presentations. We use references such as Material Design to care for accessibility and hierarchy, so text stays legible and contrast works on small screens, where much of your audience will see the brand first, often while scrolling quickly.'),
                ('Diseño y performance conectados', 'Design and performance, connected',
                 'Cuando la identidad ya está activa, el diseño pasa a formar parte de la rutina de crecimiento. Los creativos para anuncios se producen en variaciones para que el equipo de medios pruebe mensajes y formatos, y los resultados alimentan la siguiente ronda de piezas. Este ciclo mantiene el diseño gráfico y branding alineados con los datos: la marca sigue siendo reconocible mientras cada pieza se ajusta a lo que tu audiencia responde.',
                 'Once the identity is live, design becomes part of the growth routine. Ad creatives are produced in variations so the media team can test messages and formats, and the results feed the next round of assets. This loop keeps graphic design and branding aligned with data: the brand stays recognizable while each piece is adjusted to what your audience actually responds to.'),
            ],
        ),
        ref=(('Material Design 3, Google', 'Material Design 3 by Google'), 'https://m3.material.io/'),
    ),
}
